// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: gitpod/v1/agent_security.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/gitpod-io/terraform-provider-ona/api/public-clients/go/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AgentSecurityServiceName is the fully-qualified name of the AgentSecurityService service.
	AgentSecurityServiceName = "gitpod.v1.AgentSecurityService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentSecurityServiceReportExecEventProcedure is the fully-qualified name of the
	// AgentSecurityService's ReportExecEvent RPC.
	AgentSecurityServiceReportExecEventProcedure = "/gitpod.v1.AgentSecurityService/ReportExecEvent"
)

// AgentSecurityServiceClient is a client for the gitpod.v1.AgentSecurityService service.
type AgentSecurityServiceClient interface {
	// ReportExecEvent reports a blocked or audited process execution.
	//
	// Use this method to:
	// - Report process executions that were blocked or audited by security policy
	//
	// ### Examples
	//
	// - Report a blocked execution:
	//
	//	```yaml
	//	environmentId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	executable: "sha256:a1b2c3d4..."
	//	filename: "/usr/bin/curl"
	//	action: KERNEL_CONTROLS_ACTION_BLOCK
	//	process:
	//	  pid: 1234
	//	  tid: 1234
	//	  name: "curl"
	//	  cmdline: "curl https://example.com"
	//	  startedAt: "2026-01-15T10:30:00Z"
	//	  ppid: 1000
	//	  pgid: 1000
	//	  sid: 1000
	//	timestamp: "2026-01-15T10:30:00Z"
	//	```
	ReportExecEvent(context.Context, *connect.Request[v1.ReportExecEventRequest]) (*connect.Response[v1.ReportExecEventResponse], error)
}

// NewAgentSecurityServiceClient constructs a client for the gitpod.v1.AgentSecurityService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentSecurityServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentSecurityServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentSecurityServiceMethods := v1.File_gitpod_v1_agent_security_proto.Services().ByName("AgentSecurityService").Methods()
	return &agentSecurityServiceClient{
		reportExecEvent: connect.NewClient[v1.ReportExecEventRequest, v1.ReportExecEventResponse](
			httpClient,
			baseURL+AgentSecurityServiceReportExecEventProcedure,
			connect.WithSchema(agentSecurityServiceMethods.ByName("ReportExecEvent")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentSecurityServiceClient implements AgentSecurityServiceClient.
type agentSecurityServiceClient struct {
	reportExecEvent *connect.Client[v1.ReportExecEventRequest, v1.ReportExecEventResponse]
}

// ReportExecEvent calls gitpod.v1.AgentSecurityService.ReportExecEvent.
func (c *agentSecurityServiceClient) ReportExecEvent(ctx context.Context, req *connect.Request[v1.ReportExecEventRequest]) (*connect.Response[v1.ReportExecEventResponse], error) {
	return c.reportExecEvent.CallUnary(ctx, req)
}

// AgentSecurityServiceHandler is an implementation of the gitpod.v1.AgentSecurityService service.
type AgentSecurityServiceHandler interface {
	// ReportExecEvent reports a blocked or audited process execution.
	//
	// Use this method to:
	// - Report process executions that were blocked or audited by security policy
	//
	// ### Examples
	//
	// - Report a blocked execution:
	//
	//	```yaml
	//	environmentId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	executable: "sha256:a1b2c3d4..."
	//	filename: "/usr/bin/curl"
	//	action: KERNEL_CONTROLS_ACTION_BLOCK
	//	process:
	//	  pid: 1234
	//	  tid: 1234
	//	  name: "curl"
	//	  cmdline: "curl https://example.com"
	//	  startedAt: "2026-01-15T10:30:00Z"
	//	  ppid: 1000
	//	  pgid: 1000
	//	  sid: 1000
	//	timestamp: "2026-01-15T10:30:00Z"
	//	```
	ReportExecEvent(context.Context, *connect.Request[v1.ReportExecEventRequest]) (*connect.Response[v1.ReportExecEventResponse], error)
}

// NewAgentSecurityServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentSecurityServiceHandler(svc AgentSecurityServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentSecurityServiceMethods := v1.File_gitpod_v1_agent_security_proto.Services().ByName("AgentSecurityService").Methods()
	agentSecurityServiceReportExecEventHandler := connect.NewUnaryHandler(
		AgentSecurityServiceReportExecEventProcedure,
		svc.ReportExecEvent,
		connect.WithSchema(agentSecurityServiceMethods.ByName("ReportExecEvent")),
		connect.WithHandlerOptions(opts...),
	)
	return "/gitpod.v1.AgentSecurityService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentSecurityServiceReportExecEventProcedure:
			agentSecurityServiceReportExecEventHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentSecurityServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentSecurityServiceHandler struct{}

func (UnimplementedAgentSecurityServiceHandler) ReportExecEvent(context.Context, *connect.Request[v1.ReportExecEventRequest]) (*connect.Response[v1.ReportExecEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.AgentSecurityService.ReportExecEvent is not implemented"))
}
