// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: gitpod/v1/billing.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/gitpod-io/terraform-provider-ona/api/public-clients/go/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BillingServiceName is the fully-qualified name of the BillingService service.
	BillingServiceName = "gitpod.v1.BillingService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BillingServiceGetCreditUsageReportProcedure is the fully-qualified name of the BillingService's
	// GetCreditUsageReport RPC.
	BillingServiceGetCreditUsageReportProcedure = "/gitpod.v1.BillingService/GetCreditUsageReport"
	// BillingServiceGetCreditUsageExportProcedure is the fully-qualified name of the BillingService's
	// GetCreditUsageExport RPC.
	BillingServiceGetCreditUsageExportProcedure = "/gitpod.v1.BillingService/GetCreditUsageExport"
	// BillingServiceGetEnterpriseAIUsageSummaryProcedure is the fully-qualified name of the
	// BillingService's GetEnterpriseAIUsageSummary RPC.
	BillingServiceGetEnterpriseAIUsageSummaryProcedure = "/gitpod.v1.BillingService/GetEnterpriseAIUsageSummary"
	// BillingServiceListEnterpriseAITeamUsageProcedure is the fully-qualified name of the
	// BillingService's ListEnterpriseAITeamUsage RPC.
	BillingServiceListEnterpriseAITeamUsageProcedure = "/gitpod.v1.BillingService/ListEnterpriseAITeamUsage"
	// BillingServiceListEnterpriseAIUserUsageProcedure is the fully-qualified name of the
	// BillingService's ListEnterpriseAIUserUsage RPC.
	BillingServiceListEnterpriseAIUserUsageProcedure = "/gitpod.v1.BillingService/ListEnterpriseAIUserUsage"
	// BillingServiceGetEnterpriseAIUsageTimeSeriesProcedure is the fully-qualified name of the
	// BillingService's GetEnterpriseAIUsageTimeSeries RPC.
	BillingServiceGetEnterpriseAIUsageTimeSeriesProcedure = "/gitpod.v1.BillingService/GetEnterpriseAIUsageTimeSeries"
	// BillingServiceGetEnterpriseAIUserBudgetPolicyProcedure is the fully-qualified name of the
	// BillingService's GetEnterpriseAIUserBudgetPolicy RPC.
	BillingServiceGetEnterpriseAIUserBudgetPolicyProcedure = "/gitpod.v1.BillingService/GetEnterpriseAIUserBudgetPolicy"
	// BillingServiceSetEnterpriseAIUserBudgetPolicyProcedure is the fully-qualified name of the
	// BillingService's SetEnterpriseAIUserBudgetPolicy RPC.
	BillingServiceSetEnterpriseAIUserBudgetPolicyProcedure = "/gitpod.v1.BillingService/SetEnterpriseAIUserBudgetPolicy"
	// BillingServiceDeleteEnterpriseAIUserBudgetPolicyProcedure is the fully-qualified name of the
	// BillingService's DeleteEnterpriseAIUserBudgetPolicy RPC.
	BillingServiceDeleteEnterpriseAIUserBudgetPolicyProcedure = "/gitpod.v1.BillingService/DeleteEnterpriseAIUserBudgetPolicy"
	// BillingServiceGetCumulativeCreditUsageProcedure is the fully-qualified name of the
	// BillingService's GetCumulativeCreditUsage RPC.
	BillingServiceGetCumulativeCreditUsageProcedure = "/gitpod.v1.BillingService/GetCumulativeCreditUsage"
	// BillingServiceListEnterpriseUserCreditUsageProcedure is the fully-qualified name of the
	// BillingService's ListEnterpriseUserCreditUsage RPC.
	BillingServiceListEnterpriseUserCreditUsageProcedure = "/gitpod.v1.BillingService/ListEnterpriseUserCreditUsage"
	// BillingServiceCreateTeamCreditAllocationProcedure is the fully-qualified name of the
	// BillingService's CreateTeamCreditAllocation RPC.
	BillingServiceCreateTeamCreditAllocationProcedure = "/gitpod.v1.BillingService/CreateTeamCreditAllocation"
	// BillingServiceGetTeamCreditAllocationProcedure is the fully-qualified name of the
	// BillingService's GetTeamCreditAllocation RPC.
	BillingServiceGetTeamCreditAllocationProcedure = "/gitpod.v1.BillingService/GetTeamCreditAllocation"
	// BillingServiceUpdateTeamCreditAllocationProcedure is the fully-qualified name of the
	// BillingService's UpdateTeamCreditAllocation RPC.
	BillingServiceUpdateTeamCreditAllocationProcedure = "/gitpod.v1.BillingService/UpdateTeamCreditAllocation"
	// BillingServiceDeleteTeamCreditAllocationProcedure is the fully-qualified name of the
	// BillingService's DeleteTeamCreditAllocation RPC.
	BillingServiceDeleteTeamCreditAllocationProcedure = "/gitpod.v1.BillingService/DeleteTeamCreditAllocation"
)

// BillingServiceClient is a client for the gitpod.v1.BillingService service.
type BillingServiceClient interface {
	// Returns a daily credit usage report for an enterprise organization.
	//
	// Each day reports org-wide credits by usage type, plus per-user, per-team,
	// per-environment, and per-conversation breakdowns (top consumers with the
	// remainder aggregated into an "Others" bucket) and a per-model breakdown
	// of intelligence usage.
	//
	// Use this method to:
	// - Chart daily credit consumption over a date range
	// - Attribute credit usage to users, teams, environments, and conversations
	// - Restrict the report to a single user or service account
	//
	// ### Examples
	//
	// - Get the report for January:
	//
	//	Both dates are inclusive and the range must not exceed 31 days.
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	dateRange:
	//	  startTime: "2024-01-01T00:00:00Z"
	//	  endTime: "2024-01-31T00:00:00Z"
	//	```
	//
	// ### Authorization
	//
	// Requires `billing:read_usage` permission on the organization. A user
	// without it can read their own usage by setting filter.subject to their
	// own user identity; this self-access path is not available to service
	// accounts.
	GetCreditUsageReport(context.Context, *connect.Request[v1.GetCreditUsageReportRequest]) (*connect.Response[v1.GetCreditUsageReportResponse], error)
	// Returns a signed download URL for a CSV export of credit usage.
	//
	// The URL points to an HTTP endpoint that streams gzip-compressed CSV and
	// is valid for five minutes. The download must be made by the same principal
	// that requested it, carrying its own bearer token. The export range may
	// cover up to a year.
	//
	// For organizations without enterprise credit usage enabled (no billing
	// contract start date), the export instead contains BYOK cost usage with a
	// different column set, and groupBy=RESOURCE is rejected.
	//
	// Use this method to:
	// - Export per-user daily credit usage for external reporting
	// - Export a per-environment and per-conversation resource breakdown
	//
	// ### Examples
	//
	// - Export January's daily summary:
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	dateRange:
	//	  startTime: "2024-01-01T00:00:00Z"
	//	  endTime: "2024-01-31T00:00:00Z"
	//	groupBy: CREDIT_USAGE_EXPORT_GROUP_BY_DAILY_SUMMARY
	//	```
	//
	// ### Authorization
	//
	// Requires `billing:read_usage` permission on the organization.
	GetCreditUsageExport(context.Context, *connect.Request[v1.GetCreditUsageExportRequest]) (*connect.Response[v1.GetCreditUsageExportResponse], error)
	// Returns organization-level enterprise AI usage totals for reporting.
	//
	// Reports BYOK (bring-your-own-key) token spend: cost in the
	// organization's billing currency plus token counts, with a per-model
	// breakdown. Credit-based usage from managed models is not included and
	// the credits field is not populated by this endpoint.
	//
	// Use this method to:
	// - Report total BYOK AI spend (cost and tokens) for a date range
	// - Break down organization usage by model
	//
	// Only available for enterprise organizations.
	//
	// ### Examples
	//
	// - Get usage totals for January:
	//
	//	Returns organization-wide BYOK spend for the month. Both dates are
	//	inclusive and the range must not exceed 31 days.
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	dateRange:
	//	  startTime: "2024-01-01T00:00:00Z"
	//	  endTime: "2024-01-31T00:00:00Z"
	//	```
	//
	// ### Authorization
	//
	// Requires `billing:read_usage` permission on the organization.
	GetEnterpriseAIUsageSummary(context.Context, *connect.Request[v1.GetEnterpriseAIUsageSummaryRequest]) (*connect.Response[v1.GetEnterpriseAIUsageSummaryResponse], error)
	// Lists enterprise AI usage grouped by team.
	//
	// Reports BYOK token spend per team (cost and tokens) with each team's
	// monthly budget when one applies. The credits field is not populated by
	// this endpoint.
	//
	// Use this method to:
	// - Compare BYOK AI spend across teams
	// - Track team budget utilization
	// - Filter usage to specific teams
	//
	// Only available for enterprise organizations.
	//
	// ### Examples
	//
	// - List team usage for January:
	//
	//	Returns BYOK spend per team with monthly budgets. Both dates are
	//	inclusive and the range must not exceed 31 days.
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	dateRange:
	//	  startTime: "2024-01-01T00:00:00Z"
	//	  endTime: "2024-01-31T00:00:00Z"
	//	```
	//
	// ### Authorization
	//
	// Requires `billing:read_usage` permission on the organization.
	ListEnterpriseAITeamUsage(context.Context, *connect.Request[v1.ListEnterpriseAITeamUsageRequest]) (*connect.Response[v1.ListEnterpriseAITeamUsageResponse], error)
	// Lists enterprise AI usage grouped by user with effective monthly budget data.
	//
	// Reports BYOK token spend (cost and tokens) for each user and service
	// account with attributed usage in the date range, including each
	// subject's effective monthly budget. Usage not attributed to a user or
	// service account is excluded, so the sum across subjects can be less
	// than the organization totals from GetEnterpriseAIUsageSummary. The
	// credits field is not populated by this endpoint.
	//
	// Budget fields (month_to_date_usage, utilization_percent, over_budget)
	// are computed from usage inside the requested date range measured
	// against the monthly limit. Send a range that starts on the first day
	// of the month for true month-to-date figures.
	//
	// Use this method to:
	// - Export per-user BYOK AI spend to external reporting
	// - Identify the highest spenders in the organization
	// - Track per-user budget utilization and over-budget users
	//
	// Only available for enterprise organizations.
	//
	// ### Examples
	//
	// - List user usage for January:
	//
	//	Returns per-user BYOK spend with effective budgets, highest spend
	//	first. Both dates are inclusive and the range must not exceed 31 days.
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	dateRange:
	//	  startTime: "2024-01-01T00:00:00Z"
	//	  endTime: "2024-01-31T00:00:00Z"
	//	```
	//
	// ### Authorization
	//
	// Requires `billing:read_usage` permission on the organization. Callers
	// without it can read their own usage by setting filter.subject to
	// themselves.
	ListEnterpriseAIUserUsage(context.Context, *connect.Request[v1.ListEnterpriseAIUserUsageRequest]) (*connect.Response[v1.ListEnterpriseAIUserUsageResponse], error)
	// Returns daily enterprise AI usage totals for the organization.
	//
	// Each day reports BYOK token spend (cost and tokens) with per-user,
	// per-team, and per-model breakdowns. Per-user entries cover the top
	// spenders with the remainder aggregated into an "Others" bucket; usage
	// not attributed to a user or service account appears only in the daily
	// totals. The credits field is not populated by this endpoint.
	//
	// When filter.subject is set the response contains only that subject's
	// usage: daily totals and the team breakdown are omitted, and the model
	// breakdown covers the subject only.
	//
	// Use this method to:
	// - Chart daily BYOK AI spend over a date range
	// - Feed daily per-user usage into external dashboards
	// - Restrict the response to a single user or service account
	//
	// Only available for enterprise organizations.
	//
	// ### Examples
	//
	// - Get daily usage for January:
	//
	//	Returns one entry per day with per-user, per-team, and per-model
	//	breakdowns. Both dates are inclusive and the range must not exceed
	//	31 days.
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	dateRange:
	//	  startTime: "2024-01-01T00:00:00Z"
	//	  endTime: "2024-01-31T00:00:00Z"
	//	```
	//
	// ### Authorization
	//
	// Requires `billing:read_usage` permission on the organization.
	GetEnterpriseAIUsageTimeSeries(context.Context, *connect.Request[v1.GetEnterpriseAIUsageTimeSeriesRequest]) (*connect.Response[v1.GetEnterpriseAIUsageTimeSeriesResponse], error)
	// Gets the configured and effective monthly budget policy for a user or org.
	//
	// When user_id is provided, the response includes any direct user override
	// and the effective policy after applying the organization default. When
	// user_id is omitted, both fields describe the organization default.
	//
	// ### Authorization
	//
	// Requires `billing:read_usage` permission on the organization.
	GetEnterpriseAIUserBudgetPolicy(context.Context, *connect.Request[v1.GetEnterpriseAIUserBudgetPolicyRequest]) (*connect.Response[v1.GetEnterpriseAIUserBudgetPolicyResponse], error)
	// Sets the organization default or a per-user monthly budget policy.
	//
	// A user policy overrides the organization default. Set no_cap to exempt a
	// user from the default monthly budget.
	//
	// ### Authorization
	//
	// Requires `billing:update` permission on the organization.
	SetEnterpriseAIUserBudgetPolicy(context.Context, *connect.Request[v1.SetEnterpriseAIUserBudgetPolicyRequest]) (*connect.Response[v1.SetEnterpriseAIUserBudgetPolicyResponse], error)
	// Deletes the organization default or a per-user monthly budget policy.
	//
	// ### Authorization
	//
	// Requires `billing:delete` permission on the organization.
	DeleteEnterpriseAIUserBudgetPolicy(context.Context, *connect.Request[v1.DeleteEnterpriseAIUserBudgetPolicyRequest]) (*connect.Response[v1.DeleteEnterpriseAIUserBudgetPolicyResponse], error)
	// Returns cumulative credit usage for an organization and its teams.
	//
	// Use this method to:
	// - Get the total cumulative credit consumption as of a point in time
	// - Get per-team cumulative usage with credit allocation (budget) comparison
	// - Display team credit summaries on the usage page and team detail page
	// - Display user budget utilization when user budgets are enabled
	//
	// ### Examples
	//
	// - Get current cumulative usage:
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	```
	//
	// - Get cumulative usage as of a specific date:
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	asOf: "2026-03-31T23:59:59Z"
	//	```
	//
	// ### Authorization
	//
	// Requires `billing:read_usage` permission on the organization.
	GetCumulativeCreditUsage(context.Context, *connect.Request[v1.GetCumulativeCreditUsageRequest]) (*connect.Response[v1.GetCumulativeCreditUsageResponse], error)
	// Lists per-user month-to-date credit usage with effective monthly budgets.
	//
	// Results are ordered by total credits descending so the highest spenders
	// appear first, with user_id as a stable tiebreaker. Use cursor pagination
	// to walk the full set for large organizations.
	//
	// The default SORT_FIELD_USAGE ordering supports cursor pagination over any
	// number of users. Sorting by display name, budget, or budget utilization
	// computes the order in memory and is limited to organizations with at most
	// 10,000 users; beyond that, use SORT_FIELD_USAGE. Because month-to-date
	// figures are recomputed per request, hold a date range stable across a
	// paginated walk to keep page tokens valid.
	//
	// Use this method to:
	// - Export per-user credit usage to external reporting
	// - Identify the highest spenders in the organization
	// - Track per-user budget utilization and over-budget users
	//
	// ### Examples
	//
	// - List user usage for the current month:
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	pagination:
	//	  pageSize: 50
	//	```
	//
	// ### Authorization
	//
	// Requires `billing:read_usage` permission on the organization.
	ListEnterpriseUserCreditUsage(context.Context, *connect.Request[v1.ListEnterpriseUserCreditUsageRequest]) (*connect.Response[v1.ListEnterpriseUserCreditUsageResponse], error)
	// Creates a credit allocation (budget) for a team.
	//
	// Allocations are soft budgets for reporting and alerting — not enforced at usage time.
	// Over-allocation (sum of team budgets > org grant) is allowed.
	//
	// ### Examples
	//
	// - Create a team allocation:
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	teamId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	creditBudget: "500"
	//	```
	//
	// ### Authorization
	//
	// Requires `billing:create` permission on the organization.
	CreateTeamCreditAllocation(context.Context, *connect.Request[v1.CreateTeamCreditAllocationRequest]) (*connect.Response[v1.CreateTeamCreditAllocationResponse], error)
	// Gets the credit allocation for a team.
	//
	// ### Examples
	//
	// - Get a team's allocation:
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	teamId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	//
	// ### Authorization
	//
	// Requires `billing:read` permission on the organization.
	GetTeamCreditAllocation(context.Context, *connect.Request[v1.GetTeamCreditAllocationRequest]) (*connect.Response[v1.GetTeamCreditAllocationResponse], error)
	// Updates the credit allocation for a team.
	//
	// ### Examples
	//
	// - Update a team's budget:
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	teamId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	creditBudget: "750"
	//	```
	//
	// ### Authorization
	//
	// Requires `billing:update` permission on the organization.
	UpdateTeamCreditAllocation(context.Context, *connect.Request[v1.UpdateTeamCreditAllocationRequest]) (*connect.Response[v1.UpdateTeamCreditAllocationResponse], error)
	// Deletes the credit allocation for a team.
	//
	// ### Examples
	//
	// - Delete a team's allocation:
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	teamId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	//
	// ### Authorization
	//
	// Requires `billing:delete` permission on the organization.
	DeleteTeamCreditAllocation(context.Context, *connect.Request[v1.DeleteTeamCreditAllocationRequest]) (*connect.Response[v1.DeleteTeamCreditAllocationResponse], error)
}

// NewBillingServiceClient constructs a client for the gitpod.v1.BillingService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBillingServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BillingServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	billingServiceMethods := v1.File_gitpod_v1_billing_proto.Services().ByName("BillingService").Methods()
	return &billingServiceClient{
		getCreditUsageReport: connect.NewClient[v1.GetCreditUsageReportRequest, v1.GetCreditUsageReportResponse](
			httpClient,
			baseURL+BillingServiceGetCreditUsageReportProcedure,
			connect.WithSchema(billingServiceMethods.ByName("GetCreditUsageReport")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getCreditUsageExport: connect.NewClient[v1.GetCreditUsageExportRequest, v1.GetCreditUsageExportResponse](
			httpClient,
			baseURL+BillingServiceGetCreditUsageExportProcedure,
			connect.WithSchema(billingServiceMethods.ByName("GetCreditUsageExport")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getEnterpriseAIUsageSummary: connect.NewClient[v1.GetEnterpriseAIUsageSummaryRequest, v1.GetEnterpriseAIUsageSummaryResponse](
			httpClient,
			baseURL+BillingServiceGetEnterpriseAIUsageSummaryProcedure,
			connect.WithSchema(billingServiceMethods.ByName("GetEnterpriseAIUsageSummary")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listEnterpriseAITeamUsage: connect.NewClient[v1.ListEnterpriseAITeamUsageRequest, v1.ListEnterpriseAITeamUsageResponse](
			httpClient,
			baseURL+BillingServiceListEnterpriseAITeamUsageProcedure,
			connect.WithSchema(billingServiceMethods.ByName("ListEnterpriseAITeamUsage")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listEnterpriseAIUserUsage: connect.NewClient[v1.ListEnterpriseAIUserUsageRequest, v1.ListEnterpriseAIUserUsageResponse](
			httpClient,
			baseURL+BillingServiceListEnterpriseAIUserUsageProcedure,
			connect.WithSchema(billingServiceMethods.ByName("ListEnterpriseAIUserUsage")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getEnterpriseAIUsageTimeSeries: connect.NewClient[v1.GetEnterpriseAIUsageTimeSeriesRequest, v1.GetEnterpriseAIUsageTimeSeriesResponse](
			httpClient,
			baseURL+BillingServiceGetEnterpriseAIUsageTimeSeriesProcedure,
			connect.WithSchema(billingServiceMethods.ByName("GetEnterpriseAIUsageTimeSeries")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getEnterpriseAIUserBudgetPolicy: connect.NewClient[v1.GetEnterpriseAIUserBudgetPolicyRequest, v1.GetEnterpriseAIUserBudgetPolicyResponse](
			httpClient,
			baseURL+BillingServiceGetEnterpriseAIUserBudgetPolicyProcedure,
			connect.WithSchema(billingServiceMethods.ByName("GetEnterpriseAIUserBudgetPolicy")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		setEnterpriseAIUserBudgetPolicy: connect.NewClient[v1.SetEnterpriseAIUserBudgetPolicyRequest, v1.SetEnterpriseAIUserBudgetPolicyResponse](
			httpClient,
			baseURL+BillingServiceSetEnterpriseAIUserBudgetPolicyProcedure,
			connect.WithSchema(billingServiceMethods.ByName("SetEnterpriseAIUserBudgetPolicy")),
			connect.WithClientOptions(opts...),
		),
		deleteEnterpriseAIUserBudgetPolicy: connect.NewClient[v1.DeleteEnterpriseAIUserBudgetPolicyRequest, v1.DeleteEnterpriseAIUserBudgetPolicyResponse](
			httpClient,
			baseURL+BillingServiceDeleteEnterpriseAIUserBudgetPolicyProcedure,
			connect.WithSchema(billingServiceMethods.ByName("DeleteEnterpriseAIUserBudgetPolicy")),
			connect.WithClientOptions(opts...),
		),
		getCumulativeCreditUsage: connect.NewClient[v1.GetCumulativeCreditUsageRequest, v1.GetCumulativeCreditUsageResponse](
			httpClient,
			baseURL+BillingServiceGetCumulativeCreditUsageProcedure,
			connect.WithSchema(billingServiceMethods.ByName("GetCumulativeCreditUsage")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listEnterpriseUserCreditUsage: connect.NewClient[v1.ListEnterpriseUserCreditUsageRequest, v1.ListEnterpriseUserCreditUsageResponse](
			httpClient,
			baseURL+BillingServiceListEnterpriseUserCreditUsageProcedure,
			connect.WithSchema(billingServiceMethods.ByName("ListEnterpriseUserCreditUsage")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		createTeamCreditAllocation: connect.NewClient[v1.CreateTeamCreditAllocationRequest, v1.CreateTeamCreditAllocationResponse](
			httpClient,
			baseURL+BillingServiceCreateTeamCreditAllocationProcedure,
			connect.WithSchema(billingServiceMethods.ByName("CreateTeamCreditAllocation")),
			connect.WithClientOptions(opts...),
		),
		getTeamCreditAllocation: connect.NewClient[v1.GetTeamCreditAllocationRequest, v1.GetTeamCreditAllocationResponse](
			httpClient,
			baseURL+BillingServiceGetTeamCreditAllocationProcedure,
			connect.WithSchema(billingServiceMethods.ByName("GetTeamCreditAllocation")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updateTeamCreditAllocation: connect.NewClient[v1.UpdateTeamCreditAllocationRequest, v1.UpdateTeamCreditAllocationResponse](
			httpClient,
			baseURL+BillingServiceUpdateTeamCreditAllocationProcedure,
			connect.WithSchema(billingServiceMethods.ByName("UpdateTeamCreditAllocation")),
			connect.WithClientOptions(opts...),
		),
		deleteTeamCreditAllocation: connect.NewClient[v1.DeleteTeamCreditAllocationRequest, v1.DeleteTeamCreditAllocationResponse](
			httpClient,
			baseURL+BillingServiceDeleteTeamCreditAllocationProcedure,
			connect.WithSchema(billingServiceMethods.ByName("DeleteTeamCreditAllocation")),
			connect.WithClientOptions(opts...),
		),
	}
}

// billingServiceClient implements BillingServiceClient.
type billingServiceClient struct {
	getCreditUsageReport               *connect.Client[v1.GetCreditUsageReportRequest, v1.GetCreditUsageReportResponse]
	getCreditUsageExport               *connect.Client[v1.GetCreditUsageExportRequest, v1.GetCreditUsageExportResponse]
	getEnterpriseAIUsageSummary        *connect.Client[v1.GetEnterpriseAIUsageSummaryRequest, v1.GetEnterpriseAIUsageSummaryResponse]
	listEnterpriseAITeamUsage          *connect.Client[v1.ListEnterpriseAITeamUsageRequest, v1.ListEnterpriseAITeamUsageResponse]
	listEnterpriseAIUserUsage          *connect.Client[v1.ListEnterpriseAIUserUsageRequest, v1.ListEnterpriseAIUserUsageResponse]
	getEnterpriseAIUsageTimeSeries     *connect.Client[v1.GetEnterpriseAIUsageTimeSeriesRequest, v1.GetEnterpriseAIUsageTimeSeriesResponse]
	getEnterpriseAIUserBudgetPolicy    *connect.Client[v1.GetEnterpriseAIUserBudgetPolicyRequest, v1.GetEnterpriseAIUserBudgetPolicyResponse]
	setEnterpriseAIUserBudgetPolicy    *connect.Client[v1.SetEnterpriseAIUserBudgetPolicyRequest, v1.SetEnterpriseAIUserBudgetPolicyResponse]
	deleteEnterpriseAIUserBudgetPolicy *connect.Client[v1.DeleteEnterpriseAIUserBudgetPolicyRequest, v1.DeleteEnterpriseAIUserBudgetPolicyResponse]
	getCumulativeCreditUsage           *connect.Client[v1.GetCumulativeCreditUsageRequest, v1.GetCumulativeCreditUsageResponse]
	listEnterpriseUserCreditUsage      *connect.Client[v1.ListEnterpriseUserCreditUsageRequest, v1.ListEnterpriseUserCreditUsageResponse]
	createTeamCreditAllocation         *connect.Client[v1.CreateTeamCreditAllocationRequest, v1.CreateTeamCreditAllocationResponse]
	getTeamCreditAllocation            *connect.Client[v1.GetTeamCreditAllocationRequest, v1.GetTeamCreditAllocationResponse]
	updateTeamCreditAllocation         *connect.Client[v1.UpdateTeamCreditAllocationRequest, v1.UpdateTeamCreditAllocationResponse]
	deleteTeamCreditAllocation         *connect.Client[v1.DeleteTeamCreditAllocationRequest, v1.DeleteTeamCreditAllocationResponse]
}

// GetCreditUsageReport calls gitpod.v1.BillingService.GetCreditUsageReport.
func (c *billingServiceClient) GetCreditUsageReport(ctx context.Context, req *connect.Request[v1.GetCreditUsageReportRequest]) (*connect.Response[v1.GetCreditUsageReportResponse], error) {
	return c.getCreditUsageReport.CallUnary(ctx, req)
}

// GetCreditUsageExport calls gitpod.v1.BillingService.GetCreditUsageExport.
func (c *billingServiceClient) GetCreditUsageExport(ctx context.Context, req *connect.Request[v1.GetCreditUsageExportRequest]) (*connect.Response[v1.GetCreditUsageExportResponse], error) {
	return c.getCreditUsageExport.CallUnary(ctx, req)
}

// GetEnterpriseAIUsageSummary calls gitpod.v1.BillingService.GetEnterpriseAIUsageSummary.
func (c *billingServiceClient) GetEnterpriseAIUsageSummary(ctx context.Context, req *connect.Request[v1.GetEnterpriseAIUsageSummaryRequest]) (*connect.Response[v1.GetEnterpriseAIUsageSummaryResponse], error) {
	return c.getEnterpriseAIUsageSummary.CallUnary(ctx, req)
}

// ListEnterpriseAITeamUsage calls gitpod.v1.BillingService.ListEnterpriseAITeamUsage.
func (c *billingServiceClient) ListEnterpriseAITeamUsage(ctx context.Context, req *connect.Request[v1.ListEnterpriseAITeamUsageRequest]) (*connect.Response[v1.ListEnterpriseAITeamUsageResponse], error) {
	return c.listEnterpriseAITeamUsage.CallUnary(ctx, req)
}

// ListEnterpriseAIUserUsage calls gitpod.v1.BillingService.ListEnterpriseAIUserUsage.
func (c *billingServiceClient) ListEnterpriseAIUserUsage(ctx context.Context, req *connect.Request[v1.ListEnterpriseAIUserUsageRequest]) (*connect.Response[v1.ListEnterpriseAIUserUsageResponse], error) {
	return c.listEnterpriseAIUserUsage.CallUnary(ctx, req)
}

// GetEnterpriseAIUsageTimeSeries calls gitpod.v1.BillingService.GetEnterpriseAIUsageTimeSeries.
func (c *billingServiceClient) GetEnterpriseAIUsageTimeSeries(ctx context.Context, req *connect.Request[v1.GetEnterpriseAIUsageTimeSeriesRequest]) (*connect.Response[v1.GetEnterpriseAIUsageTimeSeriesResponse], error) {
	return c.getEnterpriseAIUsageTimeSeries.CallUnary(ctx, req)
}

// GetEnterpriseAIUserBudgetPolicy calls gitpod.v1.BillingService.GetEnterpriseAIUserBudgetPolicy.
func (c *billingServiceClient) GetEnterpriseAIUserBudgetPolicy(ctx context.Context, req *connect.Request[v1.GetEnterpriseAIUserBudgetPolicyRequest]) (*connect.Response[v1.GetEnterpriseAIUserBudgetPolicyResponse], error) {
	return c.getEnterpriseAIUserBudgetPolicy.CallUnary(ctx, req)
}

// SetEnterpriseAIUserBudgetPolicy calls gitpod.v1.BillingService.SetEnterpriseAIUserBudgetPolicy.
func (c *billingServiceClient) SetEnterpriseAIUserBudgetPolicy(ctx context.Context, req *connect.Request[v1.SetEnterpriseAIUserBudgetPolicyRequest]) (*connect.Response[v1.SetEnterpriseAIUserBudgetPolicyResponse], error) {
	return c.setEnterpriseAIUserBudgetPolicy.CallUnary(ctx, req)
}

// DeleteEnterpriseAIUserBudgetPolicy calls
// gitpod.v1.BillingService.DeleteEnterpriseAIUserBudgetPolicy.
func (c *billingServiceClient) DeleteEnterpriseAIUserBudgetPolicy(ctx context.Context, req *connect.Request[v1.DeleteEnterpriseAIUserBudgetPolicyRequest]) (*connect.Response[v1.DeleteEnterpriseAIUserBudgetPolicyResponse], error) {
	return c.deleteEnterpriseAIUserBudgetPolicy.CallUnary(ctx, req)
}

// GetCumulativeCreditUsage calls gitpod.v1.BillingService.GetCumulativeCreditUsage.
func (c *billingServiceClient) GetCumulativeCreditUsage(ctx context.Context, req *connect.Request[v1.GetCumulativeCreditUsageRequest]) (*connect.Response[v1.GetCumulativeCreditUsageResponse], error) {
	return c.getCumulativeCreditUsage.CallUnary(ctx, req)
}

// ListEnterpriseUserCreditUsage calls gitpod.v1.BillingService.ListEnterpriseUserCreditUsage.
func (c *billingServiceClient) ListEnterpriseUserCreditUsage(ctx context.Context, req *connect.Request[v1.ListEnterpriseUserCreditUsageRequest]) (*connect.Response[v1.ListEnterpriseUserCreditUsageResponse], error) {
	return c.listEnterpriseUserCreditUsage.CallUnary(ctx, req)
}

// CreateTeamCreditAllocation calls gitpod.v1.BillingService.CreateTeamCreditAllocation.
func (c *billingServiceClient) CreateTeamCreditAllocation(ctx context.Context, req *connect.Request[v1.CreateTeamCreditAllocationRequest]) (*connect.Response[v1.CreateTeamCreditAllocationResponse], error) {
	return c.createTeamCreditAllocation.CallUnary(ctx, req)
}

// GetTeamCreditAllocation calls gitpod.v1.BillingService.GetTeamCreditAllocation.
func (c *billingServiceClient) GetTeamCreditAllocation(ctx context.Context, req *connect.Request[v1.GetTeamCreditAllocationRequest]) (*connect.Response[v1.GetTeamCreditAllocationResponse], error) {
	return c.getTeamCreditAllocation.CallUnary(ctx, req)
}

// UpdateTeamCreditAllocation calls gitpod.v1.BillingService.UpdateTeamCreditAllocation.
func (c *billingServiceClient) UpdateTeamCreditAllocation(ctx context.Context, req *connect.Request[v1.UpdateTeamCreditAllocationRequest]) (*connect.Response[v1.UpdateTeamCreditAllocationResponse], error) {
	return c.updateTeamCreditAllocation.CallUnary(ctx, req)
}

// DeleteTeamCreditAllocation calls gitpod.v1.BillingService.DeleteTeamCreditAllocation.
func (c *billingServiceClient) DeleteTeamCreditAllocation(ctx context.Context, req *connect.Request[v1.DeleteTeamCreditAllocationRequest]) (*connect.Response[v1.DeleteTeamCreditAllocationResponse], error) {
	return c.deleteTeamCreditAllocation.CallUnary(ctx, req)
}

// BillingServiceHandler is an implementation of the gitpod.v1.BillingService service.
type BillingServiceHandler interface {
	// Returns a daily credit usage report for an enterprise organization.
	//
	// Each day reports org-wide credits by usage type, plus per-user, per-team,
	// per-environment, and per-conversation breakdowns (top consumers with the
	// remainder aggregated into an "Others" bucket) and a per-model breakdown
	// of intelligence usage.
	//
	// Use this method to:
	// - Chart daily credit consumption over a date range
	// - Attribute credit usage to users, teams, environments, and conversations
	// - Restrict the report to a single user or service account
	//
	// ### Examples
	//
	// - Get the report for January:
	//
	//	Both dates are inclusive and the range must not exceed 31 days.
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	dateRange:
	//	  startTime: "2024-01-01T00:00:00Z"
	//	  endTime: "2024-01-31T00:00:00Z"
	//	```
	//
	// ### Authorization
	//
	// Requires `billing:read_usage` permission on the organization. A user
	// without it can read their own usage by setting filter.subject to their
	// own user identity; this self-access path is not available to service
	// accounts.
	GetCreditUsageReport(context.Context, *connect.Request[v1.GetCreditUsageReportRequest]) (*connect.Response[v1.GetCreditUsageReportResponse], error)
	// Returns a signed download URL for a CSV export of credit usage.
	//
	// The URL points to an HTTP endpoint that streams gzip-compressed CSV and
	// is valid for five minutes. The download must be made by the same principal
	// that requested it, carrying its own bearer token. The export range may
	// cover up to a year.
	//
	// For organizations without enterprise credit usage enabled (no billing
	// contract start date), the export instead contains BYOK cost usage with a
	// different column set, and groupBy=RESOURCE is rejected.
	//
	// Use this method to:
	// - Export per-user daily credit usage for external reporting
	// - Export a per-environment and per-conversation resource breakdown
	//
	// ### Examples
	//
	// - Export January's daily summary:
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	dateRange:
	//	  startTime: "2024-01-01T00:00:00Z"
	//	  endTime: "2024-01-31T00:00:00Z"
	//	groupBy: CREDIT_USAGE_EXPORT_GROUP_BY_DAILY_SUMMARY
	//	```
	//
	// ### Authorization
	//
	// Requires `billing:read_usage` permission on the organization.
	GetCreditUsageExport(context.Context, *connect.Request[v1.GetCreditUsageExportRequest]) (*connect.Response[v1.GetCreditUsageExportResponse], error)
	// Returns organization-level enterprise AI usage totals for reporting.
	//
	// Reports BYOK (bring-your-own-key) token spend: cost in the
	// organization's billing currency plus token counts, with a per-model
	// breakdown. Credit-based usage from managed models is not included and
	// the credits field is not populated by this endpoint.
	//
	// Use this method to:
	// - Report total BYOK AI spend (cost and tokens) for a date range
	// - Break down organization usage by model
	//
	// Only available for enterprise organizations.
	//
	// ### Examples
	//
	// - Get usage totals for January:
	//
	//	Returns organization-wide BYOK spend for the month. Both dates are
	//	inclusive and the range must not exceed 31 days.
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	dateRange:
	//	  startTime: "2024-01-01T00:00:00Z"
	//	  endTime: "2024-01-31T00:00:00Z"
	//	```
	//
	// ### Authorization
	//
	// Requires `billing:read_usage` permission on the organization.
	GetEnterpriseAIUsageSummary(context.Context, *connect.Request[v1.GetEnterpriseAIUsageSummaryRequest]) (*connect.Response[v1.GetEnterpriseAIUsageSummaryResponse], error)
	// Lists enterprise AI usage grouped by team.
	//
	// Reports BYOK token spend per team (cost and tokens) with each team's
	// monthly budget when one applies. The credits field is not populated by
	// this endpoint.
	//
	// Use this method to:
	// - Compare BYOK AI spend across teams
	// - Track team budget utilization
	// - Filter usage to specific teams
	//
	// Only available for enterprise organizations.
	//
	// ### Examples
	//
	// - List team usage for January:
	//
	//	Returns BYOK spend per team with monthly budgets. Both dates are
	//	inclusive and the range must not exceed 31 days.
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	dateRange:
	//	  startTime: "2024-01-01T00:00:00Z"
	//	  endTime: "2024-01-31T00:00:00Z"
	//	```
	//
	// ### Authorization
	//
	// Requires `billing:read_usage` permission on the organization.
	ListEnterpriseAITeamUsage(context.Context, *connect.Request[v1.ListEnterpriseAITeamUsageRequest]) (*connect.Response[v1.ListEnterpriseAITeamUsageResponse], error)
	// Lists enterprise AI usage grouped by user with effective monthly budget data.
	//
	// Reports BYOK token spend (cost and tokens) for each user and service
	// account with attributed usage in the date range, including each
	// subject's effective monthly budget. Usage not attributed to a user or
	// service account is excluded, so the sum across subjects can be less
	// than the organization totals from GetEnterpriseAIUsageSummary. The
	// credits field is not populated by this endpoint.
	//
	// Budget fields (month_to_date_usage, utilization_percent, over_budget)
	// are computed from usage inside the requested date range measured
	// against the monthly limit. Send a range that starts on the first day
	// of the month for true month-to-date figures.
	//
	// Use this method to:
	// - Export per-user BYOK AI spend to external reporting
	// - Identify the highest spenders in the organization
	// - Track per-user budget utilization and over-budget users
	//
	// Only available for enterprise organizations.
	//
	// ### Examples
	//
	// - List user usage for January:
	//
	//	Returns per-user BYOK spend with effective budgets, highest spend
	//	first. Both dates are inclusive and the range must not exceed 31 days.
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	dateRange:
	//	  startTime: "2024-01-01T00:00:00Z"
	//	  endTime: "2024-01-31T00:00:00Z"
	//	```
	//
	// ### Authorization
	//
	// Requires `billing:read_usage` permission on the organization. Callers
	// without it can read their own usage by setting filter.subject to
	// themselves.
	ListEnterpriseAIUserUsage(context.Context, *connect.Request[v1.ListEnterpriseAIUserUsageRequest]) (*connect.Response[v1.ListEnterpriseAIUserUsageResponse], error)
	// Returns daily enterprise AI usage totals for the organization.
	//
	// Each day reports BYOK token spend (cost and tokens) with per-user,
	// per-team, and per-model breakdowns. Per-user entries cover the top
	// spenders with the remainder aggregated into an "Others" bucket; usage
	// not attributed to a user or service account appears only in the daily
	// totals. The credits field is not populated by this endpoint.
	//
	// When filter.subject is set the response contains only that subject's
	// usage: daily totals and the team breakdown are omitted, and the model
	// breakdown covers the subject only.
	//
	// Use this method to:
	// - Chart daily BYOK AI spend over a date range
	// - Feed daily per-user usage into external dashboards
	// - Restrict the response to a single user or service account
	//
	// Only available for enterprise organizations.
	//
	// ### Examples
	//
	// - Get daily usage for January:
	//
	//	Returns one entry per day with per-user, per-team, and per-model
	//	breakdowns. Both dates are inclusive and the range must not exceed
	//	31 days.
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	dateRange:
	//	  startTime: "2024-01-01T00:00:00Z"
	//	  endTime: "2024-01-31T00:00:00Z"
	//	```
	//
	// ### Authorization
	//
	// Requires `billing:read_usage` permission on the organization.
	GetEnterpriseAIUsageTimeSeries(context.Context, *connect.Request[v1.GetEnterpriseAIUsageTimeSeriesRequest]) (*connect.Response[v1.GetEnterpriseAIUsageTimeSeriesResponse], error)
	// Gets the configured and effective monthly budget policy for a user or org.
	//
	// When user_id is provided, the response includes any direct user override
	// and the effective policy after applying the organization default. When
	// user_id is omitted, both fields describe the organization default.
	//
	// ### Authorization
	//
	// Requires `billing:read_usage` permission on the organization.
	GetEnterpriseAIUserBudgetPolicy(context.Context, *connect.Request[v1.GetEnterpriseAIUserBudgetPolicyRequest]) (*connect.Response[v1.GetEnterpriseAIUserBudgetPolicyResponse], error)
	// Sets the organization default or a per-user monthly budget policy.
	//
	// A user policy overrides the organization default. Set no_cap to exempt a
	// user from the default monthly budget.
	//
	// ### Authorization
	//
	// Requires `billing:update` permission on the organization.
	SetEnterpriseAIUserBudgetPolicy(context.Context, *connect.Request[v1.SetEnterpriseAIUserBudgetPolicyRequest]) (*connect.Response[v1.SetEnterpriseAIUserBudgetPolicyResponse], error)
	// Deletes the organization default or a per-user monthly budget policy.
	//
	// ### Authorization
	//
	// Requires `billing:delete` permission on the organization.
	DeleteEnterpriseAIUserBudgetPolicy(context.Context, *connect.Request[v1.DeleteEnterpriseAIUserBudgetPolicyRequest]) (*connect.Response[v1.DeleteEnterpriseAIUserBudgetPolicyResponse], error)
	// Returns cumulative credit usage for an organization and its teams.
	//
	// Use this method to:
	// - Get the total cumulative credit consumption as of a point in time
	// - Get per-team cumulative usage with credit allocation (budget) comparison
	// - Display team credit summaries on the usage page and team detail page
	// - Display user budget utilization when user budgets are enabled
	//
	// ### Examples
	//
	// - Get current cumulative usage:
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	```
	//
	// - Get cumulative usage as of a specific date:
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	asOf: "2026-03-31T23:59:59Z"
	//	```
	//
	// ### Authorization
	//
	// Requires `billing:read_usage` permission on the organization.
	GetCumulativeCreditUsage(context.Context, *connect.Request[v1.GetCumulativeCreditUsageRequest]) (*connect.Response[v1.GetCumulativeCreditUsageResponse], error)
	// Lists per-user month-to-date credit usage with effective monthly budgets.
	//
	// Results are ordered by total credits descending so the highest spenders
	// appear first, with user_id as a stable tiebreaker. Use cursor pagination
	// to walk the full set for large organizations.
	//
	// The default SORT_FIELD_USAGE ordering supports cursor pagination over any
	// number of users. Sorting by display name, budget, or budget utilization
	// computes the order in memory and is limited to organizations with at most
	// 10,000 users; beyond that, use SORT_FIELD_USAGE. Because month-to-date
	// figures are recomputed per request, hold a date range stable across a
	// paginated walk to keep page tokens valid.
	//
	// Use this method to:
	// - Export per-user credit usage to external reporting
	// - Identify the highest spenders in the organization
	// - Track per-user budget utilization and over-budget users
	//
	// ### Examples
	//
	// - List user usage for the current month:
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	pagination:
	//	  pageSize: 50
	//	```
	//
	// ### Authorization
	//
	// Requires `billing:read_usage` permission on the organization.
	ListEnterpriseUserCreditUsage(context.Context, *connect.Request[v1.ListEnterpriseUserCreditUsageRequest]) (*connect.Response[v1.ListEnterpriseUserCreditUsageResponse], error)
	// Creates a credit allocation (budget) for a team.
	//
	// Allocations are soft budgets for reporting and alerting — not enforced at usage time.
	// Over-allocation (sum of team budgets > org grant) is allowed.
	//
	// ### Examples
	//
	// - Create a team allocation:
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	teamId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	creditBudget: "500"
	//	```
	//
	// ### Authorization
	//
	// Requires `billing:create` permission on the organization.
	CreateTeamCreditAllocation(context.Context, *connect.Request[v1.CreateTeamCreditAllocationRequest]) (*connect.Response[v1.CreateTeamCreditAllocationResponse], error)
	// Gets the credit allocation for a team.
	//
	// ### Examples
	//
	// - Get a team's allocation:
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	teamId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	//
	// ### Authorization
	//
	// Requires `billing:read` permission on the organization.
	GetTeamCreditAllocation(context.Context, *connect.Request[v1.GetTeamCreditAllocationRequest]) (*connect.Response[v1.GetTeamCreditAllocationResponse], error)
	// Updates the credit allocation for a team.
	//
	// ### Examples
	//
	// - Update a team's budget:
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	teamId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	creditBudget: "750"
	//	```
	//
	// ### Authorization
	//
	// Requires `billing:update` permission on the organization.
	UpdateTeamCreditAllocation(context.Context, *connect.Request[v1.UpdateTeamCreditAllocationRequest]) (*connect.Response[v1.UpdateTeamCreditAllocationResponse], error)
	// Deletes the credit allocation for a team.
	//
	// ### Examples
	//
	// - Delete a team's allocation:
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	teamId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	//
	// ### Authorization
	//
	// Requires `billing:delete` permission on the organization.
	DeleteTeamCreditAllocation(context.Context, *connect.Request[v1.DeleteTeamCreditAllocationRequest]) (*connect.Response[v1.DeleteTeamCreditAllocationResponse], error)
}

// NewBillingServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBillingServiceHandler(svc BillingServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	billingServiceMethods := v1.File_gitpod_v1_billing_proto.Services().ByName("BillingService").Methods()
	billingServiceGetCreditUsageReportHandler := connect.NewUnaryHandler(
		BillingServiceGetCreditUsageReportProcedure,
		svc.GetCreditUsageReport,
		connect.WithSchema(billingServiceMethods.ByName("GetCreditUsageReport")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	billingServiceGetCreditUsageExportHandler := connect.NewUnaryHandler(
		BillingServiceGetCreditUsageExportProcedure,
		svc.GetCreditUsageExport,
		connect.WithSchema(billingServiceMethods.ByName("GetCreditUsageExport")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	billingServiceGetEnterpriseAIUsageSummaryHandler := connect.NewUnaryHandler(
		BillingServiceGetEnterpriseAIUsageSummaryProcedure,
		svc.GetEnterpriseAIUsageSummary,
		connect.WithSchema(billingServiceMethods.ByName("GetEnterpriseAIUsageSummary")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	billingServiceListEnterpriseAITeamUsageHandler := connect.NewUnaryHandler(
		BillingServiceListEnterpriseAITeamUsageProcedure,
		svc.ListEnterpriseAITeamUsage,
		connect.WithSchema(billingServiceMethods.ByName("ListEnterpriseAITeamUsage")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	billingServiceListEnterpriseAIUserUsageHandler := connect.NewUnaryHandler(
		BillingServiceListEnterpriseAIUserUsageProcedure,
		svc.ListEnterpriseAIUserUsage,
		connect.WithSchema(billingServiceMethods.ByName("ListEnterpriseAIUserUsage")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	billingServiceGetEnterpriseAIUsageTimeSeriesHandler := connect.NewUnaryHandler(
		BillingServiceGetEnterpriseAIUsageTimeSeriesProcedure,
		svc.GetEnterpriseAIUsageTimeSeries,
		connect.WithSchema(billingServiceMethods.ByName("GetEnterpriseAIUsageTimeSeries")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	billingServiceGetEnterpriseAIUserBudgetPolicyHandler := connect.NewUnaryHandler(
		BillingServiceGetEnterpriseAIUserBudgetPolicyProcedure,
		svc.GetEnterpriseAIUserBudgetPolicy,
		connect.WithSchema(billingServiceMethods.ByName("GetEnterpriseAIUserBudgetPolicy")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	billingServiceSetEnterpriseAIUserBudgetPolicyHandler := connect.NewUnaryHandler(
		BillingServiceSetEnterpriseAIUserBudgetPolicyProcedure,
		svc.SetEnterpriseAIUserBudgetPolicy,
		connect.WithSchema(billingServiceMethods.ByName("SetEnterpriseAIUserBudgetPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	billingServiceDeleteEnterpriseAIUserBudgetPolicyHandler := connect.NewUnaryHandler(
		BillingServiceDeleteEnterpriseAIUserBudgetPolicyProcedure,
		svc.DeleteEnterpriseAIUserBudgetPolicy,
		connect.WithSchema(billingServiceMethods.ByName("DeleteEnterpriseAIUserBudgetPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	billingServiceGetCumulativeCreditUsageHandler := connect.NewUnaryHandler(
		BillingServiceGetCumulativeCreditUsageProcedure,
		svc.GetCumulativeCreditUsage,
		connect.WithSchema(billingServiceMethods.ByName("GetCumulativeCreditUsage")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	billingServiceListEnterpriseUserCreditUsageHandler := connect.NewUnaryHandler(
		BillingServiceListEnterpriseUserCreditUsageProcedure,
		svc.ListEnterpriseUserCreditUsage,
		connect.WithSchema(billingServiceMethods.ByName("ListEnterpriseUserCreditUsage")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	billingServiceCreateTeamCreditAllocationHandler := connect.NewUnaryHandler(
		BillingServiceCreateTeamCreditAllocationProcedure,
		svc.CreateTeamCreditAllocation,
		connect.WithSchema(billingServiceMethods.ByName("CreateTeamCreditAllocation")),
		connect.WithHandlerOptions(opts...),
	)
	billingServiceGetTeamCreditAllocationHandler := connect.NewUnaryHandler(
		BillingServiceGetTeamCreditAllocationProcedure,
		svc.GetTeamCreditAllocation,
		connect.WithSchema(billingServiceMethods.ByName("GetTeamCreditAllocation")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	billingServiceUpdateTeamCreditAllocationHandler := connect.NewUnaryHandler(
		BillingServiceUpdateTeamCreditAllocationProcedure,
		svc.UpdateTeamCreditAllocation,
		connect.WithSchema(billingServiceMethods.ByName("UpdateTeamCreditAllocation")),
		connect.WithHandlerOptions(opts...),
	)
	billingServiceDeleteTeamCreditAllocationHandler := connect.NewUnaryHandler(
		BillingServiceDeleteTeamCreditAllocationProcedure,
		svc.DeleteTeamCreditAllocation,
		connect.WithSchema(billingServiceMethods.ByName("DeleteTeamCreditAllocation")),
		connect.WithHandlerOptions(opts...),
	)
	return "/gitpod.v1.BillingService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BillingServiceGetCreditUsageReportProcedure:
			billingServiceGetCreditUsageReportHandler.ServeHTTP(w, r)
		case BillingServiceGetCreditUsageExportProcedure:
			billingServiceGetCreditUsageExportHandler.ServeHTTP(w, r)
		case BillingServiceGetEnterpriseAIUsageSummaryProcedure:
			billingServiceGetEnterpriseAIUsageSummaryHandler.ServeHTTP(w, r)
		case BillingServiceListEnterpriseAITeamUsageProcedure:
			billingServiceListEnterpriseAITeamUsageHandler.ServeHTTP(w, r)
		case BillingServiceListEnterpriseAIUserUsageProcedure:
			billingServiceListEnterpriseAIUserUsageHandler.ServeHTTP(w, r)
		case BillingServiceGetEnterpriseAIUsageTimeSeriesProcedure:
			billingServiceGetEnterpriseAIUsageTimeSeriesHandler.ServeHTTP(w, r)
		case BillingServiceGetEnterpriseAIUserBudgetPolicyProcedure:
			billingServiceGetEnterpriseAIUserBudgetPolicyHandler.ServeHTTP(w, r)
		case BillingServiceSetEnterpriseAIUserBudgetPolicyProcedure:
			billingServiceSetEnterpriseAIUserBudgetPolicyHandler.ServeHTTP(w, r)
		case BillingServiceDeleteEnterpriseAIUserBudgetPolicyProcedure:
			billingServiceDeleteEnterpriseAIUserBudgetPolicyHandler.ServeHTTP(w, r)
		case BillingServiceGetCumulativeCreditUsageProcedure:
			billingServiceGetCumulativeCreditUsageHandler.ServeHTTP(w, r)
		case BillingServiceListEnterpriseUserCreditUsageProcedure:
			billingServiceListEnterpriseUserCreditUsageHandler.ServeHTTP(w, r)
		case BillingServiceCreateTeamCreditAllocationProcedure:
			billingServiceCreateTeamCreditAllocationHandler.ServeHTTP(w, r)
		case BillingServiceGetTeamCreditAllocationProcedure:
			billingServiceGetTeamCreditAllocationHandler.ServeHTTP(w, r)
		case BillingServiceUpdateTeamCreditAllocationProcedure:
			billingServiceUpdateTeamCreditAllocationHandler.ServeHTTP(w, r)
		case BillingServiceDeleteTeamCreditAllocationProcedure:
			billingServiceDeleteTeamCreditAllocationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBillingServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBillingServiceHandler struct{}

func (UnimplementedBillingServiceHandler) GetCreditUsageReport(context.Context, *connect.Request[v1.GetCreditUsageReportRequest]) (*connect.Response[v1.GetCreditUsageReportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.BillingService.GetCreditUsageReport is not implemented"))
}

func (UnimplementedBillingServiceHandler) GetCreditUsageExport(context.Context, *connect.Request[v1.GetCreditUsageExportRequest]) (*connect.Response[v1.GetCreditUsageExportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.BillingService.GetCreditUsageExport is not implemented"))
}

func (UnimplementedBillingServiceHandler) GetEnterpriseAIUsageSummary(context.Context, *connect.Request[v1.GetEnterpriseAIUsageSummaryRequest]) (*connect.Response[v1.GetEnterpriseAIUsageSummaryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.BillingService.GetEnterpriseAIUsageSummary is not implemented"))
}

func (UnimplementedBillingServiceHandler) ListEnterpriseAITeamUsage(context.Context, *connect.Request[v1.ListEnterpriseAITeamUsageRequest]) (*connect.Response[v1.ListEnterpriseAITeamUsageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.BillingService.ListEnterpriseAITeamUsage is not implemented"))
}

func (UnimplementedBillingServiceHandler) ListEnterpriseAIUserUsage(context.Context, *connect.Request[v1.ListEnterpriseAIUserUsageRequest]) (*connect.Response[v1.ListEnterpriseAIUserUsageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.BillingService.ListEnterpriseAIUserUsage is not implemented"))
}

func (UnimplementedBillingServiceHandler) GetEnterpriseAIUsageTimeSeries(context.Context, *connect.Request[v1.GetEnterpriseAIUsageTimeSeriesRequest]) (*connect.Response[v1.GetEnterpriseAIUsageTimeSeriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.BillingService.GetEnterpriseAIUsageTimeSeries is not implemented"))
}

func (UnimplementedBillingServiceHandler) GetEnterpriseAIUserBudgetPolicy(context.Context, *connect.Request[v1.GetEnterpriseAIUserBudgetPolicyRequest]) (*connect.Response[v1.GetEnterpriseAIUserBudgetPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.BillingService.GetEnterpriseAIUserBudgetPolicy is not implemented"))
}

func (UnimplementedBillingServiceHandler) SetEnterpriseAIUserBudgetPolicy(context.Context, *connect.Request[v1.SetEnterpriseAIUserBudgetPolicyRequest]) (*connect.Response[v1.SetEnterpriseAIUserBudgetPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.BillingService.SetEnterpriseAIUserBudgetPolicy is not implemented"))
}

func (UnimplementedBillingServiceHandler) DeleteEnterpriseAIUserBudgetPolicy(context.Context, *connect.Request[v1.DeleteEnterpriseAIUserBudgetPolicyRequest]) (*connect.Response[v1.DeleteEnterpriseAIUserBudgetPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.BillingService.DeleteEnterpriseAIUserBudgetPolicy is not implemented"))
}

func (UnimplementedBillingServiceHandler) GetCumulativeCreditUsage(context.Context, *connect.Request[v1.GetCumulativeCreditUsageRequest]) (*connect.Response[v1.GetCumulativeCreditUsageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.BillingService.GetCumulativeCreditUsage is not implemented"))
}

func (UnimplementedBillingServiceHandler) ListEnterpriseUserCreditUsage(context.Context, *connect.Request[v1.ListEnterpriseUserCreditUsageRequest]) (*connect.Response[v1.ListEnterpriseUserCreditUsageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.BillingService.ListEnterpriseUserCreditUsage is not implemented"))
}

func (UnimplementedBillingServiceHandler) CreateTeamCreditAllocation(context.Context, *connect.Request[v1.CreateTeamCreditAllocationRequest]) (*connect.Response[v1.CreateTeamCreditAllocationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.BillingService.CreateTeamCreditAllocation is not implemented"))
}

func (UnimplementedBillingServiceHandler) GetTeamCreditAllocation(context.Context, *connect.Request[v1.GetTeamCreditAllocationRequest]) (*connect.Response[v1.GetTeamCreditAllocationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.BillingService.GetTeamCreditAllocation is not implemented"))
}

func (UnimplementedBillingServiceHandler) UpdateTeamCreditAllocation(context.Context, *connect.Request[v1.UpdateTeamCreditAllocationRequest]) (*connect.Response[v1.UpdateTeamCreditAllocationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.BillingService.UpdateTeamCreditAllocation is not implemented"))
}

func (UnimplementedBillingServiceHandler) DeleteTeamCreditAllocation(context.Context, *connect.Request[v1.DeleteTeamCreditAllocationRequest]) (*connect.Response[v1.DeleteTeamCreditAllocationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.BillingService.DeleteTeamCreditAllocation is not implemented"))
}
