// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: gitpod/v1/security.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/gitpod-io/terraform-provider-ona/api/public-clients/go/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SecurityServiceName is the fully-qualified name of the SecurityService service.
	SecurityServiceName = "gitpod.v1.SecurityService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SecurityServiceCreateSecurityPolicyProcedure is the fully-qualified name of the SecurityService's
	// CreateSecurityPolicy RPC.
	SecurityServiceCreateSecurityPolicyProcedure = "/gitpod.v1.SecurityService/CreateSecurityPolicy"
	// SecurityServiceGetSecurityPolicyProcedure is the fully-qualified name of the SecurityService's
	// GetSecurityPolicy RPC.
	SecurityServiceGetSecurityPolicyProcedure = "/gitpod.v1.SecurityService/GetSecurityPolicy"
	// SecurityServiceListSecurityPoliciesProcedure is the fully-qualified name of the SecurityService's
	// ListSecurityPolicies RPC.
	SecurityServiceListSecurityPoliciesProcedure = "/gitpod.v1.SecurityService/ListSecurityPolicies"
	// SecurityServiceUpdateSecurityPolicyProcedure is the fully-qualified name of the SecurityService's
	// UpdateSecurityPolicy RPC.
	SecurityServiceUpdateSecurityPolicyProcedure = "/gitpod.v1.SecurityService/UpdateSecurityPolicy"
	// SecurityServiceDeleteSecurityPolicyProcedure is the fully-qualified name of the SecurityService's
	// DeleteSecurityPolicy RPC.
	SecurityServiceDeleteSecurityPolicyProcedure = "/gitpod.v1.SecurityService/DeleteSecurityPolicy"
)

// SecurityServiceClient is a client for the gitpod.v1.SecurityService service.
type SecurityServiceClient interface {
	// Creates a new security policy.
	//
	// Use this method to:
	// - Define environment access controls
	// - Configure audited or blocked operations
	// - Manage organization security posture
	//
	// ### Examples
	//
	// - Create security policy:
	//
	//	Creates an audit-first Veto Exec policy with one audited bare name and
	//	one blocked absolute path. Creation stores an inactive definition;
	//	assigning it as the organization default validates materializability.
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	metadata:
	//	  name: "Veto Exec audit-first"
	//	spec:
	//	  executables:
	//	    defaultEffect: EFFECT_ALLOW
	//	    rules:
	//	      - path: "npx"
	//	        effect: EFFECT_AUDIT
	//	      - path: "/usr/bin/curl"
	//	        effect: EFFECT_BLOCK
	//	```
	CreateSecurityPolicy(context.Context, *connect.Request[v1.CreateSecurityPolicyRequest]) (*connect.Response[v1.CreateSecurityPolicyResponse], error)
	// Gets details about a specific security policy.
	//
	// Use this method to:
	// - View security policy configuration
	// - Inspect enforcement rules
	//
	// ### Examples
	//
	// - Get security policy:
	//
	//	Retrieves a security policy by ID.
	//
	//	```yaml
	//	securityPolicyId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	GetSecurityPolicy(context.Context, *connect.Request[v1.GetSecurityPolicyRequest]) (*connect.Response[v1.GetSecurityPolicyResponse], error)
	// Lists security policies.
	//
	// Use this method to:
	// - View all security policies in an organization
	// - Audit configured security controls
	//
	// ### Examples
	//
	// - List organization policies:
	//
	//	Shows security policies with pagination.
	//
	//	```yaml
	//	filter:
	//	  organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	pagination:
	//	  pageSize: 20
	//	```
	ListSecurityPolicies(context.Context, *connect.Request[v1.ListSecurityPoliciesRequest]) (*connect.Response[v1.ListSecurityPoliciesResponse], error)
	// Updates a security policy.
	//
	// Use this method to:
	// - Rename a security policy
	// - Change enforcement rules
	// - Update auditing behavior
	//
	// ### Examples
	//
	// - Update security policy:
	//
	//	Promotes one executable rule from audit to block while leaving unmatched
	//	executables allowed. Updating an assigned policy validates
	//	materializability; updating an unassigned policy only stores its spec.
	//
	//	```yaml
	//	securityPolicyId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	spec:
	//	  executables:
	//	    defaultEffect: EFFECT_ALLOW
	//	    rules:
	//	      - path: "npx"
	//	        effect: EFFECT_BLOCK
	//	      - path: "/usr/bin/curl"
	//	        effect: EFFECT_BLOCK
	//	```
	UpdateSecurityPolicy(context.Context, *connect.Request[v1.UpdateSecurityPolicyRequest]) (*connect.Response[v1.UpdateSecurityPolicyResponse], error)
	// Deletes a security policy.
	//
	// Use this method to:
	// - Remove obsolete security policies
	// - Clean up unused policy definitions
	//
	// ### Examples
	//
	// - Delete security policy:
	//
	//	Permanently removes a security policy.
	//
	//	```yaml
	//	securityPolicyId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	DeleteSecurityPolicy(context.Context, *connect.Request[v1.DeleteSecurityPolicyRequest]) (*connect.Response[v1.DeleteSecurityPolicyResponse], error)
}

// NewSecurityServiceClient constructs a client for the gitpod.v1.SecurityService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSecurityServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SecurityServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	securityServiceMethods := v1.File_gitpod_v1_security_proto.Services().ByName("SecurityService").Methods()
	return &securityServiceClient{
		createSecurityPolicy: connect.NewClient[v1.CreateSecurityPolicyRequest, v1.CreateSecurityPolicyResponse](
			httpClient,
			baseURL+SecurityServiceCreateSecurityPolicyProcedure,
			connect.WithSchema(securityServiceMethods.ByName("CreateSecurityPolicy")),
			connect.WithClientOptions(opts...),
		),
		getSecurityPolicy: connect.NewClient[v1.GetSecurityPolicyRequest, v1.GetSecurityPolicyResponse](
			httpClient,
			baseURL+SecurityServiceGetSecurityPolicyProcedure,
			connect.WithSchema(securityServiceMethods.ByName("GetSecurityPolicy")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listSecurityPolicies: connect.NewClient[v1.ListSecurityPoliciesRequest, v1.ListSecurityPoliciesResponse](
			httpClient,
			baseURL+SecurityServiceListSecurityPoliciesProcedure,
			connect.WithSchema(securityServiceMethods.ByName("ListSecurityPolicies")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updateSecurityPolicy: connect.NewClient[v1.UpdateSecurityPolicyRequest, v1.UpdateSecurityPolicyResponse](
			httpClient,
			baseURL+SecurityServiceUpdateSecurityPolicyProcedure,
			connect.WithSchema(securityServiceMethods.ByName("UpdateSecurityPolicy")),
			connect.WithClientOptions(opts...),
		),
		deleteSecurityPolicy: connect.NewClient[v1.DeleteSecurityPolicyRequest, v1.DeleteSecurityPolicyResponse](
			httpClient,
			baseURL+SecurityServiceDeleteSecurityPolicyProcedure,
			connect.WithSchema(securityServiceMethods.ByName("DeleteSecurityPolicy")),
			connect.WithClientOptions(opts...),
		),
	}
}

// securityServiceClient implements SecurityServiceClient.
type securityServiceClient struct {
	createSecurityPolicy *connect.Client[v1.CreateSecurityPolicyRequest, v1.CreateSecurityPolicyResponse]
	getSecurityPolicy    *connect.Client[v1.GetSecurityPolicyRequest, v1.GetSecurityPolicyResponse]
	listSecurityPolicies *connect.Client[v1.ListSecurityPoliciesRequest, v1.ListSecurityPoliciesResponse]
	updateSecurityPolicy *connect.Client[v1.UpdateSecurityPolicyRequest, v1.UpdateSecurityPolicyResponse]
	deleteSecurityPolicy *connect.Client[v1.DeleteSecurityPolicyRequest, v1.DeleteSecurityPolicyResponse]
}

// CreateSecurityPolicy calls gitpod.v1.SecurityService.CreateSecurityPolicy.
func (c *securityServiceClient) CreateSecurityPolicy(ctx context.Context, req *connect.Request[v1.CreateSecurityPolicyRequest]) (*connect.Response[v1.CreateSecurityPolicyResponse], error) {
	return c.createSecurityPolicy.CallUnary(ctx, req)
}

// GetSecurityPolicy calls gitpod.v1.SecurityService.GetSecurityPolicy.
func (c *securityServiceClient) GetSecurityPolicy(ctx context.Context, req *connect.Request[v1.GetSecurityPolicyRequest]) (*connect.Response[v1.GetSecurityPolicyResponse], error) {
	return c.getSecurityPolicy.CallUnary(ctx, req)
}

// ListSecurityPolicies calls gitpod.v1.SecurityService.ListSecurityPolicies.
func (c *securityServiceClient) ListSecurityPolicies(ctx context.Context, req *connect.Request[v1.ListSecurityPoliciesRequest]) (*connect.Response[v1.ListSecurityPoliciesResponse], error) {
	return c.listSecurityPolicies.CallUnary(ctx, req)
}

// UpdateSecurityPolicy calls gitpod.v1.SecurityService.UpdateSecurityPolicy.
func (c *securityServiceClient) UpdateSecurityPolicy(ctx context.Context, req *connect.Request[v1.UpdateSecurityPolicyRequest]) (*connect.Response[v1.UpdateSecurityPolicyResponse], error) {
	return c.updateSecurityPolicy.CallUnary(ctx, req)
}

// DeleteSecurityPolicy calls gitpod.v1.SecurityService.DeleteSecurityPolicy.
func (c *securityServiceClient) DeleteSecurityPolicy(ctx context.Context, req *connect.Request[v1.DeleteSecurityPolicyRequest]) (*connect.Response[v1.DeleteSecurityPolicyResponse], error) {
	return c.deleteSecurityPolicy.CallUnary(ctx, req)
}

// SecurityServiceHandler is an implementation of the gitpod.v1.SecurityService service.
type SecurityServiceHandler interface {
	// Creates a new security policy.
	//
	// Use this method to:
	// - Define environment access controls
	// - Configure audited or blocked operations
	// - Manage organization security posture
	//
	// ### Examples
	//
	// - Create security policy:
	//
	//	Creates an audit-first Veto Exec policy with one audited bare name and
	//	one blocked absolute path. Creation stores an inactive definition;
	//	assigning it as the organization default validates materializability.
	//
	//	```yaml
	//	organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	metadata:
	//	  name: "Veto Exec audit-first"
	//	spec:
	//	  executables:
	//	    defaultEffect: EFFECT_ALLOW
	//	    rules:
	//	      - path: "npx"
	//	        effect: EFFECT_AUDIT
	//	      - path: "/usr/bin/curl"
	//	        effect: EFFECT_BLOCK
	//	```
	CreateSecurityPolicy(context.Context, *connect.Request[v1.CreateSecurityPolicyRequest]) (*connect.Response[v1.CreateSecurityPolicyResponse], error)
	// Gets details about a specific security policy.
	//
	// Use this method to:
	// - View security policy configuration
	// - Inspect enforcement rules
	//
	// ### Examples
	//
	// - Get security policy:
	//
	//	Retrieves a security policy by ID.
	//
	//	```yaml
	//	securityPolicyId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	GetSecurityPolicy(context.Context, *connect.Request[v1.GetSecurityPolicyRequest]) (*connect.Response[v1.GetSecurityPolicyResponse], error)
	// Lists security policies.
	//
	// Use this method to:
	// - View all security policies in an organization
	// - Audit configured security controls
	//
	// ### Examples
	//
	// - List organization policies:
	//
	//	Shows security policies with pagination.
	//
	//	```yaml
	//	filter:
	//	  organizationId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	pagination:
	//	  pageSize: 20
	//	```
	ListSecurityPolicies(context.Context, *connect.Request[v1.ListSecurityPoliciesRequest]) (*connect.Response[v1.ListSecurityPoliciesResponse], error)
	// Updates a security policy.
	//
	// Use this method to:
	// - Rename a security policy
	// - Change enforcement rules
	// - Update auditing behavior
	//
	// ### Examples
	//
	// - Update security policy:
	//
	//	Promotes one executable rule from audit to block while leaving unmatched
	//	executables allowed. Updating an assigned policy validates
	//	materializability; updating an unassigned policy only stores its spec.
	//
	//	```yaml
	//	securityPolicyId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	spec:
	//	  executables:
	//	    defaultEffect: EFFECT_ALLOW
	//	    rules:
	//	      - path: "npx"
	//	        effect: EFFECT_BLOCK
	//	      - path: "/usr/bin/curl"
	//	        effect: EFFECT_BLOCK
	//	```
	UpdateSecurityPolicy(context.Context, *connect.Request[v1.UpdateSecurityPolicyRequest]) (*connect.Response[v1.UpdateSecurityPolicyResponse], error)
	// Deletes a security policy.
	//
	// Use this method to:
	// - Remove obsolete security policies
	// - Clean up unused policy definitions
	//
	// ### Examples
	//
	// - Delete security policy:
	//
	//	Permanently removes a security policy.
	//
	//	```yaml
	//	securityPolicyId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	DeleteSecurityPolicy(context.Context, *connect.Request[v1.DeleteSecurityPolicyRequest]) (*connect.Response[v1.DeleteSecurityPolicyResponse], error)
}

// NewSecurityServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSecurityServiceHandler(svc SecurityServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	securityServiceMethods := v1.File_gitpod_v1_security_proto.Services().ByName("SecurityService").Methods()
	securityServiceCreateSecurityPolicyHandler := connect.NewUnaryHandler(
		SecurityServiceCreateSecurityPolicyProcedure,
		svc.CreateSecurityPolicy,
		connect.WithSchema(securityServiceMethods.ByName("CreateSecurityPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	securityServiceGetSecurityPolicyHandler := connect.NewUnaryHandler(
		SecurityServiceGetSecurityPolicyProcedure,
		svc.GetSecurityPolicy,
		connect.WithSchema(securityServiceMethods.ByName("GetSecurityPolicy")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	securityServiceListSecurityPoliciesHandler := connect.NewUnaryHandler(
		SecurityServiceListSecurityPoliciesProcedure,
		svc.ListSecurityPolicies,
		connect.WithSchema(securityServiceMethods.ByName("ListSecurityPolicies")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	securityServiceUpdateSecurityPolicyHandler := connect.NewUnaryHandler(
		SecurityServiceUpdateSecurityPolicyProcedure,
		svc.UpdateSecurityPolicy,
		connect.WithSchema(securityServiceMethods.ByName("UpdateSecurityPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	securityServiceDeleteSecurityPolicyHandler := connect.NewUnaryHandler(
		SecurityServiceDeleteSecurityPolicyProcedure,
		svc.DeleteSecurityPolicy,
		connect.WithSchema(securityServiceMethods.ByName("DeleteSecurityPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	return "/gitpod.v1.SecurityService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SecurityServiceCreateSecurityPolicyProcedure:
			securityServiceCreateSecurityPolicyHandler.ServeHTTP(w, r)
		case SecurityServiceGetSecurityPolicyProcedure:
			securityServiceGetSecurityPolicyHandler.ServeHTTP(w, r)
		case SecurityServiceListSecurityPoliciesProcedure:
			securityServiceListSecurityPoliciesHandler.ServeHTTP(w, r)
		case SecurityServiceUpdateSecurityPolicyProcedure:
			securityServiceUpdateSecurityPolicyHandler.ServeHTTP(w, r)
		case SecurityServiceDeleteSecurityPolicyProcedure:
			securityServiceDeleteSecurityPolicyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSecurityServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSecurityServiceHandler struct{}

func (UnimplementedSecurityServiceHandler) CreateSecurityPolicy(context.Context, *connect.Request[v1.CreateSecurityPolicyRequest]) (*connect.Response[v1.CreateSecurityPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.SecurityService.CreateSecurityPolicy is not implemented"))
}

func (UnimplementedSecurityServiceHandler) GetSecurityPolicy(context.Context, *connect.Request[v1.GetSecurityPolicyRequest]) (*connect.Response[v1.GetSecurityPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.SecurityService.GetSecurityPolicy is not implemented"))
}

func (UnimplementedSecurityServiceHandler) ListSecurityPolicies(context.Context, *connect.Request[v1.ListSecurityPoliciesRequest]) (*connect.Response[v1.ListSecurityPoliciesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.SecurityService.ListSecurityPolicies is not implemented"))
}

func (UnimplementedSecurityServiceHandler) UpdateSecurityPolicy(context.Context, *connect.Request[v1.UpdateSecurityPolicyRequest]) (*connect.Response[v1.UpdateSecurityPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.SecurityService.UpdateSecurityPolicy is not implemented"))
}

func (UnimplementedSecurityServiceHandler) DeleteSecurityPolicy(context.Context, *connect.Request[v1.DeleteSecurityPolicyRequest]) (*connect.Response[v1.DeleteSecurityPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.SecurityService.DeleteSecurityPolicy is not implemented"))
}
