// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gitpod/v1/agent_security.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/gitpod-io/terraform-provider-ona/api/public-clients/go/tools/logfields"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReportExecEventRequest contains a Veto Exec event reported by an environment.
type ReportExecEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// environment_id is the environment where the event occurred.
	EnvironmentId string `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	// executable is the digest of the binary content (e.g., "sha256:a1b2c3d4...").
	// 256 allows for longer hash algorithms or prefixed identifiers.
	// May be empty when the event source cannot compute the hash.
	Executable string `protobuf:"bytes,2,opt,name=executable,proto3" json:"executable,omitempty"`
	// filename is the kernel-resolved path of the binary.
	// Kernel PATH_MAX = 4096 (include/uapi/linux/limits.h).
	// May be empty if the event source could not resolve it.
	Filename string `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	// action is the enforcement action taken (block or audit).
	Action KernelControlsAction `protobuf:"varint,4,opt,name=action,proto3,enum=gitpod.v1.KernelControlsAction" json:"action,omitempty"`
	// process contains metadata about the process that triggered the event.
	Process *Process `protobuf:"bytes,5,opt,name=process,proto3" json:"process,omitempty"`
	// timestamp is when the event occurred in the environment.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportExecEventRequest) Reset() {
	*x = ReportExecEventRequest{}
	mi := &file_gitpod_v1_agent_security_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportExecEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportExecEventRequest) ProtoMessage() {}

func (x *ReportExecEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitpod_v1_agent_security_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportExecEventRequest.ProtoReflect.Descriptor instead.
func (*ReportExecEventRequest) Descriptor() ([]byte, []int) {
	return file_gitpod_v1_agent_security_proto_rawDescGZIP(), []int{0}
}

func (x *ReportExecEventRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *ReportExecEventRequest) GetExecutable() string {
	if x != nil {
		return x.Executable
	}
	return ""
}

func (x *ReportExecEventRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ReportExecEventRequest) GetAction() KernelControlsAction {
	if x != nil {
		return x.Action
	}
	return KernelControlsAction_KERNEL_CONTROLS_ACTION_UNSPECIFIED
}

func (x *ReportExecEventRequest) GetProcess() *Process {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *ReportExecEventRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ReportExecEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportExecEventResponse) Reset() {
	*x = ReportExecEventResponse{}
	mi := &file_gitpod_v1_agent_security_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportExecEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportExecEventResponse) ProtoMessage() {}

func (x *ReportExecEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitpod_v1_agent_security_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportExecEventResponse.ProtoReflect.Descriptor instead.
func (*ReportExecEventResponse) Descriptor() ([]byte, []int) {
	return file_gitpod_v1_agent_security_proto_rawDescGZIP(), []int{1}
}

// Process describes process metadata for a security event.
//
// PID fields use int32 to match the kernel's pid_t (signed int).
// Linux PID max is 4,194,304 (2^22), well within int32 range.
// Postgres has no unsigned integer type: Ent maps uint32 to bigint
// (8 bytes) while int32 maps to integer (4 bytes). Using int32
// aligns proto, Go, and Postgres types without wasting storage.
type Process struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pid is the userspace process ID (kernel thread group ID, tgid).
	Pid int32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	// tid is the userspace thread ID (kernel pid).
	Tid int32 `protobuf:"varint,2,opt,name=tid,proto3" json:"tid,omitempty"`
	// name is the process name (comm).
	// 2x kernel TASK_COMM_LEN=16
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// started_at is when the process started.
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// ppid is the parent process ID.
	Ppid int32 `protobuf:"varint,6,opt,name=ppid,proto3" json:"ppid,omitempty"`
	// pgid is the process group ID.
	Pgid int32 `protobuf:"varint,7,opt,name=pgid,proto3" json:"pgid,omitempty"`
	// sid is the session ID.
	Sid           int32 `protobuf:"varint,8,opt,name=sid,proto3" json:"sid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Process) Reset() {
	*x = Process{}
	mi := &file_gitpod_v1_agent_security_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_gitpod_v1_agent_security_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_gitpod_v1_agent_security_proto_rawDescGZIP(), []int{2}
}

func (x *Process) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Process) GetTid() int32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *Process) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Process) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Process) GetPpid() int32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *Process) GetPgid() int32 {
	if x != nil {
		return x.Pgid
	}
	return 0
}

func (x *Process) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

var File_gitpod_v1_agent_security_proto protoreflect.FileDescriptor

const file_gitpod_v1_agent_security_proto_rawDesc = "" +
	"\n" +
	"\x1egitpod/v1/agent_security.proto\x12\tgitpod.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgitpod/tools/v1/logfields.proto\x1a\x1bgitpod/v1/environment.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xea\x02\n" +
	"\x16ReportExecEventRequest\x12C\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tB\x1c\xbaH\x05r\x03\xb0\x01\x01\xa2\xab\x1e\x10\n" +
	"\x0eenvironment.idR\renvironmentId\x12(\n" +
	"\n" +
	"executable\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x02R\n" +
	"executable\x12$\n" +
	"\bfilename\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\x80 R\bfilename\x12C\n" +
	"\x06action\x18\x04 \x01(\x0e2\x1f.gitpod.v1.KernelControlsActionB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x06action\x124\n" +
	"\aprocess\x18\x05 \x01(\v2\x12.gitpod.v1.ProcessB\x06\xbaH\x03\xc8\x01\x01R\aprocess\x12@\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\ttimestamp\"\x19\n" +
	"\x17ReportExecEventResponse\"\xbf\x01\n" +
	"\aProcess\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x10\n" +
	"\x03tid\x18\x02 \x01(\x05R\x03tid\x12\x1b\n" +
	"\x04name\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x18 R\x04name\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12\x12\n" +
	"\x04ppid\x18\x06 \x01(\x05R\x04ppid\x12\x12\n" +
	"\x04pgid\x18\a \x01(\x05R\x04pgid\x12\x10\n" +
	"\x03sid\x18\b \x01(\x05R\x03sid2r\n" +
	"\x14AgentSecurityService\x12Z\n" +
	"\x0fReportExecEvent\x12!.gitpod.v1.ReportExecEventRequest\x1a\".gitpod.v1.ReportExecEventResponse\"\x00B,Z*github.com/gitpod-io/gitpod-next/api/go/v1b\x06proto3"

var (
	file_gitpod_v1_agent_security_proto_rawDescOnce sync.Once
	file_gitpod_v1_agent_security_proto_rawDescData []byte
)

func file_gitpod_v1_agent_security_proto_rawDescGZIP() []byte {
	file_gitpod_v1_agent_security_proto_rawDescOnce.Do(func() {
		file_gitpod_v1_agent_security_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gitpod_v1_agent_security_proto_rawDesc), len(file_gitpod_v1_agent_security_proto_rawDesc)))
	})
	return file_gitpod_v1_agent_security_proto_rawDescData
}

var file_gitpod_v1_agent_security_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gitpod_v1_agent_security_proto_goTypes = []any{
	(*ReportExecEventRequest)(nil),  // 0: gitpod.v1.ReportExecEventRequest
	(*ReportExecEventResponse)(nil), // 1: gitpod.v1.ReportExecEventResponse
	(*Process)(nil),                 // 2: gitpod.v1.Process
	(KernelControlsAction)(0),       // 3: gitpod.v1.KernelControlsAction
	(*timestamppb.Timestamp)(nil),   // 4: google.protobuf.Timestamp
}
var file_gitpod_v1_agent_security_proto_depIdxs = []int32{
	3, // 0: gitpod.v1.ReportExecEventRequest.action:type_name -> gitpod.v1.KernelControlsAction
	2, // 1: gitpod.v1.ReportExecEventRequest.process:type_name -> gitpod.v1.Process
	4, // 2: gitpod.v1.ReportExecEventRequest.timestamp:type_name -> google.protobuf.Timestamp
	4, // 3: gitpod.v1.Process.started_at:type_name -> google.protobuf.Timestamp
	0, // 4: gitpod.v1.AgentSecurityService.ReportExecEvent:input_type -> gitpod.v1.ReportExecEventRequest
	1, // 5: gitpod.v1.AgentSecurityService.ReportExecEvent:output_type -> gitpod.v1.ReportExecEventResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_gitpod_v1_agent_security_proto_init() }
func file_gitpod_v1_agent_security_proto_init() {
	if File_gitpod_v1_agent_security_proto != nil {
		return
	}
	file_gitpod_v1_environment_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gitpod_v1_agent_security_proto_rawDesc), len(file_gitpod_v1_agent_security_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gitpod_v1_agent_security_proto_goTypes,
		DependencyIndexes: file_gitpod_v1_agent_security_proto_depIdxs,
		MessageInfos:      file_gitpod_v1_agent_security_proto_msgTypes,
	}.Build()
	File_gitpod_v1_agent_security_proto = out.File
	file_gitpod_v1_agent_security_proto_goTypes = nil
	file_gitpod_v1_agent_security_proto_depIdxs = nil
}
