// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: gitpod/v1/runner_configuration.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RunnerConfigurationService_CreateHostAuthenticationToken_FullMethodName         = "/gitpod.v1.RunnerConfigurationService/CreateHostAuthenticationToken"
	RunnerConfigurationService_GetHostAuthenticationToken_FullMethodName            = "/gitpod.v1.RunnerConfigurationService/GetHostAuthenticationToken"
	RunnerConfigurationService_ListHostAuthenticationTokens_FullMethodName          = "/gitpod.v1.RunnerConfigurationService/ListHostAuthenticationTokens"
	RunnerConfigurationService_UpdateHostAuthenticationToken_FullMethodName         = "/gitpod.v1.RunnerConfigurationService/UpdateHostAuthenticationToken"
	RunnerConfigurationService_UpdateHostAuthenticationTokenMetadata_FullMethodName = "/gitpod.v1.RunnerConfigurationService/UpdateHostAuthenticationTokenMetadata"
	RunnerConfigurationService_DeleteHostAuthenticationToken_FullMethodName         = "/gitpod.v1.RunnerConfigurationService/DeleteHostAuthenticationToken"
	RunnerConfigurationService_GetRunnerConfigurationSchema_FullMethodName          = "/gitpod.v1.RunnerConfigurationService/GetRunnerConfigurationSchema"
	RunnerConfigurationService_CreateSCMIntegration_FullMethodName                  = "/gitpod.v1.RunnerConfigurationService/CreateSCMIntegration"
	RunnerConfigurationService_GetSCMIntegration_FullMethodName                     = "/gitpod.v1.RunnerConfigurationService/GetSCMIntegration"
	RunnerConfigurationService_ListSCMIntegrations_FullMethodName                   = "/gitpod.v1.RunnerConfigurationService/ListSCMIntegrations"
	RunnerConfigurationService_UpdateSCMIntegration_FullMethodName                  = "/gitpod.v1.RunnerConfigurationService/UpdateSCMIntegration"
	RunnerConfigurationService_DeleteSCMIntegration_FullMethodName                  = "/gitpod.v1.RunnerConfigurationService/DeleteSCMIntegration"
	RunnerConfigurationService_CreateEnvironmentClass_FullMethodName                = "/gitpod.v1.RunnerConfigurationService/CreateEnvironmentClass"
	RunnerConfigurationService_GetEnvironmentClass_FullMethodName                   = "/gitpod.v1.RunnerConfigurationService/GetEnvironmentClass"
	RunnerConfigurationService_ListEnvironmentClasses_FullMethodName                = "/gitpod.v1.RunnerConfigurationService/ListEnvironmentClasses"
	RunnerConfigurationService_UpdateEnvironmentClass_FullMethodName                = "/gitpod.v1.RunnerConfigurationService/UpdateEnvironmentClass"
	RunnerConfigurationService_ValidateRunnerConfiguration_FullMethodName           = "/gitpod.v1.RunnerConfigurationService/ValidateRunnerConfiguration"
	RunnerConfigurationService_CreateLLMIntegration_FullMethodName                  = "/gitpod.v1.RunnerConfigurationService/CreateLLMIntegration"
	RunnerConfigurationService_GetLLMIntegration_FullMethodName                     = "/gitpod.v1.RunnerConfigurationService/GetLLMIntegration"
	RunnerConfigurationService_ListLLMIntegrations_FullMethodName                   = "/gitpod.v1.RunnerConfigurationService/ListLLMIntegrations"
	RunnerConfigurationService_UpdateLLMIntegration_FullMethodName                  = "/gitpod.v1.RunnerConfigurationService/UpdateLLMIntegration"
	RunnerConfigurationService_DeleteLLMIntegration_FullMethodName                  = "/gitpod.v1.RunnerConfigurationService/DeleteLLMIntegration"
)

// RunnerConfigurationServiceClient is the client API for RunnerConfigurationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RunnerConfigurationServiceClient interface {
	// Creates a new authentication token for accessing remote hosts.
	//
	// Use this method to:
	// - Set up SCM authentication
	// - Configure OAuth credentials
	// - Manage PAT tokens
	//
	// ### Examples
	//
	// - Create OAuth token:
	//
	//	Creates a new OAuth-based authentication token.
	//
	//	```yaml
	//	runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	userId: "f53d2330-3795-4c5d-a1f3-453121af9c60"
	//	host: "github.com"
	//	token: "gho_xxxxxxxxxxxx"
	//	source: HOST_AUTHENTICATION_TOKEN_SOURCE_OAUTH
	//	expiresAt: "2024-12-31T23:59:59Z"
	//	refreshToken: "ghr_xxxxxxxxxxxx"
	//	```
	CreateHostAuthenticationToken(ctx context.Context, in *CreateHostAuthenticationTokenRequest, opts ...grpc.CallOption) (*CreateHostAuthenticationTokenResponse, error)
	// Gets details about a specific host authentication token.
	//
	// Use this method to:
	// - View token information
	// - Check token expiration
	// - Verify token validity
	//
	// ### Examples
	//
	// - Get token details:
	//
	//	Retrieves information about a specific token.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	GetHostAuthenticationToken(ctx context.Context, in *GetHostAuthenticationTokenRequest, opts ...grpc.CallOption) (*GetHostAuthenticationTokenResponse, error)
	// Lists host authentication tokens with optional filtering.
	//
	// Use this method to:
	// - View all tokens
	// - Filter by runner or user
	// - Monitor token status
	//
	// ### Examples
	//
	// - List all tokens:
	//
	//	Shows all tokens with pagination.
	//
	//	```yaml
	//	pagination:
	//	  pageSize: 20
	//	```
	//
	// - Filter by runner:
	//
	//	Lists tokens for a specific runner.
	//
	//	```yaml
	//	filter:
	//	  runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	pagination:
	//	  pageSize: 20
	//	```
	ListHostAuthenticationTokens(ctx context.Context, in *ListHostAuthenticationTokensRequest, opts ...grpc.CallOption) (*ListHostAuthenticationTokensResponse, error)
	// Updates an existing host authentication token.
	//
	// Use this method to:
	// - Refresh token values
	// - Update expiration
	// - Modify token settings
	//
	// ### Examples
	//
	// - Update token:
	//
	//	Updates token value and expiration.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	token: "gho_xxxxxxxxxxxx"
	//	expiresAt: "2024-12-31T23:59:59Z"
	//	refreshToken: "ghr_xxxxxxxxxxxx"
	//	```
	UpdateHostAuthenticationToken(ctx context.Context, in *UpdateHostAuthenticationTokenRequest, opts ...grpc.CallOption) (*UpdateHostAuthenticationTokenResponse, error)
	// Updates metadata for an existing host authentication token.
	//
	// Use this method to:
	// - Persist provider-derived identity metadata
	// - Attach external user mappings used by webhook handling
	//
	// ### Examples
	//
	// - Update external user ID:
	//
	//	Persists the provider user ID associated with the token.
	//
	//	```yaml
	//	runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	externalUserId: "12345678"
	//	```
	UpdateHostAuthenticationTokenMetadata(ctx context.Context, in *UpdateHostAuthenticationTokenMetadataRequest, opts ...grpc.CallOption) (*UpdateHostAuthenticationTokenMetadataResponse, error)
	// Deletes a host authentication token.
	//
	// Use this method to:
	// - Remove unused tokens
	// - Revoke access
	// - Clean up expired tokens
	//
	// ### Examples
	//
	// - Delete token:
	//
	//	Permanently removes a token.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	DeleteHostAuthenticationToken(ctx context.Context, in *DeleteHostAuthenticationTokenRequest, opts ...grpc.CallOption) (*DeleteHostAuthenticationTokenResponse, error)
	// Gets the latest runner configuration schema.
	//
	// Use this method to:
	// - View available settings
	// - Check configuration options
	// - Validate configurations
	//
	// ### Examples
	//
	// - Get schema:
	//
	//	Retrieves configuration schema for a runner.
	//
	//	```yaml
	//	runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	GetRunnerConfigurationSchema(ctx context.Context, in *GetRunnerConfigurationSchemaRequest, opts ...grpc.CallOption) (*GetRunnerConfigurationSchemaResponse, error)
	// Creates a new SCM integration for a runner.
	//
	// Use this method to:
	// - Configure source control access
	// - Set up repository integrations
	// - Enable code synchronization
	//
	// ### Examples
	//
	// - Create GitHub integration:
	//
	//	Sets up GitHub SCM integration.
	//
	//	```yaml
	//	runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	scmId: "github"
	//	host: "github.com"
	//	oauthClientId: "client_id"
	//	oauthPlaintextClientSecret: "client_secret"
	//	```
	CreateSCMIntegration(ctx context.Context, in *CreateSCMIntegrationRequest, opts ...grpc.CallOption) (*CreateSCMIntegrationResponse, error)
	// Gets details about a specific SCM integration.
	//
	// Use this method to:
	// - View integration settings
	// - Check integration status
	// - Verify configuration
	//
	// ### Examples
	//
	// - Get integration details:
	//
	//	Retrieves information about a specific integration.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	GetSCMIntegration(ctx context.Context, in *GetSCMIntegrationRequest, opts ...grpc.CallOption) (*GetSCMIntegrationResponse, error)
	// Lists SCM integrations for a runner.
	//
	// Use this method to:
	// - View all integrations
	// - Monitor integration status
	// - Check available SCMs
	//
	// ### Examples
	//
	// - List integrations:
	//
	//	Shows all SCM integrations.
	//
	//	```yaml
	//	filter:
	//	  runnerIds: ["d2c94c27-3b76-4a42-b88c-95a85e392c68"]
	//	pagination:
	//	  pageSize: 20
	//	```
	ListSCMIntegrations(ctx context.Context, in *ListSCMIntegrationsRequest, opts ...grpc.CallOption) (*ListSCMIntegrationsResponse, error)
	// Updates an existing SCM integration.
	//
	// Use this method to:
	// - Modify integration settings
	// - Update credentials
	// - Change configuration
	//
	// ### Examples
	//
	// - Update integration:
	//
	//	Updates OAuth credentials.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	oauthClientId: "new_client_id"
	//	oauthPlaintextClientSecret: "new_client_secret"
	//	```
	UpdateSCMIntegration(ctx context.Context, in *UpdateSCMIntegrationRequest, opts ...grpc.CallOption) (*UpdateSCMIntegrationResponse, error)
	// Deletes an SCM integration.
	//
	// Use this method to:
	// - Remove unused integrations
	// - Clean up configurations
	// - Revoke SCM access
	//
	// ### Examples
	//
	// - Delete integration:
	//
	//	Removes an SCM integration.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	DeleteSCMIntegration(ctx context.Context, in *DeleteSCMIntegrationRequest, opts ...grpc.CallOption) (*DeleteSCMIntegrationResponse, error)
	// Creates a new environment class for a runner.
	//
	// Use this method to:
	// - Define compute resources
	// - Configure environment settings
	// - Set up runtime options
	//
	// ### Examples
	//
	// - Create environment class:
	//
	//	Creates a new environment configuration.
	//
	//	```yaml
	//	runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	displayName: "Large Instance"
	//	description: "8 CPU, 16GB RAM"
	//	configuration:
	//	  - key: "cpu"
	//	    value: "8"
	//	  - key: "memory"
	//	    value: "16384"
	//	```
	CreateEnvironmentClass(ctx context.Context, in *CreateEnvironmentClassRequest, opts ...grpc.CallOption) (*CreateEnvironmentClassResponse, error)
	// Gets details about a specific environment class.
	//
	// Use this method to:
	// - View class configuration
	// - Check resource settings
	// - Verify availability
	//
	// ### Examples
	//
	// - Get class details:
	//
	//	Retrieves information about a specific class.
	//
	//	```yaml
	//	environmentClassId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	GetEnvironmentClass(ctx context.Context, in *GetEnvironmentClassRequest, opts ...grpc.CallOption) (*GetEnvironmentClassResponse, error)
	// Lists environment classes with optional filtering.
	//
	// Use this method to:
	// - View available classes
	// - Filter by capability
	// - Check enabled status
	//
	// ### Examples
	//
	// - List all classes:
	//
	//	Shows all environment classes.
	//
	//	```yaml
	//	pagination:
	//	  pageSize: 20
	//	```
	//
	// - Filter enabled classes:
	//
	//	Lists only enabled environment classes.
	//
	//	```yaml
	//	filter:
	//	  enabled: true
	//	pagination:
	//	  pageSize: 20
	//	```
	//
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	ListEnvironmentClasses(ctx context.Context, in *ListEnvironmentClassesRequest, opts ...grpc.CallOption) (*ListEnvironmentClassesResponse, error)
	// Updates an environment class.
	//
	// Use this method to:
	// - Modify class settings
	// - Update resource limits
	// - Change availability
	//
	// ### Examples
	//
	// - Update class:
	//
	//	Changes class configuration.
	//
	//	```yaml
	//	environmentClassId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	displayName: "Updated Large Instance"
	//	description: "16 CPU, 32GB RAM"
	//	enabled: true
	//	```
	UpdateEnvironmentClass(ctx context.Context, in *UpdateEnvironmentClassRequest, opts ...grpc.CallOption) (*UpdateEnvironmentClassResponse, error)
	// Validates a runner configuration.
	//
	// Use this method to:
	// - Check configuration validity
	// - Verify integration settings
	// - Validate environment classes
	//
	// ### Examples
	//
	// - Validate SCM integration:
	//
	//	Checks if an SCM integration is valid.
	//
	//	```yaml
	//	runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	scmIntegration:
	//	  id: "integration-id"
	//	  scmId: "github"
	//	  host: "github.com"
	//	  oauthClientId: "client_id"
	//	  oauthPlaintextClientSecret: "client_secret"
	//	```
	ValidateRunnerConfiguration(ctx context.Context, in *ValidateRunnerConfigurationRequest, opts ...grpc.CallOption) (*ValidateRunnerConfigurationResponse, error)
	// Creates a new LLM integration for a runner.
	//
	// Use this method to:
	// - Configure LLM access
	// - Set up LLM integrations
	// - Enable LLM usage
	CreateLLMIntegration(ctx context.Context, in *CreateLLMIntegrationRequest, opts ...grpc.CallOption) (*CreateLLMIntegrationResponse, error)
	// Gets details about a specific LLM integration.
	//
	// Use this method to:
	// - View integration settings
	// - Check integration status
	// - Verify configuration
	//
	// ### Examples
	//
	// - Get integration details:
	//
	//	Retrieves information about a specific integration.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	GetLLMIntegration(ctx context.Context, in *GetLLMIntegrationRequest, opts ...grpc.CallOption) (*GetLLMIntegrationResponse, error)
	// Lists LLM integrations for a runner.
	//
	// Use this method to:
	// - View all integrations
	// - Monitor integration status
	// - Check available LLMs
	//
	// ### Examples
	//
	// - List integrations:
	//
	//	Shows all LLM integrations.
	//
	//	```yaml
	//	filter:
	//	  runnerIds: ["d2c94c27-3b76-4a42-b88c-95a85e392c68"]
	//	pagination:
	//	  pageSize: 20
	//	```
	ListLLMIntegrations(ctx context.Context, in *ListLLMIntegrationsRequest, opts ...grpc.CallOption) (*ListLLMIntegrationsResponse, error)
	// Updates an existing LLM integration.
	//
	// Use this method to:
	// - Modify integration settings
	// - Update credentials
	// - Change configuration
	//
	// ### Examples
	//
	// - Update integration:
	//
	//	Updates OAuth credentials.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	apiKey: "sk-..."
	//	```
	UpdateLLMIntegration(ctx context.Context, in *UpdateLLMIntegrationRequest, opts ...grpc.CallOption) (*UpdateLLMIntegrationResponse, error)
	// Deletes an LLM integration.
	//
	// Use this method to:
	// - Remove unused integrations
	// - Clean up configurations
	// - Revoke LLM access
	//
	// ### Examples
	//
	// - Delete integration:
	//
	//	Removes an LLM integration.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	DeleteLLMIntegration(ctx context.Context, in *DeleteLLMIntegrationRequest, opts ...grpc.CallOption) (*DeleteLLMIntegrationResponse, error)
}

type runnerConfigurationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRunnerConfigurationServiceClient(cc grpc.ClientConnInterface) RunnerConfigurationServiceClient {
	return &runnerConfigurationServiceClient{cc}
}

func (c *runnerConfigurationServiceClient) CreateHostAuthenticationToken(ctx context.Context, in *CreateHostAuthenticationTokenRequest, opts ...grpc.CallOption) (*CreateHostAuthenticationTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateHostAuthenticationTokenResponse)
	err := c.cc.Invoke(ctx, RunnerConfigurationService_CreateHostAuthenticationToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerConfigurationServiceClient) GetHostAuthenticationToken(ctx context.Context, in *GetHostAuthenticationTokenRequest, opts ...grpc.CallOption) (*GetHostAuthenticationTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHostAuthenticationTokenResponse)
	err := c.cc.Invoke(ctx, RunnerConfigurationService_GetHostAuthenticationToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerConfigurationServiceClient) ListHostAuthenticationTokens(ctx context.Context, in *ListHostAuthenticationTokensRequest, opts ...grpc.CallOption) (*ListHostAuthenticationTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHostAuthenticationTokensResponse)
	err := c.cc.Invoke(ctx, RunnerConfigurationService_ListHostAuthenticationTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerConfigurationServiceClient) UpdateHostAuthenticationToken(ctx context.Context, in *UpdateHostAuthenticationTokenRequest, opts ...grpc.CallOption) (*UpdateHostAuthenticationTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateHostAuthenticationTokenResponse)
	err := c.cc.Invoke(ctx, RunnerConfigurationService_UpdateHostAuthenticationToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerConfigurationServiceClient) UpdateHostAuthenticationTokenMetadata(ctx context.Context, in *UpdateHostAuthenticationTokenMetadataRequest, opts ...grpc.CallOption) (*UpdateHostAuthenticationTokenMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateHostAuthenticationTokenMetadataResponse)
	err := c.cc.Invoke(ctx, RunnerConfigurationService_UpdateHostAuthenticationTokenMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerConfigurationServiceClient) DeleteHostAuthenticationToken(ctx context.Context, in *DeleteHostAuthenticationTokenRequest, opts ...grpc.CallOption) (*DeleteHostAuthenticationTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteHostAuthenticationTokenResponse)
	err := c.cc.Invoke(ctx, RunnerConfigurationService_DeleteHostAuthenticationToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerConfigurationServiceClient) GetRunnerConfigurationSchema(ctx context.Context, in *GetRunnerConfigurationSchemaRequest, opts ...grpc.CallOption) (*GetRunnerConfigurationSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRunnerConfigurationSchemaResponse)
	err := c.cc.Invoke(ctx, RunnerConfigurationService_GetRunnerConfigurationSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerConfigurationServiceClient) CreateSCMIntegration(ctx context.Context, in *CreateSCMIntegrationRequest, opts ...grpc.CallOption) (*CreateSCMIntegrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSCMIntegrationResponse)
	err := c.cc.Invoke(ctx, RunnerConfigurationService_CreateSCMIntegration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerConfigurationServiceClient) GetSCMIntegration(ctx context.Context, in *GetSCMIntegrationRequest, opts ...grpc.CallOption) (*GetSCMIntegrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSCMIntegrationResponse)
	err := c.cc.Invoke(ctx, RunnerConfigurationService_GetSCMIntegration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerConfigurationServiceClient) ListSCMIntegrations(ctx context.Context, in *ListSCMIntegrationsRequest, opts ...grpc.CallOption) (*ListSCMIntegrationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSCMIntegrationsResponse)
	err := c.cc.Invoke(ctx, RunnerConfigurationService_ListSCMIntegrations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerConfigurationServiceClient) UpdateSCMIntegration(ctx context.Context, in *UpdateSCMIntegrationRequest, opts ...grpc.CallOption) (*UpdateSCMIntegrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSCMIntegrationResponse)
	err := c.cc.Invoke(ctx, RunnerConfigurationService_UpdateSCMIntegration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerConfigurationServiceClient) DeleteSCMIntegration(ctx context.Context, in *DeleteSCMIntegrationRequest, opts ...grpc.CallOption) (*DeleteSCMIntegrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSCMIntegrationResponse)
	err := c.cc.Invoke(ctx, RunnerConfigurationService_DeleteSCMIntegration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerConfigurationServiceClient) CreateEnvironmentClass(ctx context.Context, in *CreateEnvironmentClassRequest, opts ...grpc.CallOption) (*CreateEnvironmentClassResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEnvironmentClassResponse)
	err := c.cc.Invoke(ctx, RunnerConfigurationService_CreateEnvironmentClass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerConfigurationServiceClient) GetEnvironmentClass(ctx context.Context, in *GetEnvironmentClassRequest, opts ...grpc.CallOption) (*GetEnvironmentClassResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEnvironmentClassResponse)
	err := c.cc.Invoke(ctx, RunnerConfigurationService_GetEnvironmentClass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerConfigurationServiceClient) ListEnvironmentClasses(ctx context.Context, in *ListEnvironmentClassesRequest, opts ...grpc.CallOption) (*ListEnvironmentClassesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEnvironmentClassesResponse)
	err := c.cc.Invoke(ctx, RunnerConfigurationService_ListEnvironmentClasses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerConfigurationServiceClient) UpdateEnvironmentClass(ctx context.Context, in *UpdateEnvironmentClassRequest, opts ...grpc.CallOption) (*UpdateEnvironmentClassResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEnvironmentClassResponse)
	err := c.cc.Invoke(ctx, RunnerConfigurationService_UpdateEnvironmentClass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerConfigurationServiceClient) ValidateRunnerConfiguration(ctx context.Context, in *ValidateRunnerConfigurationRequest, opts ...grpc.CallOption) (*ValidateRunnerConfigurationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateRunnerConfigurationResponse)
	err := c.cc.Invoke(ctx, RunnerConfigurationService_ValidateRunnerConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerConfigurationServiceClient) CreateLLMIntegration(ctx context.Context, in *CreateLLMIntegrationRequest, opts ...grpc.CallOption) (*CreateLLMIntegrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLLMIntegrationResponse)
	err := c.cc.Invoke(ctx, RunnerConfigurationService_CreateLLMIntegration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerConfigurationServiceClient) GetLLMIntegration(ctx context.Context, in *GetLLMIntegrationRequest, opts ...grpc.CallOption) (*GetLLMIntegrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLLMIntegrationResponse)
	err := c.cc.Invoke(ctx, RunnerConfigurationService_GetLLMIntegration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerConfigurationServiceClient) ListLLMIntegrations(ctx context.Context, in *ListLLMIntegrationsRequest, opts ...grpc.CallOption) (*ListLLMIntegrationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLLMIntegrationsResponse)
	err := c.cc.Invoke(ctx, RunnerConfigurationService_ListLLMIntegrations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerConfigurationServiceClient) UpdateLLMIntegration(ctx context.Context, in *UpdateLLMIntegrationRequest, opts ...grpc.CallOption) (*UpdateLLMIntegrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateLLMIntegrationResponse)
	err := c.cc.Invoke(ctx, RunnerConfigurationService_UpdateLLMIntegration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerConfigurationServiceClient) DeleteLLMIntegration(ctx context.Context, in *DeleteLLMIntegrationRequest, opts ...grpc.CallOption) (*DeleteLLMIntegrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLLMIntegrationResponse)
	err := c.cc.Invoke(ctx, RunnerConfigurationService_DeleteLLMIntegration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunnerConfigurationServiceServer is the server API for RunnerConfigurationService service.
// All implementations must embed UnimplementedRunnerConfigurationServiceServer
// for forward compatibility.
type RunnerConfigurationServiceServer interface {
	// Creates a new authentication token for accessing remote hosts.
	//
	// Use this method to:
	// - Set up SCM authentication
	// - Configure OAuth credentials
	// - Manage PAT tokens
	//
	// ### Examples
	//
	// - Create OAuth token:
	//
	//	Creates a new OAuth-based authentication token.
	//
	//	```yaml
	//	runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	userId: "f53d2330-3795-4c5d-a1f3-453121af9c60"
	//	host: "github.com"
	//	token: "gho_xxxxxxxxxxxx"
	//	source: HOST_AUTHENTICATION_TOKEN_SOURCE_OAUTH
	//	expiresAt: "2024-12-31T23:59:59Z"
	//	refreshToken: "ghr_xxxxxxxxxxxx"
	//	```
	CreateHostAuthenticationToken(context.Context, *CreateHostAuthenticationTokenRequest) (*CreateHostAuthenticationTokenResponse, error)
	// Gets details about a specific host authentication token.
	//
	// Use this method to:
	// - View token information
	// - Check token expiration
	// - Verify token validity
	//
	// ### Examples
	//
	// - Get token details:
	//
	//	Retrieves information about a specific token.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	GetHostAuthenticationToken(context.Context, *GetHostAuthenticationTokenRequest) (*GetHostAuthenticationTokenResponse, error)
	// Lists host authentication tokens with optional filtering.
	//
	// Use this method to:
	// - View all tokens
	// - Filter by runner or user
	// - Monitor token status
	//
	// ### Examples
	//
	// - List all tokens:
	//
	//	Shows all tokens with pagination.
	//
	//	```yaml
	//	pagination:
	//	  pageSize: 20
	//	```
	//
	// - Filter by runner:
	//
	//	Lists tokens for a specific runner.
	//
	//	```yaml
	//	filter:
	//	  runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	pagination:
	//	  pageSize: 20
	//	```
	ListHostAuthenticationTokens(context.Context, *ListHostAuthenticationTokensRequest) (*ListHostAuthenticationTokensResponse, error)
	// Updates an existing host authentication token.
	//
	// Use this method to:
	// - Refresh token values
	// - Update expiration
	// - Modify token settings
	//
	// ### Examples
	//
	// - Update token:
	//
	//	Updates token value and expiration.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	token: "gho_xxxxxxxxxxxx"
	//	expiresAt: "2024-12-31T23:59:59Z"
	//	refreshToken: "ghr_xxxxxxxxxxxx"
	//	```
	UpdateHostAuthenticationToken(context.Context, *UpdateHostAuthenticationTokenRequest) (*UpdateHostAuthenticationTokenResponse, error)
	// Updates metadata for an existing host authentication token.
	//
	// Use this method to:
	// - Persist provider-derived identity metadata
	// - Attach external user mappings used by webhook handling
	//
	// ### Examples
	//
	// - Update external user ID:
	//
	//	Persists the provider user ID associated with the token.
	//
	//	```yaml
	//	runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	externalUserId: "12345678"
	//	```
	UpdateHostAuthenticationTokenMetadata(context.Context, *UpdateHostAuthenticationTokenMetadataRequest) (*UpdateHostAuthenticationTokenMetadataResponse, error)
	// Deletes a host authentication token.
	//
	// Use this method to:
	// - Remove unused tokens
	// - Revoke access
	// - Clean up expired tokens
	//
	// ### Examples
	//
	// - Delete token:
	//
	//	Permanently removes a token.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	DeleteHostAuthenticationToken(context.Context, *DeleteHostAuthenticationTokenRequest) (*DeleteHostAuthenticationTokenResponse, error)
	// Gets the latest runner configuration schema.
	//
	// Use this method to:
	// - View available settings
	// - Check configuration options
	// - Validate configurations
	//
	// ### Examples
	//
	// - Get schema:
	//
	//	Retrieves configuration schema for a runner.
	//
	//	```yaml
	//	runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	GetRunnerConfigurationSchema(context.Context, *GetRunnerConfigurationSchemaRequest) (*GetRunnerConfigurationSchemaResponse, error)
	// Creates a new SCM integration for a runner.
	//
	// Use this method to:
	// - Configure source control access
	// - Set up repository integrations
	// - Enable code synchronization
	//
	// ### Examples
	//
	// - Create GitHub integration:
	//
	//	Sets up GitHub SCM integration.
	//
	//	```yaml
	//	runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	scmId: "github"
	//	host: "github.com"
	//	oauthClientId: "client_id"
	//	oauthPlaintextClientSecret: "client_secret"
	//	```
	CreateSCMIntegration(context.Context, *CreateSCMIntegrationRequest) (*CreateSCMIntegrationResponse, error)
	// Gets details about a specific SCM integration.
	//
	// Use this method to:
	// - View integration settings
	// - Check integration status
	// - Verify configuration
	//
	// ### Examples
	//
	// - Get integration details:
	//
	//	Retrieves information about a specific integration.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	GetSCMIntegration(context.Context, *GetSCMIntegrationRequest) (*GetSCMIntegrationResponse, error)
	// Lists SCM integrations for a runner.
	//
	// Use this method to:
	// - View all integrations
	// - Monitor integration status
	// - Check available SCMs
	//
	// ### Examples
	//
	// - List integrations:
	//
	//	Shows all SCM integrations.
	//
	//	```yaml
	//	filter:
	//	  runnerIds: ["d2c94c27-3b76-4a42-b88c-95a85e392c68"]
	//	pagination:
	//	  pageSize: 20
	//	```
	ListSCMIntegrations(context.Context, *ListSCMIntegrationsRequest) (*ListSCMIntegrationsResponse, error)
	// Updates an existing SCM integration.
	//
	// Use this method to:
	// - Modify integration settings
	// - Update credentials
	// - Change configuration
	//
	// ### Examples
	//
	// - Update integration:
	//
	//	Updates OAuth credentials.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	oauthClientId: "new_client_id"
	//	oauthPlaintextClientSecret: "new_client_secret"
	//	```
	UpdateSCMIntegration(context.Context, *UpdateSCMIntegrationRequest) (*UpdateSCMIntegrationResponse, error)
	// Deletes an SCM integration.
	//
	// Use this method to:
	// - Remove unused integrations
	// - Clean up configurations
	// - Revoke SCM access
	//
	// ### Examples
	//
	// - Delete integration:
	//
	//	Removes an SCM integration.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	DeleteSCMIntegration(context.Context, *DeleteSCMIntegrationRequest) (*DeleteSCMIntegrationResponse, error)
	// Creates a new environment class for a runner.
	//
	// Use this method to:
	// - Define compute resources
	// - Configure environment settings
	// - Set up runtime options
	//
	// ### Examples
	//
	// - Create environment class:
	//
	//	Creates a new environment configuration.
	//
	//	```yaml
	//	runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	displayName: "Large Instance"
	//	description: "8 CPU, 16GB RAM"
	//	configuration:
	//	  - key: "cpu"
	//	    value: "8"
	//	  - key: "memory"
	//	    value: "16384"
	//	```
	CreateEnvironmentClass(context.Context, *CreateEnvironmentClassRequest) (*CreateEnvironmentClassResponse, error)
	// Gets details about a specific environment class.
	//
	// Use this method to:
	// - View class configuration
	// - Check resource settings
	// - Verify availability
	//
	// ### Examples
	//
	// - Get class details:
	//
	//	Retrieves information about a specific class.
	//
	//	```yaml
	//	environmentClassId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	GetEnvironmentClass(context.Context, *GetEnvironmentClassRequest) (*GetEnvironmentClassResponse, error)
	// Lists environment classes with optional filtering.
	//
	// Use this method to:
	// - View available classes
	// - Filter by capability
	// - Check enabled status
	//
	// ### Examples
	//
	// - List all classes:
	//
	//	Shows all environment classes.
	//
	//	```yaml
	//	pagination:
	//	  pageSize: 20
	//	```
	//
	// - Filter enabled classes:
	//
	//	Lists only enabled environment classes.
	//
	//	```yaml
	//	filter:
	//	  enabled: true
	//	pagination:
	//	  pageSize: 20
	//	```
	//
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	ListEnvironmentClasses(context.Context, *ListEnvironmentClassesRequest) (*ListEnvironmentClassesResponse, error)
	// Updates an environment class.
	//
	// Use this method to:
	// - Modify class settings
	// - Update resource limits
	// - Change availability
	//
	// ### Examples
	//
	// - Update class:
	//
	//	Changes class configuration.
	//
	//	```yaml
	//	environmentClassId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	displayName: "Updated Large Instance"
	//	description: "16 CPU, 32GB RAM"
	//	enabled: true
	//	```
	UpdateEnvironmentClass(context.Context, *UpdateEnvironmentClassRequest) (*UpdateEnvironmentClassResponse, error)
	// Validates a runner configuration.
	//
	// Use this method to:
	// - Check configuration validity
	// - Verify integration settings
	// - Validate environment classes
	//
	// ### Examples
	//
	// - Validate SCM integration:
	//
	//	Checks if an SCM integration is valid.
	//
	//	```yaml
	//	runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	scmIntegration:
	//	  id: "integration-id"
	//	  scmId: "github"
	//	  host: "github.com"
	//	  oauthClientId: "client_id"
	//	  oauthPlaintextClientSecret: "client_secret"
	//	```
	ValidateRunnerConfiguration(context.Context, *ValidateRunnerConfigurationRequest) (*ValidateRunnerConfigurationResponse, error)
	// Creates a new LLM integration for a runner.
	//
	// Use this method to:
	// - Configure LLM access
	// - Set up LLM integrations
	// - Enable LLM usage
	CreateLLMIntegration(context.Context, *CreateLLMIntegrationRequest) (*CreateLLMIntegrationResponse, error)
	// Gets details about a specific LLM integration.
	//
	// Use this method to:
	// - View integration settings
	// - Check integration status
	// - Verify configuration
	//
	// ### Examples
	//
	// - Get integration details:
	//
	//	Retrieves information about a specific integration.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	GetLLMIntegration(context.Context, *GetLLMIntegrationRequest) (*GetLLMIntegrationResponse, error)
	// Lists LLM integrations for a runner.
	//
	// Use this method to:
	// - View all integrations
	// - Monitor integration status
	// - Check available LLMs
	//
	// ### Examples
	//
	// - List integrations:
	//
	//	Shows all LLM integrations.
	//
	//	```yaml
	//	filter:
	//	  runnerIds: ["d2c94c27-3b76-4a42-b88c-95a85e392c68"]
	//	pagination:
	//	  pageSize: 20
	//	```
	ListLLMIntegrations(context.Context, *ListLLMIntegrationsRequest) (*ListLLMIntegrationsResponse, error)
	// Updates an existing LLM integration.
	//
	// Use this method to:
	// - Modify integration settings
	// - Update credentials
	// - Change configuration
	//
	// ### Examples
	//
	// - Update integration:
	//
	//	Updates OAuth credentials.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	apiKey: "sk-..."
	//	```
	UpdateLLMIntegration(context.Context, *UpdateLLMIntegrationRequest) (*UpdateLLMIntegrationResponse, error)
	// Deletes an LLM integration.
	//
	// Use this method to:
	// - Remove unused integrations
	// - Clean up configurations
	// - Revoke LLM access
	//
	// ### Examples
	//
	// - Delete integration:
	//
	//	Removes an LLM integration.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	DeleteLLMIntegration(context.Context, *DeleteLLMIntegrationRequest) (*DeleteLLMIntegrationResponse, error)
	mustEmbedUnimplementedRunnerConfigurationServiceServer()
}

// UnimplementedRunnerConfigurationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunnerConfigurationServiceServer struct{}

func (UnimplementedRunnerConfigurationServiceServer) CreateHostAuthenticationToken(context.Context, *CreateHostAuthenticationTokenRequest) (*CreateHostAuthenticationTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHostAuthenticationToken not implemented")
}
func (UnimplementedRunnerConfigurationServiceServer) GetHostAuthenticationToken(context.Context, *GetHostAuthenticationTokenRequest) (*GetHostAuthenticationTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHostAuthenticationToken not implemented")
}
func (UnimplementedRunnerConfigurationServiceServer) ListHostAuthenticationTokens(context.Context, *ListHostAuthenticationTokensRequest) (*ListHostAuthenticationTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHostAuthenticationTokens not implemented")
}
func (UnimplementedRunnerConfigurationServiceServer) UpdateHostAuthenticationToken(context.Context, *UpdateHostAuthenticationTokenRequest) (*UpdateHostAuthenticationTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHostAuthenticationToken not implemented")
}
func (UnimplementedRunnerConfigurationServiceServer) UpdateHostAuthenticationTokenMetadata(context.Context, *UpdateHostAuthenticationTokenMetadataRequest) (*UpdateHostAuthenticationTokenMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHostAuthenticationTokenMetadata not implemented")
}
func (UnimplementedRunnerConfigurationServiceServer) DeleteHostAuthenticationToken(context.Context, *DeleteHostAuthenticationTokenRequest) (*DeleteHostAuthenticationTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHostAuthenticationToken not implemented")
}
func (UnimplementedRunnerConfigurationServiceServer) GetRunnerConfigurationSchema(context.Context, *GetRunnerConfigurationSchemaRequest) (*GetRunnerConfigurationSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRunnerConfigurationSchema not implemented")
}
func (UnimplementedRunnerConfigurationServiceServer) CreateSCMIntegration(context.Context, *CreateSCMIntegrationRequest) (*CreateSCMIntegrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSCMIntegration not implemented")
}
func (UnimplementedRunnerConfigurationServiceServer) GetSCMIntegration(context.Context, *GetSCMIntegrationRequest) (*GetSCMIntegrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSCMIntegration not implemented")
}
func (UnimplementedRunnerConfigurationServiceServer) ListSCMIntegrations(context.Context, *ListSCMIntegrationsRequest) (*ListSCMIntegrationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSCMIntegrations not implemented")
}
func (UnimplementedRunnerConfigurationServiceServer) UpdateSCMIntegration(context.Context, *UpdateSCMIntegrationRequest) (*UpdateSCMIntegrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSCMIntegration not implemented")
}
func (UnimplementedRunnerConfigurationServiceServer) DeleteSCMIntegration(context.Context, *DeleteSCMIntegrationRequest) (*DeleteSCMIntegrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSCMIntegration not implemented")
}
func (UnimplementedRunnerConfigurationServiceServer) CreateEnvironmentClass(context.Context, *CreateEnvironmentClassRequest) (*CreateEnvironmentClassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEnvironmentClass not implemented")
}
func (UnimplementedRunnerConfigurationServiceServer) GetEnvironmentClass(context.Context, *GetEnvironmentClassRequest) (*GetEnvironmentClassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnvironmentClass not implemented")
}
func (UnimplementedRunnerConfigurationServiceServer) ListEnvironmentClasses(context.Context, *ListEnvironmentClassesRequest) (*ListEnvironmentClassesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEnvironmentClasses not implemented")
}
func (UnimplementedRunnerConfigurationServiceServer) UpdateEnvironmentClass(context.Context, *UpdateEnvironmentClassRequest) (*UpdateEnvironmentClassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEnvironmentClass not implemented")
}
func (UnimplementedRunnerConfigurationServiceServer) ValidateRunnerConfiguration(context.Context, *ValidateRunnerConfigurationRequest) (*ValidateRunnerConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateRunnerConfiguration not implemented")
}
func (UnimplementedRunnerConfigurationServiceServer) CreateLLMIntegration(context.Context, *CreateLLMIntegrationRequest) (*CreateLLMIntegrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLLMIntegration not implemented")
}
func (UnimplementedRunnerConfigurationServiceServer) GetLLMIntegration(context.Context, *GetLLMIntegrationRequest) (*GetLLMIntegrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLLMIntegration not implemented")
}
func (UnimplementedRunnerConfigurationServiceServer) ListLLMIntegrations(context.Context, *ListLLMIntegrationsRequest) (*ListLLMIntegrationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLLMIntegrations not implemented")
}
func (UnimplementedRunnerConfigurationServiceServer) UpdateLLMIntegration(context.Context, *UpdateLLMIntegrationRequest) (*UpdateLLMIntegrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLLMIntegration not implemented")
}
func (UnimplementedRunnerConfigurationServiceServer) DeleteLLMIntegration(context.Context, *DeleteLLMIntegrationRequest) (*DeleteLLMIntegrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLLMIntegration not implemented")
}
func (UnimplementedRunnerConfigurationServiceServer) mustEmbedUnimplementedRunnerConfigurationServiceServer() {
}
func (UnimplementedRunnerConfigurationServiceServer) testEmbeddedByValue() {}

// UnsafeRunnerConfigurationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunnerConfigurationServiceServer will
// result in compilation errors.
type UnsafeRunnerConfigurationServiceServer interface {
	mustEmbedUnimplementedRunnerConfigurationServiceServer()
}

func RegisterRunnerConfigurationServiceServer(s grpc.ServiceRegistrar, srv RunnerConfigurationServiceServer) {
	// If the following call pancis, it indicates UnimplementedRunnerConfigurationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RunnerConfigurationService_ServiceDesc, srv)
}

func _RunnerConfigurationService_CreateHostAuthenticationToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHostAuthenticationTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerConfigurationServiceServer).CreateHostAuthenticationToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerConfigurationService_CreateHostAuthenticationToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerConfigurationServiceServer).CreateHostAuthenticationToken(ctx, req.(*CreateHostAuthenticationTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerConfigurationService_GetHostAuthenticationToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostAuthenticationTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerConfigurationServiceServer).GetHostAuthenticationToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerConfigurationService_GetHostAuthenticationToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerConfigurationServiceServer).GetHostAuthenticationToken(ctx, req.(*GetHostAuthenticationTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerConfigurationService_ListHostAuthenticationTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHostAuthenticationTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerConfigurationServiceServer).ListHostAuthenticationTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerConfigurationService_ListHostAuthenticationTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerConfigurationServiceServer).ListHostAuthenticationTokens(ctx, req.(*ListHostAuthenticationTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerConfigurationService_UpdateHostAuthenticationToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHostAuthenticationTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerConfigurationServiceServer).UpdateHostAuthenticationToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerConfigurationService_UpdateHostAuthenticationToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerConfigurationServiceServer).UpdateHostAuthenticationToken(ctx, req.(*UpdateHostAuthenticationTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerConfigurationService_UpdateHostAuthenticationTokenMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHostAuthenticationTokenMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerConfigurationServiceServer).UpdateHostAuthenticationTokenMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerConfigurationService_UpdateHostAuthenticationTokenMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerConfigurationServiceServer).UpdateHostAuthenticationTokenMetadata(ctx, req.(*UpdateHostAuthenticationTokenMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerConfigurationService_DeleteHostAuthenticationToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHostAuthenticationTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerConfigurationServiceServer).DeleteHostAuthenticationToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerConfigurationService_DeleteHostAuthenticationToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerConfigurationServiceServer).DeleteHostAuthenticationToken(ctx, req.(*DeleteHostAuthenticationTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerConfigurationService_GetRunnerConfigurationSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunnerConfigurationSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerConfigurationServiceServer).GetRunnerConfigurationSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerConfigurationService_GetRunnerConfigurationSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerConfigurationServiceServer).GetRunnerConfigurationSchema(ctx, req.(*GetRunnerConfigurationSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerConfigurationService_CreateSCMIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSCMIntegrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerConfigurationServiceServer).CreateSCMIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerConfigurationService_CreateSCMIntegration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerConfigurationServiceServer).CreateSCMIntegration(ctx, req.(*CreateSCMIntegrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerConfigurationService_GetSCMIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSCMIntegrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerConfigurationServiceServer).GetSCMIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerConfigurationService_GetSCMIntegration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerConfigurationServiceServer).GetSCMIntegration(ctx, req.(*GetSCMIntegrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerConfigurationService_ListSCMIntegrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSCMIntegrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerConfigurationServiceServer).ListSCMIntegrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerConfigurationService_ListSCMIntegrations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerConfigurationServiceServer).ListSCMIntegrations(ctx, req.(*ListSCMIntegrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerConfigurationService_UpdateSCMIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSCMIntegrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerConfigurationServiceServer).UpdateSCMIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerConfigurationService_UpdateSCMIntegration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerConfigurationServiceServer).UpdateSCMIntegration(ctx, req.(*UpdateSCMIntegrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerConfigurationService_DeleteSCMIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSCMIntegrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerConfigurationServiceServer).DeleteSCMIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerConfigurationService_DeleteSCMIntegration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerConfigurationServiceServer).DeleteSCMIntegration(ctx, req.(*DeleteSCMIntegrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerConfigurationService_CreateEnvironmentClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEnvironmentClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerConfigurationServiceServer).CreateEnvironmentClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerConfigurationService_CreateEnvironmentClass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerConfigurationServiceServer).CreateEnvironmentClass(ctx, req.(*CreateEnvironmentClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerConfigurationService_GetEnvironmentClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnvironmentClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerConfigurationServiceServer).GetEnvironmentClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerConfigurationService_GetEnvironmentClass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerConfigurationServiceServer).GetEnvironmentClass(ctx, req.(*GetEnvironmentClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerConfigurationService_ListEnvironmentClasses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnvironmentClassesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerConfigurationServiceServer).ListEnvironmentClasses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerConfigurationService_ListEnvironmentClasses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerConfigurationServiceServer).ListEnvironmentClasses(ctx, req.(*ListEnvironmentClassesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerConfigurationService_UpdateEnvironmentClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEnvironmentClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerConfigurationServiceServer).UpdateEnvironmentClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerConfigurationService_UpdateEnvironmentClass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerConfigurationServiceServer).UpdateEnvironmentClass(ctx, req.(*UpdateEnvironmentClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerConfigurationService_ValidateRunnerConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRunnerConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerConfigurationServiceServer).ValidateRunnerConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerConfigurationService_ValidateRunnerConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerConfigurationServiceServer).ValidateRunnerConfiguration(ctx, req.(*ValidateRunnerConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerConfigurationService_CreateLLMIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLLMIntegrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerConfigurationServiceServer).CreateLLMIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerConfigurationService_CreateLLMIntegration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerConfigurationServiceServer).CreateLLMIntegration(ctx, req.(*CreateLLMIntegrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerConfigurationService_GetLLMIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLLMIntegrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerConfigurationServiceServer).GetLLMIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerConfigurationService_GetLLMIntegration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerConfigurationServiceServer).GetLLMIntegration(ctx, req.(*GetLLMIntegrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerConfigurationService_ListLLMIntegrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLLMIntegrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerConfigurationServiceServer).ListLLMIntegrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerConfigurationService_ListLLMIntegrations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerConfigurationServiceServer).ListLLMIntegrations(ctx, req.(*ListLLMIntegrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerConfigurationService_UpdateLLMIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLLMIntegrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerConfigurationServiceServer).UpdateLLMIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerConfigurationService_UpdateLLMIntegration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerConfigurationServiceServer).UpdateLLMIntegration(ctx, req.(*UpdateLLMIntegrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerConfigurationService_DeleteLLMIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLLMIntegrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerConfigurationServiceServer).DeleteLLMIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerConfigurationService_DeleteLLMIntegration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerConfigurationServiceServer).DeleteLLMIntegration(ctx, req.(*DeleteLLMIntegrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RunnerConfigurationService_ServiceDesc is the grpc.ServiceDesc for RunnerConfigurationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunnerConfigurationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gitpod.v1.RunnerConfigurationService",
	HandlerType: (*RunnerConfigurationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHostAuthenticationToken",
			Handler:    _RunnerConfigurationService_CreateHostAuthenticationToken_Handler,
		},
		{
			MethodName: "GetHostAuthenticationToken",
			Handler:    _RunnerConfigurationService_GetHostAuthenticationToken_Handler,
		},
		{
			MethodName: "ListHostAuthenticationTokens",
			Handler:    _RunnerConfigurationService_ListHostAuthenticationTokens_Handler,
		},
		{
			MethodName: "UpdateHostAuthenticationToken",
			Handler:    _RunnerConfigurationService_UpdateHostAuthenticationToken_Handler,
		},
		{
			MethodName: "UpdateHostAuthenticationTokenMetadata",
			Handler:    _RunnerConfigurationService_UpdateHostAuthenticationTokenMetadata_Handler,
		},
		{
			MethodName: "DeleteHostAuthenticationToken",
			Handler:    _RunnerConfigurationService_DeleteHostAuthenticationToken_Handler,
		},
		{
			MethodName: "GetRunnerConfigurationSchema",
			Handler:    _RunnerConfigurationService_GetRunnerConfigurationSchema_Handler,
		},
		{
			MethodName: "CreateSCMIntegration",
			Handler:    _RunnerConfigurationService_CreateSCMIntegration_Handler,
		},
		{
			MethodName: "GetSCMIntegration",
			Handler:    _RunnerConfigurationService_GetSCMIntegration_Handler,
		},
		{
			MethodName: "ListSCMIntegrations",
			Handler:    _RunnerConfigurationService_ListSCMIntegrations_Handler,
		},
		{
			MethodName: "UpdateSCMIntegration",
			Handler:    _RunnerConfigurationService_UpdateSCMIntegration_Handler,
		},
		{
			MethodName: "DeleteSCMIntegration",
			Handler:    _RunnerConfigurationService_DeleteSCMIntegration_Handler,
		},
		{
			MethodName: "CreateEnvironmentClass",
			Handler:    _RunnerConfigurationService_CreateEnvironmentClass_Handler,
		},
		{
			MethodName: "GetEnvironmentClass",
			Handler:    _RunnerConfigurationService_GetEnvironmentClass_Handler,
		},
		{
			MethodName: "ListEnvironmentClasses",
			Handler:    _RunnerConfigurationService_ListEnvironmentClasses_Handler,
		},
		{
			MethodName: "UpdateEnvironmentClass",
			Handler:    _RunnerConfigurationService_UpdateEnvironmentClass_Handler,
		},
		{
			MethodName: "ValidateRunnerConfiguration",
			Handler:    _RunnerConfigurationService_ValidateRunnerConfiguration_Handler,
		},
		{
			MethodName: "CreateLLMIntegration",
			Handler:    _RunnerConfigurationService_CreateLLMIntegration_Handler,
		},
		{
			MethodName: "GetLLMIntegration",
			Handler:    _RunnerConfigurationService_GetLLMIntegration_Handler,
		},
		{
			MethodName: "ListLLMIntegrations",
			Handler:    _RunnerConfigurationService_ListLLMIntegrations_Handler,
		},
		{
			MethodName: "UpdateLLMIntegration",
			Handler:    _RunnerConfigurationService_UpdateLLMIntegration_Handler,
		},
		{
			MethodName: "DeleteLLMIntegration",
			Handler:    _RunnerConfigurationService_DeleteLLMIntegration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gitpod/v1/runner_configuration.proto",
}
