// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gitpod/v1/insights.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/gitpod-io/terraform-provider-ona/internal/api/go/tools/logfields"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ScmProvider identifies the SCM platform a pull request was fetched from.
type ScmProvider int32

const (
	ScmProvider_SCM_PROVIDER_UNSPECIFIED ScmProvider = 0
	// GitHub.
	ScmProvider_SCM_PROVIDER_GITHUB ScmProvider = 1
	// GitLab.
	ScmProvider_SCM_PROVIDER_GITLAB ScmProvider = 2
	// Bitbucket.
	ScmProvider_SCM_PROVIDER_BITBUCKET ScmProvider = 3
)

// Enum value maps for ScmProvider.
var (
	ScmProvider_name = map[int32]string{
		0: "SCM_PROVIDER_UNSPECIFIED",
		1: "SCM_PROVIDER_GITHUB",
		2: "SCM_PROVIDER_GITLAB",
		3: "SCM_PROVIDER_BITBUCKET",
	}
	ScmProvider_value = map[string]int32{
		"SCM_PROVIDER_UNSPECIFIED": 0,
		"SCM_PROVIDER_GITHUB":      1,
		"SCM_PROVIDER_GITLAB":      2,
		"SCM_PROVIDER_BITBUCKET":   3,
	}
)

func (x ScmProvider) Enum() *ScmProvider {
	p := new(ScmProvider)
	*p = x
	return p
}

func (x ScmProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScmProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_gitpod_v1_insights_proto_enumTypes[0].Descriptor()
}

func (ScmProvider) Type() protoreflect.EnumType {
	return &file_gitpod_v1_insights_proto_enumTypes[0]
}

func (x ScmProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScmProvider.Descriptor instead.
func (ScmProvider) EnumDescriptor() ([]byte, []int) {
	return file_gitpod_v1_insights_proto_rawDescGZIP(), []int{0}
}

// CollectionOutcome describes the result of a single CLI collection batch.
// Persisted in project_insights_settings so operators can diagnose NULL
// watermarks from the DB alone.
type CollectionOutcome int32

const (
	CollectionOutcome_COLLECTION_OUTCOME_UNSPECIFIED CollectionOutcome = 0
	// Data collected and reported normally.
	CollectionOutcome_COLLECTION_OUTCOME_SUCCESS CollectionOutcome = 1
	// No commits or PRs found in the collection window. The watermark still
	// advances so the empty window is not re-fetched.
	CollectionOutcome_COLLECTION_OUTCOME_EMPTY_WINDOW CollectionOutcome = 2
	// The CLI failed to read git log (e.g. corrupt repo, missing branch).
	CollectionOutcome_COLLECTION_OUTCOME_GIT_LOG_ERROR CollectionOutcome = 3
	// The CLI failed to fetch PR data from the SCM API (e.g. auth failure,
	// rate limit, network error).
	CollectionOutcome_COLLECTION_OUTCOME_PR_FETCH_ERROR CollectionOutcome = 4
	// The CLI failed during setup before the collection loop started
	// (e.g. credential resolution, project resolution, git remote parsing).
	CollectionOutcome_COLLECTION_OUTCOME_SETUP_ERROR CollectionOutcome = 5
	// Catch-all for unexpected errors not covered by a specific variant.
	CollectionOutcome_COLLECTION_OUTCOME_UNKNOWN_ERROR CollectionOutcome = 6
)

// Enum value maps for CollectionOutcome.
var (
	CollectionOutcome_name = map[int32]string{
		0: "COLLECTION_OUTCOME_UNSPECIFIED",
		1: "COLLECTION_OUTCOME_SUCCESS",
		2: "COLLECTION_OUTCOME_EMPTY_WINDOW",
		3: "COLLECTION_OUTCOME_GIT_LOG_ERROR",
		4: "COLLECTION_OUTCOME_PR_FETCH_ERROR",
		5: "COLLECTION_OUTCOME_SETUP_ERROR",
		6: "COLLECTION_OUTCOME_UNKNOWN_ERROR",
	}
	CollectionOutcome_value = map[string]int32{
		"COLLECTION_OUTCOME_UNSPECIFIED":    0,
		"COLLECTION_OUTCOME_SUCCESS":        1,
		"COLLECTION_OUTCOME_EMPTY_WINDOW":   2,
		"COLLECTION_OUTCOME_GIT_LOG_ERROR":  3,
		"COLLECTION_OUTCOME_PR_FETCH_ERROR": 4,
		"COLLECTION_OUTCOME_SETUP_ERROR":    5,
		"COLLECTION_OUTCOME_UNKNOWN_ERROR":  6,
	}
)

func (x CollectionOutcome) Enum() *CollectionOutcome {
	p := new(CollectionOutcome)
	*p = x
	return p
}

func (x CollectionOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CollectionOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_gitpod_v1_insights_proto_enumTypes[1].Descriptor()
}

func (CollectionOutcome) Type() protoreflect.EnumType {
	return &file_gitpod_v1_insights_proto_enumTypes[1]
}

func (x CollectionOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CollectionOutcome.Descriptor instead.
func (CollectionOutcome) EnumDescriptor() ([]byte, []int) {
	return file_gitpod_v1_insights_proto_rawDescGZIP(), []int{1}
}

// Category distinguishes the source of the issue. The frontend may use
// this to choose copy ("Insights can't run yet…" vs "Last insights run
// failed…").
type InsightsHealthIssue_Category int32

const (
	InsightsHealthIssue_CATEGORY_UNSPECIFIED InsightsHealthIssue_Category = 0
	// The issue is a prerequisite that has not been met. Prerequisites are
	// deterministic, derived from project/org configuration, and checked
	// synchronously before a workflow execution is attempted.
	InsightsHealthIssue_CATEGORY_PREREQUISITE InsightsHealthIssue_Category = 1
	// The issue is a runtime failure observed after a workflow execution
	// was attempted. Runtime errors depend on runner-side state.
	InsightsHealthIssue_CATEGORY_RUNTIME InsightsHealthIssue_Category = 2
)

// Enum value maps for InsightsHealthIssue_Category.
var (
	InsightsHealthIssue_Category_name = map[int32]string{
		0: "CATEGORY_UNSPECIFIED",
		1: "CATEGORY_PREREQUISITE",
		2: "CATEGORY_RUNTIME",
	}
	InsightsHealthIssue_Category_value = map[string]int32{
		"CATEGORY_UNSPECIFIED":  0,
		"CATEGORY_PREREQUISITE": 1,
		"CATEGORY_RUNTIME":      2,
	}
)

func (x InsightsHealthIssue_Category) Enum() *InsightsHealthIssue_Category {
	p := new(InsightsHealthIssue_Category)
	*p = x
	return p
}

func (x InsightsHealthIssue_Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InsightsHealthIssue_Category) Descriptor() protoreflect.EnumDescriptor {
	return file_gitpod_v1_insights_proto_enumTypes[2].Descriptor()
}

func (InsightsHealthIssue_Category) Type() protoreflect.EnumType {
	return &file_gitpod_v1_insights_proto_enumTypes[2]
}

func (x InsightsHealthIssue_Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InsightsHealthIssue_Category.Descriptor instead.
func (InsightsHealthIssue_Category) EnumDescriptor() ([]byte, []int) {
	return file_gitpod_v1_insights_proto_rawDescGZIP(), []int{3, 0}
}

// CommitCoAuthorStat represents co-author data for a single commit.
type CommitCoAuthorStat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SHA of the commit. Used with project_id as the idempotency key.
	CommitHash string `protobuf:"bytes,1,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	// Author date of the commit.
	CommitDate *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=commit_date,json=commitDate,proto3" json:"commit_date,omitempty"`
	// Which tool co-authored this commit, NO_COAUTHOR for solo commits,
	// or HUMAN_COAUTHOR for human pair-programming.
	// UNSPECIFIED is rejected — callers must always set a concrete value.
	Tool CoAuthorTool `protobuf:"varint,3,opt,name=tool,proto3,enum=gitpod.v1.CoAuthorTool" json:"tool,omitempty"`
	// Lines added in this commit.
	LinesAdded int64 `protobuf:"varint,4,opt,name=lines_added,json=linesAdded,proto3" json:"lines_added,omitempty"`
	// Lines removed in this commit.
	LinesRemoved int64 `protobuf:"varint,5,opt,name=lines_removed,json=linesRemoved,proto3" json:"lines_removed,omitempty"`
	// One-way hash of the author email. Enables distinct author counts
	// without storing PII.
	AuthorHash string `protobuf:"bytes,6,opt,name=author_hash,json=authorHash,proto3" json:"author_hash,omitempty"`
	// Raw co-author email address from the Co-authored-by trailer.
	// Empty when there is no co-author trailer. Stored verbatim so the
	// backend can reclassify historical data when new AI tools are added.
	RawCoauthor string `protobuf:"bytes,7,opt,name=raw_coauthor,json=rawCoauthor,proto3" json:"raw_coauthor,omitempty"`
	// Stable numeric user ID from the SCM provider for the commit author
	// (e.g. GitHub user.id resolved via the commit API). Used by the backend
	// to resolve the commit author to an Ona user via HostAuthenticationToken.
	// Empty when the CLI cannot resolve the email or the provider doesn't
	// support it.
	AuthorScmId   string `protobuf:"bytes,8,opt,name=author_scm_id,json=authorScmId,proto3" json:"author_scm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitCoAuthorStat) Reset() {
	*x = CommitCoAuthorStat{}
	mi := &file_gitpod_v1_insights_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitCoAuthorStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitCoAuthorStat) ProtoMessage() {}

func (x *CommitCoAuthorStat) ProtoReflect() protoreflect.Message {
	mi := &file_gitpod_v1_insights_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitCoAuthorStat.ProtoReflect.Descriptor instead.
func (*CommitCoAuthorStat) Descriptor() ([]byte, []int) {
	return file_gitpod_v1_insights_proto_rawDescGZIP(), []int{0}
}

func (x *CommitCoAuthorStat) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *CommitCoAuthorStat) GetCommitDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CommitDate
	}
	return nil
}

func (x *CommitCoAuthorStat) GetTool() CoAuthorTool {
	if x != nil {
		return x.Tool
	}
	return CoAuthorTool_CO_AUTHOR_TOOL_UNSPECIFIED
}

func (x *CommitCoAuthorStat) GetLinesAdded() int64 {
	if x != nil {
		return x.LinesAdded
	}
	return 0
}

func (x *CommitCoAuthorStat) GetLinesRemoved() int64 {
	if x != nil {
		return x.LinesRemoved
	}
	return 0
}

func (x *CommitCoAuthorStat) GetAuthorHash() string {
	if x != nil {
		return x.AuthorHash
	}
	return ""
}

func (x *CommitCoAuthorStat) GetRawCoauthor() string {
	if x != nil {
		return x.RawCoauthor
	}
	return ""
}

func (x *CommitCoAuthorStat) GetAuthorScmId() string {
	if x != nil {
		return x.AuthorScmId
	}
	return ""
}

// EnableProjectInsightsRequest enables co-author insights for a project.
type EnableProjectInsightsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project to enable insights for.
	ProjectId     string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableProjectInsightsRequest) Reset() {
	*x = EnableProjectInsightsRequest{}
	mi := &file_gitpod_v1_insights_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableProjectInsightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableProjectInsightsRequest) ProtoMessage() {}

func (x *EnableProjectInsightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitpod_v1_insights_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableProjectInsightsRequest.ProtoReflect.Descriptor instead.
func (*EnableProjectInsightsRequest) Descriptor() ([]byte, []int) {
	return file_gitpod_v1_insights_proto_rawDescGZIP(), []int{1}
}

func (x *EnableProjectInsightsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type EnableProjectInsightsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableProjectInsightsResponse) Reset() {
	*x = EnableProjectInsightsResponse{}
	mi := &file_gitpod_v1_insights_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableProjectInsightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableProjectInsightsResponse) ProtoMessage() {}

func (x *EnableProjectInsightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitpod_v1_insights_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableProjectInsightsResponse.ProtoReflect.Descriptor instead.
func (*EnableProjectInsightsResponse) Descriptor() ([]byte, []int) {
	return file_gitpod_v1_insights_proto_rawDescGZIP(), []int{2}
}

// InsightsHealthIssue describes one reason why insights for a project is
// either not runnable (prerequisite) or last failed (runtime). The
// error_code field comes from the shared errorcodes registry; the frontend
// renders it via the same map used for environment errors.
type InsightsHealthIssue struct {
	state    protoimpl.MessageState       `protogen:"open.v1"`
	Category InsightsHealthIssue_Category `protobuf:"varint,1,opt,name=category,proto3,enum=gitpod.v1.InsightsHealthIssue_Category" json:"category,omitempty"`
	// Stable machine identifier of the issue (e.g.
	// "PROJECT_NO_ENVIRONMENT_CLASS"). The frontend looks this up in the
	// generated error-codes map.
	ErrorCode string `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// Rendering hints (e.g. environment_class_id, runner_id, attempted_at).
	// Keys are defined by the code that produces the issue.
	Metadata map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// When this issue was observed. For prerequisites it's "now"; for
	// runtime errors it's the failed execution's end time.
	DetectedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=detected_at,json=detectedAt,proto3" json:"detected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsightsHealthIssue) Reset() {
	*x = InsightsHealthIssue{}
	mi := &file_gitpod_v1_insights_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsightsHealthIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsightsHealthIssue) ProtoMessage() {}

func (x *InsightsHealthIssue) ProtoReflect() protoreflect.Message {
	mi := &file_gitpod_v1_insights_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsightsHealthIssue.ProtoReflect.Descriptor instead.
func (*InsightsHealthIssue) Descriptor() ([]byte, []int) {
	return file_gitpod_v1_insights_proto_rawDescGZIP(), []int{3}
}

func (x *InsightsHealthIssue) GetCategory() InsightsHealthIssue_Category {
	if x != nil {
		return x.Category
	}
	return InsightsHealthIssue_CATEGORY_UNSPECIFIED
}

func (x *InsightsHealthIssue) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *InsightsHealthIssue) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InsightsHealthIssue) GetDetectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DetectedAt
	}
	return nil
}

// DisableProjectInsightsRequest disables co-author insights for a project.
type DisableProjectInsightsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project to disable insights for.
	ProjectId     string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableProjectInsightsRequest) Reset() {
	*x = DisableProjectInsightsRequest{}
	mi := &file_gitpod_v1_insights_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableProjectInsightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableProjectInsightsRequest) ProtoMessage() {}

func (x *DisableProjectInsightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitpod_v1_insights_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableProjectInsightsRequest.ProtoReflect.Descriptor instead.
func (*DisableProjectInsightsRequest) Descriptor() ([]byte, []int) {
	return file_gitpod_v1_insights_proto_rawDescGZIP(), []int{4}
}

func (x *DisableProjectInsightsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type DisableProjectInsightsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableProjectInsightsResponse) Reset() {
	*x = DisableProjectInsightsResponse{}
	mi := &file_gitpod_v1_insights_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableProjectInsightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableProjectInsightsResponse) ProtoMessage() {}

func (x *DisableProjectInsightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitpod_v1_insights_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableProjectInsightsResponse.ProtoReflect.Descriptor instead.
func (*DisableProjectInsightsResponse) Descriptor() ([]byte, []int) {
	return file_gitpod_v1_insights_proto_rawDescGZIP(), []int{5}
}

// GetProjectInsightsStatusRequest checks whether insights is enabled for a project.
type GetProjectInsightsStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project to check.
	ProjectId     string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectInsightsStatusRequest) Reset() {
	*x = GetProjectInsightsStatusRequest{}
	mi := &file_gitpod_v1_insights_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectInsightsStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectInsightsStatusRequest) ProtoMessage() {}

func (x *GetProjectInsightsStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitpod_v1_insights_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectInsightsStatusRequest.ProtoReflect.Descriptor instead.
func (*GetProjectInsightsStatusRequest) Descriptor() ([]byte, []int) {
	return file_gitpod_v1_insights_proto_rawDescGZIP(), []int{6}
}

func (x *GetProjectInsightsStatusRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetProjectInsightsStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether co-author insights is enabled for the project.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// When the insights workflow last completed successfully.
	// Nil when enabled is true but no data has been collected yet (pending state).
	LastRanAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_ran_at,json=lastRanAt,proto3" json:"last_ran_at,omitempty"`
	// Issues preventing the workflow from running. Empty when enabled is
	// false, or when enabled and prerequisites are met. The frontend should
	// render the first issue prominently. Today only carries
	// CATEGORY_PREREQUISITE; CATEGORY_RUNTIME will be added later.
	InsightsHealth []*InsightsHealthIssue `protobuf:"bytes,3,rep,name=insights_health,json=insightsHealth,proto3" json:"insights_health,omitempty"`
	// Upper bound of the most recent batch successfully written for this
	// project. Nil when no data has been collected yet (first-time enable
	// or never run). The CLI reads this to decide where to resume
	// collection.
	DataCollectedThrough *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=data_collected_through,json=dataCollectedThrough,proto3" json:"data_collected_through,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetProjectInsightsStatusResponse) Reset() {
	*x = GetProjectInsightsStatusResponse{}
	mi := &file_gitpod_v1_insights_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectInsightsStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectInsightsStatusResponse) ProtoMessage() {}

func (x *GetProjectInsightsStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitpod_v1_insights_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectInsightsStatusResponse.ProtoReflect.Descriptor instead.
func (*GetProjectInsightsStatusResponse) Descriptor() ([]byte, []int) {
	return file_gitpod_v1_insights_proto_rawDescGZIP(), []int{7}
}

func (x *GetProjectInsightsStatusResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GetProjectInsightsStatusResponse) GetLastRanAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRanAt
	}
	return nil
}

func (x *GetProjectInsightsStatusResponse) GetInsightsHealth() []*InsightsHealthIssue {
	if x != nil {
		return x.InsightsHealth
	}
	return nil
}

func (x *GetProjectInsightsStatusResponse) GetDataCollectedThrough() *timestamppb.Timestamp {
	if x != nil {
		return x.DataCollectedThrough
	}
	return nil
}

// ReportAgentTraceRequest pushes an agent trace session containing one or more
// trace lines (typically JSONL) for storage.
type ReportAgentTraceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project the trace belongs to.
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Environment that produced the trace.
	EnvironmentId string `protobuf:"bytes,2,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	// Agent execution that produced the trace.
	AgentExecutionId string `protobuf:"bytes,3,opt,name=agent_execution_id,json=agentExecutionId,proto3" json:"agent_execution_id,omitempty"`
	// Total lines added across all edits in the trace session.
	LinesAdded int64 `protobuf:"varint,4,opt,name=lines_added,json=linesAdded,proto3" json:"lines_added,omitempty"`
	// Total lines removed across all edits in the trace session.
	LinesRemoved int64 `protobuf:"varint,5,opt,name=lines_removed,json=linesRemoved,proto3" json:"lines_removed,omitempty"`
	// The LLM model used during this agent session.
	Model SupportedModel `protobuf:"varint,7,opt,name=model,proto3,enum=gitpod.v1.SupportedModel" json:"model,omitempty"`
	// Individual trace lines (typically one JSON object per line).
	// May be empty when only line-count aggregates are reported.
	// Each line is capped at 5 MiB.
	Traces        []string `protobuf:"bytes,6,rep,name=traces,proto3" json:"traces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAgentTraceRequest) Reset() {
	*x = ReportAgentTraceRequest{}
	mi := &file_gitpod_v1_insights_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAgentTraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAgentTraceRequest) ProtoMessage() {}

func (x *ReportAgentTraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitpod_v1_insights_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAgentTraceRequest.ProtoReflect.Descriptor instead.
func (*ReportAgentTraceRequest) Descriptor() ([]byte, []int) {
	return file_gitpod_v1_insights_proto_rawDescGZIP(), []int{8}
}

func (x *ReportAgentTraceRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ReportAgentTraceRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *ReportAgentTraceRequest) GetAgentExecutionId() string {
	if x != nil {
		return x.AgentExecutionId
	}
	return ""
}

func (x *ReportAgentTraceRequest) GetLinesAdded() int64 {
	if x != nil {
		return x.LinesAdded
	}
	return 0
}

func (x *ReportAgentTraceRequest) GetLinesRemoved() int64 {
	if x != nil {
		return x.LinesRemoved
	}
	return 0
}

func (x *ReportAgentTraceRequest) GetModel() SupportedModel {
	if x != nil {
		return x.Model
	}
	return SupportedModel_SUPPORTED_MODEL_UNSPECIFIED
}

func (x *ReportAgentTraceRequest) GetTraces() []string {
	if x != nil {
		return x.Traces
	}
	return nil
}

type ReportAgentTraceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAgentTraceResponse) Reset() {
	*x = ReportAgentTraceResponse{}
	mi := &file_gitpod_v1_insights_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAgentTraceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAgentTraceResponse) ProtoMessage() {}

func (x *ReportAgentTraceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitpod_v1_insights_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAgentTraceResponse.ProtoReflect.Descriptor instead.
func (*ReportAgentTraceResponse) Descriptor() ([]byte, []int) {
	return file_gitpod_v1_insights_proto_rawDescGZIP(), []int{9}
}

// PullRequestStat represents speed metrics for a single merged pull request.
type PullRequestStat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PR/MR number from the SCM provider. Together with project_id forms the
	// idempotency key for upserts.
	PrNumber int32 `protobuf:"varint,1,opt,name=pr_number,json=prNumber,proto3" json:"pr_number,omitempty"`
	// Raw SCM username of the PR author (e.g. GitHub user.login, GitLab author.username).
	AuthorLogin string `protobuf:"bytes,2,opt,name=author_login,json=authorLogin,proto3" json:"author_login,omitempty"`
	// When the PR was opened.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// When the PR was merged.
	MergedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=merged_at,json=mergedAt,proto3" json:"merged_at,omitempty"`
	// Author date of the earliest commit on the PR branch.
	FirstCommitAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=first_commit_at,json=firstCommitAt,proto3" json:"first_commit_at,omitempty"`
	// Timestamp of the earliest approving review. Unset when the PR had no approvals.
	FirstApprovalAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=first_approval_at,json=firstApprovalAt,proto3" json:"first_approval_at,omitempty"`
	// Branch the PR was merged into (e.g. "main").
	TargetBranch string `protobuf:"bytes,7,opt,name=target_branch,json=targetBranch,proto3" json:"target_branch,omitempty"`
	// SCM platform the PR was fetched from.
	ScmProvider ScmProvider `protobuf:"varint,8,opt,name=scm_provider,json=scmProvider,proto3,enum=gitpod.v1.ScmProvider" json:"scm_provider,omitempty"`
	// Stable numeric user ID from the SCM provider (e.g. GitHub user.id,
	// GitLab author.id, Bitbucket author.uuid). Used by the backend to
	// resolve the PR author to an Ona user via HostAuthenticationToken.
	// Empty when the provider doesn't supply it or the CLI is too old.
	AuthorScmId   string `protobuf:"bytes,9,opt,name=author_scm_id,json=authorScmId,proto3" json:"author_scm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequestStat) Reset() {
	*x = PullRequestStat{}
	mi := &file_gitpod_v1_insights_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequestStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequestStat) ProtoMessage() {}

func (x *PullRequestStat) ProtoReflect() protoreflect.Message {
	mi := &file_gitpod_v1_insights_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequestStat.ProtoReflect.Descriptor instead.
func (*PullRequestStat) Descriptor() ([]byte, []int) {
	return file_gitpod_v1_insights_proto_rawDescGZIP(), []int{10}
}

func (x *PullRequestStat) GetPrNumber() int32 {
	if x != nil {
		return x.PrNumber
	}
	return 0
}

func (x *PullRequestStat) GetAuthorLogin() string {
	if x != nil {
		return x.AuthorLogin
	}
	return ""
}

func (x *PullRequestStat) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PullRequestStat) GetMergedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MergedAt
	}
	return nil
}

func (x *PullRequestStat) GetFirstCommitAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstCommitAt
	}
	return nil
}

func (x *PullRequestStat) GetFirstApprovalAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstApprovalAt
	}
	return nil
}

func (x *PullRequestStat) GetTargetBranch() string {
	if x != nil {
		return x.TargetBranch
	}
	return ""
}

func (x *PullRequestStat) GetScmProvider() ScmProvider {
	if x != nil {
		return x.ScmProvider
	}
	return ScmProvider_SCM_PROVIDER_UNSPECIFIED
}

func (x *PullRequestStat) GetAuthorScmId() string {
	if x != nil {
		return x.AuthorScmId
	}
	return ""
}

// ReportInsightsBatchRequest carries one collection window's worth of
// co-author and PR stats together with the upper bound of the window. The
// backend writes both stat types and advances the watermark
// (data_collected_through = max(current, collected_through)) in a single
// transaction.
//
// When collection_outcome is an error variant the backend persists the
// outcome and error message but skips stat upserts and watermark
// advancement, so the next run re-attempts the same window.
type ReportInsightsBatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project that was analyzed.
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Co-author stats for this batch window. May be empty.
	CoauthorStats []*CommitCoAuthorStat `protobuf:"bytes,2,rep,name=coauthor_stats,json=coauthorStats,proto3" json:"coauthor_stats,omitempty"`
	// PR stats for this batch window. May be empty.
	PrStats []*PullRequestStat `protobuf:"bytes,3,rep,name=pr_stats,json=prStats,proto3" json:"pr_stats,omitempty"`
	// Upper bound of this batch window. Required when collection_outcome is
	// SUCCESS or EMPTY_WINDOW. Optional (may be nil) for error outcomes
	// where the CLI has no valid window end timestamp.
	CollectedThrough *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=collected_through,json=collectedThrough,proto3" json:"collected_through,omitempty"`
	// Outcome of this collection batch. Old CLIs omit this field
	// (UNSPECIFIED); the backend treats UNSPECIFIED as SUCCESS.
	CollectionOutcome CollectionOutcome `protobuf:"varint,5,opt,name=collection_outcome,json=collectionOutcome,proto3,enum=gitpod.v1.CollectionOutcome" json:"collection_outcome,omitempty"`
	// Human-readable error detail when collection_outcome is an error
	// variant. Empty for SUCCESS / EMPTY_WINDOW.
	// The backend truncates values longer than 1024 characters.
	CollectionErrorMessage string `protobuf:"bytes,6,opt,name=collection_error_message,json=collectionErrorMessage,proto3" json:"collection_error_message,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ReportInsightsBatchRequest) Reset() {
	*x = ReportInsightsBatchRequest{}
	mi := &file_gitpod_v1_insights_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportInsightsBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportInsightsBatchRequest) ProtoMessage() {}

func (x *ReportInsightsBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitpod_v1_insights_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportInsightsBatchRequest.ProtoReflect.Descriptor instead.
func (*ReportInsightsBatchRequest) Descriptor() ([]byte, []int) {
	return file_gitpod_v1_insights_proto_rawDescGZIP(), []int{11}
}

func (x *ReportInsightsBatchRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ReportInsightsBatchRequest) GetCoauthorStats() []*CommitCoAuthorStat {
	if x != nil {
		return x.CoauthorStats
	}
	return nil
}

func (x *ReportInsightsBatchRequest) GetPrStats() []*PullRequestStat {
	if x != nil {
		return x.PrStats
	}
	return nil
}

func (x *ReportInsightsBatchRequest) GetCollectedThrough() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedThrough
	}
	return nil
}

func (x *ReportInsightsBatchRequest) GetCollectionOutcome() CollectionOutcome {
	if x != nil {
		return x.CollectionOutcome
	}
	return CollectionOutcome_COLLECTION_OUTCOME_UNSPECIFIED
}

func (x *ReportInsightsBatchRequest) GetCollectionErrorMessage() string {
	if x != nil {
		return x.CollectionErrorMessage
	}
	return ""
}

type ReportInsightsBatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of co-author rows inserted (new commits).
	CoauthorInsertedCount int64 `protobuf:"varint,1,opt,name=coauthor_inserted_count,json=coauthorInsertedCount,proto3" json:"coauthor_inserted_count,omitempty"`
	// Number of co-author rows updated (re-reported commits).
	CoauthorUpdatedCount int64 `protobuf:"varint,2,opt,name=coauthor_updated_count,json=coauthorUpdatedCount,proto3" json:"coauthor_updated_count,omitempty"`
	// Number of PR rows inserted (new PRs).
	PrInsertedCount int64 `protobuf:"varint,3,opt,name=pr_inserted_count,json=prInsertedCount,proto3" json:"pr_inserted_count,omitempty"`
	// Number of PR rows updated (re-reported PRs).
	PrUpdatedCount int64 `protobuf:"varint,4,opt,name=pr_updated_count,json=prUpdatedCount,proto3" json:"pr_updated_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportInsightsBatchResponse) Reset() {
	*x = ReportInsightsBatchResponse{}
	mi := &file_gitpod_v1_insights_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportInsightsBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportInsightsBatchResponse) ProtoMessage() {}

func (x *ReportInsightsBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitpod_v1_insights_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportInsightsBatchResponse.ProtoReflect.Descriptor instead.
func (*ReportInsightsBatchResponse) Descriptor() ([]byte, []int) {
	return file_gitpod_v1_insights_proto_rawDescGZIP(), []int{12}
}

func (x *ReportInsightsBatchResponse) GetCoauthorInsertedCount() int64 {
	if x != nil {
		return x.CoauthorInsertedCount
	}
	return 0
}

func (x *ReportInsightsBatchResponse) GetCoauthorUpdatedCount() int64 {
	if x != nil {
		return x.CoauthorUpdatedCount
	}
	return 0
}

func (x *ReportInsightsBatchResponse) GetPrInsertedCount() int64 {
	if x != nil {
		return x.PrInsertedCount
	}
	return 0
}

func (x *ReportInsightsBatchResponse) GetPrUpdatedCount() int64 {
	if x != nil {
		return x.PrUpdatedCount
	}
	return 0
}

// GetInsightsSummaryRequest returns project-level insights adoption for the org.
type GetInsightsSummaryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Organization to query.
	OrganizationId string `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetInsightsSummaryRequest) Reset() {
	*x = GetInsightsSummaryRequest{}
	mi := &file_gitpod_v1_insights_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInsightsSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInsightsSummaryRequest) ProtoMessage() {}

func (x *GetInsightsSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitpod_v1_insights_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInsightsSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetInsightsSummaryRequest) Descriptor() ([]byte, []int) {
	return file_gitpod_v1_insights_proto_rawDescGZIP(), []int{13}
}

func (x *GetInsightsSummaryRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type GetInsightsSummaryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of projects with insights enabled.
	EnabledProjectCount int64 `protobuf:"varint,1,opt,name=enabled_project_count,json=enabledProjectCount,proto3" json:"enabled_project_count,omitempty"`
	// Total number of projects in the organization.
	TotalProjectCount int64 `protobuf:"varint,2,opt,name=total_project_count,json=totalProjectCount,proto3" json:"total_project_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetInsightsSummaryResponse) Reset() {
	*x = GetInsightsSummaryResponse{}
	mi := &file_gitpod_v1_insights_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInsightsSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInsightsSummaryResponse) ProtoMessage() {}

func (x *GetInsightsSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitpod_v1_insights_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInsightsSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetInsightsSummaryResponse) Descriptor() ([]byte, []int) {
	return file_gitpod_v1_insights_proto_rawDescGZIP(), []int{14}
}

func (x *GetInsightsSummaryResponse) GetEnabledProjectCount() int64 {
	if x != nil {
		return x.EnabledProjectCount
	}
	return 0
}

func (x *GetInsightsSummaryResponse) GetTotalProjectCount() int64 {
	if x != nil {
		return x.TotalProjectCount
	}
	return 0
}

var File_gitpod_v1_insights_proto protoreflect.FileDescriptor

const file_gitpod_v1_insights_proto_rawDesc = "" +
	"\n" +
	"\x18gitpod/v1/insights.proto\x12\tgitpod.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgitpod/tools/v1/logfields.proto\x1a\x15gitpod/v1/model.proto\x1a\x15gitpod/v1/usage.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x03\n" +
	"\x12CommitCoAuthorStat\x12*\n" +
	"\vcommit_hash\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\n" +
	"commitHash\x12C\n" +
	"\vcommit_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"commitDate\x127\n" +
	"\x04tool\x18\x03 \x01(\x0e2\x17.gitpod.v1.CoAuthorToolB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x04tool\x12(\n" +
	"\vlines_added\x18\x04 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\n" +
	"linesAdded\x12,\n" +
	"\rlines_removed\x18\x05 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\flinesRemoved\x12+\n" +
	"\vauthor_hash\x18\x06 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\n" +
	"authorHash\x12+\n" +
	"\fraw_coauthor\x18\a \x01(\tB\b\xbaH\x05r\x03\x18\xc0\x02R\vrawCoauthor\x12,\n" +
	"\rauthor_scm_id\x18\b \x01(\tB\b\xbaH\x05r\x03\x18\x80\x02R\vauthorScmId\"W\n" +
	"\x1cEnableProjectInsightsRequest\x127\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x18\xbaH\x05r\x03\xb0\x01\x01\xa2\xab\x1e\f\n" +
	"\n" +
	"project.idR\tprojectId\"\x1f\n" +
	"\x1dEnableProjectInsightsResponse\"\x94\x03\n" +
	"\x13InsightsHealthIssue\x12C\n" +
	"\bcategory\x18\x01 \x01(\x0e2'.gitpod.v1.InsightsHealthIssue.CategoryR\bcategory\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12H\n" +
	"\bmetadata\x18\x03 \x03(\v2,.gitpod.v1.InsightsHealthIssue.MetadataEntryR\bmetadata\x12;\n" +
	"\vdetected_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"detectedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\bCategory\x12\x18\n" +
	"\x14CATEGORY_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CATEGORY_PREREQUISITE\x10\x01\x12\x14\n" +
	"\x10CATEGORY_RUNTIME\x10\x02\"X\n" +
	"\x1dDisableProjectInsightsRequest\x127\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x18\xbaH\x05r\x03\xb0\x01\x01\xa2\xab\x1e\f\n" +
	"\n" +
	"project.idR\tprojectId\" \n" +
	"\x1eDisableProjectInsightsResponse\"Z\n" +
	"\x1fGetProjectInsightsStatusRequest\x127\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x18\xbaH\x05r\x03\xb0\x01\x01\xa2\xab\x1e\f\n" +
	"\n" +
	"project.idR\tprojectId\"\x93\x02\n" +
	" GetProjectInsightsStatusResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12:\n" +
	"\vlast_ran_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tlastRanAt\x12G\n" +
	"\x0finsights_health\x18\x03 \x03(\v2\x1e.gitpod.v1.InsightsHealthIssueR\x0einsightsHealth\x12P\n" +
	"\x16data_collected_through\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x14dataCollectedThrough\"\x9a\x03\n" +
	"\x17ReportAgentTraceRequest\x127\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x18\xbaH\x05r\x03\xb0\x01\x01\xa2\xab\x1e\f\n" +
	"\n" +
	"project.idR\tprojectId\x12C\n" +
	"\x0eenvironment_id\x18\x02 \x01(\tB\x1c\xbaH\x05r\x03\xb0\x01\x01\xa2\xab\x1e\x10\n" +
	"\x0eenvironment.idR\renvironmentId\x12M\n" +
	"\x12agent_execution_id\x18\x03 \x01(\tB\x1f\xbaH\x05r\x03\xb0\x01\x01\xa2\xab\x1e\x13\n" +
	"\x11agentExecution.idR\x10agentExecutionId\x12(\n" +
	"\vlines_added\x18\x04 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\n" +
	"linesAdded\x12,\n" +
	"\rlines_removed\x18\x05 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\flinesRemoved\x12/\n" +
	"\x05model\x18\a \x01(\x0e2\x19.gitpod.v1.SupportedModelR\x05model\x12)\n" +
	"\x06traces\x18\x06 \x03(\tB\x11\xbaH\x0e\x92\x01\v\"\tr\a\x10\x01\x18\x80\x80\xc0\x02R\x06traces\"\x1a\n" +
	"\x18ReportAgentTraceResponse\"\xa4\x04\n" +
	"\x0fPullRequestStat\x12$\n" +
	"\tpr_number\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\bprNumber\x12-\n" +
	"\fauthor_login\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02R\vauthorLogin\x12A\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tcreatedAt\x12?\n" +
	"\tmerged_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\bmergedAt\x12J\n" +
	"\x0ffirst_commit_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\rfirstCommitAt\x12F\n" +
	"\x11first_approval_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0ffirstApprovalAt\x12/\n" +
	"\rtarget_branch\x18\a \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02R\ftargetBranch\x12E\n" +
	"\fscm_provider\x18\b \x01(\x0e2\x16.gitpod.v1.ScmProviderB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\vscmProvider\x12,\n" +
	"\rauthor_scm_id\x18\t \x01(\tB\b\xbaH\x05r\x03\x18\x80\x02R\vauthorScmId\"\xb8\x03\n" +
	"\x1aReportInsightsBatchRequest\x127\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x18\xbaH\x05r\x03\xb0\x01\x01\xa2\xab\x1e\f\n" +
	"\n" +
	"project.idR\tprojectId\x12O\n" +
	"\x0ecoauthor_stats\x18\x02 \x03(\v2\x1d.gitpod.v1.CommitCoAuthorStatB\t\xbaH\x06\x92\x01\x03\x10\x90NR\rcoauthorStats\x12@\n" +
	"\bpr_stats\x18\x03 \x03(\v2\x1a.gitpod.v1.PullRequestStatB\t\xbaH\x06\x92\x01\x03\x10\x90NR\aprStats\x12G\n" +
	"\x11collected_through\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x10collectedThrough\x12K\n" +
	"\x12collection_outcome\x18\x05 \x01(\x0e2\x1c.gitpod.v1.CollectionOutcomeR\x11collectionOutcome\x128\n" +
	"\x18collection_error_message\x18\x06 \x01(\tR\x16collectionErrorMessage\"\xe1\x01\n" +
	"\x1bReportInsightsBatchResponse\x126\n" +
	"\x17coauthor_inserted_count\x18\x01 \x01(\x03R\x15coauthorInsertedCount\x124\n" +
	"\x16coauthor_updated_count\x18\x02 \x01(\x03R\x14coauthorUpdatedCount\x12*\n" +
	"\x11pr_inserted_count\x18\x03 \x01(\x03R\x0fprInsertedCount\x12(\n" +
	"\x10pr_updated_count\x18\x04 \x01(\x03R\x0eprUpdatedCount\"c\n" +
	"\x19GetInsightsSummaryRequest\x12F\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\x1d\xbaH\x05r\x03\xb0\x01\x01\xa2\xab\x1e\x11\n" +
	"\x0forganization.idR\x0eorganizationId\"\x80\x01\n" +
	"\x1aGetInsightsSummaryResponse\x122\n" +
	"\x15enabled_project_count\x18\x01 \x01(\x03R\x13enabledProjectCount\x12.\n" +
	"\x13total_project_count\x18\x02 \x01(\x03R\x11totalProjectCount*y\n" +
	"\vScmProvider\x12\x1c\n" +
	"\x18SCM_PROVIDER_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SCM_PROVIDER_GITHUB\x10\x01\x12\x17\n" +
	"\x13SCM_PROVIDER_GITLAB\x10\x02\x12\x1a\n" +
	"\x16SCM_PROVIDER_BITBUCKET\x10\x03*\x93\x02\n" +
	"\x11CollectionOutcome\x12\"\n" +
	"\x1eCOLLECTION_OUTCOME_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCOLLECTION_OUTCOME_SUCCESS\x10\x01\x12#\n" +
	"\x1fCOLLECTION_OUTCOME_EMPTY_WINDOW\x10\x02\x12$\n" +
	" COLLECTION_OUTCOME_GIT_LOG_ERROR\x10\x03\x12%\n" +
	"!COLLECTION_OUTCOME_PR_FETCH_ERROR\x10\x04\x12\"\n" +
	"\x1eCOLLECTION_OUTCOME_SETUP_ERROR\x10\x05\x12$\n" +
	" COLLECTION_OUTCOME_UNKNOWN_ERROR\x10\x062\x99\x05\n" +
	"\x0fInsightsService\x12l\n" +
	"\x15EnableProjectInsights\x12'.gitpod.v1.EnableProjectInsightsRequest\x1a(.gitpod.v1.EnableProjectInsightsResponse\"\x00\x12o\n" +
	"\x16DisableProjectInsights\x12(.gitpod.v1.DisableProjectInsightsRequest\x1a).gitpod.v1.DisableProjectInsightsResponse\"\x00\x12x\n" +
	"\x18GetProjectInsightsStatus\x12*.gitpod.v1.GetProjectInsightsStatusRequest\x1a+.gitpod.v1.GetProjectInsightsStatusResponse\"\x03\x90\x02\x01\x12f\n" +
	"\x13ReportInsightsBatch\x12%.gitpod.v1.ReportInsightsBatchRequest\x1a&.gitpod.v1.ReportInsightsBatchResponse\"\x00\x12]\n" +
	"\x10ReportAgentTrace\x12\".gitpod.v1.ReportAgentTraceRequest\x1a#.gitpod.v1.ReportAgentTraceResponse\"\x00\x12f\n" +
	"\x12GetInsightsSummary\x12$.gitpod.v1.GetInsightsSummaryRequest\x1a%.gitpod.v1.GetInsightsSummaryResponse\"\x03\x90\x02\x01B,Z*github.com/gitpod-io/gitpod-next/api/go/v1b\x06proto3"

var (
	file_gitpod_v1_insights_proto_rawDescOnce sync.Once
	file_gitpod_v1_insights_proto_rawDescData []byte
)

func file_gitpod_v1_insights_proto_rawDescGZIP() []byte {
	file_gitpod_v1_insights_proto_rawDescOnce.Do(func() {
		file_gitpod_v1_insights_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gitpod_v1_insights_proto_rawDesc), len(file_gitpod_v1_insights_proto_rawDesc)))
	})
	return file_gitpod_v1_insights_proto_rawDescData
}

var file_gitpod_v1_insights_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_gitpod_v1_insights_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_gitpod_v1_insights_proto_goTypes = []any{
	(ScmProvider)(0),                         // 0: gitpod.v1.ScmProvider
	(CollectionOutcome)(0),                   // 1: gitpod.v1.CollectionOutcome
	(InsightsHealthIssue_Category)(0),        // 2: gitpod.v1.InsightsHealthIssue.Category
	(*CommitCoAuthorStat)(nil),               // 3: gitpod.v1.CommitCoAuthorStat
	(*EnableProjectInsightsRequest)(nil),     // 4: gitpod.v1.EnableProjectInsightsRequest
	(*EnableProjectInsightsResponse)(nil),    // 5: gitpod.v1.EnableProjectInsightsResponse
	(*InsightsHealthIssue)(nil),              // 6: gitpod.v1.InsightsHealthIssue
	(*DisableProjectInsightsRequest)(nil),    // 7: gitpod.v1.DisableProjectInsightsRequest
	(*DisableProjectInsightsResponse)(nil),   // 8: gitpod.v1.DisableProjectInsightsResponse
	(*GetProjectInsightsStatusRequest)(nil),  // 9: gitpod.v1.GetProjectInsightsStatusRequest
	(*GetProjectInsightsStatusResponse)(nil), // 10: gitpod.v1.GetProjectInsightsStatusResponse
	(*ReportAgentTraceRequest)(nil),          // 11: gitpod.v1.ReportAgentTraceRequest
	(*ReportAgentTraceResponse)(nil),         // 12: gitpod.v1.ReportAgentTraceResponse
	(*PullRequestStat)(nil),                  // 13: gitpod.v1.PullRequestStat
	(*ReportInsightsBatchRequest)(nil),       // 14: gitpod.v1.ReportInsightsBatchRequest
	(*ReportInsightsBatchResponse)(nil),      // 15: gitpod.v1.ReportInsightsBatchResponse
	(*GetInsightsSummaryRequest)(nil),        // 16: gitpod.v1.GetInsightsSummaryRequest
	(*GetInsightsSummaryResponse)(nil),       // 17: gitpod.v1.GetInsightsSummaryResponse
	nil,                                      // 18: gitpod.v1.InsightsHealthIssue.MetadataEntry
	(*timestamppb.Timestamp)(nil),            // 19: google.protobuf.Timestamp
	(CoAuthorTool)(0),                        // 20: gitpod.v1.CoAuthorTool
	(SupportedModel)(0),                      // 21: gitpod.v1.SupportedModel
}
var file_gitpod_v1_insights_proto_depIdxs = []int32{
	19, // 0: gitpod.v1.CommitCoAuthorStat.commit_date:type_name -> google.protobuf.Timestamp
	20, // 1: gitpod.v1.CommitCoAuthorStat.tool:type_name -> gitpod.v1.CoAuthorTool
	2,  // 2: gitpod.v1.InsightsHealthIssue.category:type_name -> gitpod.v1.InsightsHealthIssue.Category
	18, // 3: gitpod.v1.InsightsHealthIssue.metadata:type_name -> gitpod.v1.InsightsHealthIssue.MetadataEntry
	19, // 4: gitpod.v1.InsightsHealthIssue.detected_at:type_name -> google.protobuf.Timestamp
	19, // 5: gitpod.v1.GetProjectInsightsStatusResponse.last_ran_at:type_name -> google.protobuf.Timestamp
	6,  // 6: gitpod.v1.GetProjectInsightsStatusResponse.insights_health:type_name -> gitpod.v1.InsightsHealthIssue
	19, // 7: gitpod.v1.GetProjectInsightsStatusResponse.data_collected_through:type_name -> google.protobuf.Timestamp
	21, // 8: gitpod.v1.ReportAgentTraceRequest.model:type_name -> gitpod.v1.SupportedModel
	19, // 9: gitpod.v1.PullRequestStat.created_at:type_name -> google.protobuf.Timestamp
	19, // 10: gitpod.v1.PullRequestStat.merged_at:type_name -> google.protobuf.Timestamp
	19, // 11: gitpod.v1.PullRequestStat.first_commit_at:type_name -> google.protobuf.Timestamp
	19, // 12: gitpod.v1.PullRequestStat.first_approval_at:type_name -> google.protobuf.Timestamp
	0,  // 13: gitpod.v1.PullRequestStat.scm_provider:type_name -> gitpod.v1.ScmProvider
	3,  // 14: gitpod.v1.ReportInsightsBatchRequest.coauthor_stats:type_name -> gitpod.v1.CommitCoAuthorStat
	13, // 15: gitpod.v1.ReportInsightsBatchRequest.pr_stats:type_name -> gitpod.v1.PullRequestStat
	19, // 16: gitpod.v1.ReportInsightsBatchRequest.collected_through:type_name -> google.protobuf.Timestamp
	1,  // 17: gitpod.v1.ReportInsightsBatchRequest.collection_outcome:type_name -> gitpod.v1.CollectionOutcome
	4,  // 18: gitpod.v1.InsightsService.EnableProjectInsights:input_type -> gitpod.v1.EnableProjectInsightsRequest
	7,  // 19: gitpod.v1.InsightsService.DisableProjectInsights:input_type -> gitpod.v1.DisableProjectInsightsRequest
	9,  // 20: gitpod.v1.InsightsService.GetProjectInsightsStatus:input_type -> gitpod.v1.GetProjectInsightsStatusRequest
	14, // 21: gitpod.v1.InsightsService.ReportInsightsBatch:input_type -> gitpod.v1.ReportInsightsBatchRequest
	11, // 22: gitpod.v1.InsightsService.ReportAgentTrace:input_type -> gitpod.v1.ReportAgentTraceRequest
	16, // 23: gitpod.v1.InsightsService.GetInsightsSummary:input_type -> gitpod.v1.GetInsightsSummaryRequest
	5,  // 24: gitpod.v1.InsightsService.EnableProjectInsights:output_type -> gitpod.v1.EnableProjectInsightsResponse
	8,  // 25: gitpod.v1.InsightsService.DisableProjectInsights:output_type -> gitpod.v1.DisableProjectInsightsResponse
	10, // 26: gitpod.v1.InsightsService.GetProjectInsightsStatus:output_type -> gitpod.v1.GetProjectInsightsStatusResponse
	15, // 27: gitpod.v1.InsightsService.ReportInsightsBatch:output_type -> gitpod.v1.ReportInsightsBatchResponse
	12, // 28: gitpod.v1.InsightsService.ReportAgentTrace:output_type -> gitpod.v1.ReportAgentTraceResponse
	17, // 29: gitpod.v1.InsightsService.GetInsightsSummary:output_type -> gitpod.v1.GetInsightsSummaryResponse
	24, // [24:30] is the sub-list for method output_type
	18, // [18:24] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_gitpod_v1_insights_proto_init() }
func file_gitpod_v1_insights_proto_init() {
	if File_gitpod_v1_insights_proto != nil {
		return
	}
	file_gitpod_v1_model_proto_init()
	file_gitpod_v1_usage_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gitpod_v1_insights_proto_rawDesc), len(file_gitpod_v1_insights_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gitpod_v1_insights_proto_goTypes,
		DependencyIndexes: file_gitpod_v1_insights_proto_depIdxs,
		EnumInfos:         file_gitpod_v1_insights_proto_enumTypes,
		MessageInfos:      file_gitpod_v1_insights_proto_msgTypes,
	}.Build()
	File_gitpod_v1_insights_proto = out.File
	file_gitpod_v1_insights_proto_goTypes = nil
	file_gitpod_v1_insights_proto_depIdxs = nil
}
