// Code generated by gitpod-log-fields. DO NOT EDIT.

package v1

import (
	logfields "github.com/gitpod-io/terraform-provider-ona/internal/api/go/tools/logfields"
)

func (x *WorkflowError) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetRetry())...)
	return fields
}
