tasks:
  install-dependencies:
    name: Install dependencies
    command: make install-dependencies
    triggeredBy:
      - manual
      - prebuild

  format:
    name: Format
    command: make fmt
    dependsOn:
      - install-dependencies
    triggeredBy:
      - manual
      - prebuild

  build:
    name: Build
    command: make build
    dependsOn:
      - install-dependencies
      - lint
    triggeredBy:
      - manual
      - prebuild

  lint:
    name: Lint
    command: make lint
    dependsOn:
      - install-dependencies
      - format
    triggeredBy:
      - manual
      - prebuild

  test:
    name: Test
    command: make test
    dependsOn:
      - build
    triggeredBy:
      - manual
      - prebuild

  generate:
    name: Generate
    command: make generate
    dependsOn:
      - install-dependencies
    triggeredBy:
      - manual
      - prebuild

services:
  docs-preview:
    name: Docs preview
    commands:
      start: |
        gitpod environment port open 8808 --dont-wait --admission creator_only --name docs-preview --protocol http
        go run ./scripts/preview-docs --host 0.0.0.0 --watch docs
      ready: curl -sf http://localhost:8808
    triggeredBy:
      - manual
      - postEnvironmentStart
