// Code generated by protoc-api-adapter. DO NOT EDIT.

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	v1 "github.com/gitpod-io/terraform-provider-ona/internal/api/go/v1"
)

// AccountServiceInternal defines the internal implementation interface for AccountService.
// Implement this interface to provide custom logic for each RPC.
type AccountServiceInternal interface {
	GetAccountInternal(context.Context, *connect.Request[v1.GetAccountRequest], any) (*connect.Response[v1.GetAccountResponse], error)
	DeleteAccountInternal(context.Context, *connect.Request[v1.DeleteAccountRequest], any) (*connect.Response[v1.DeleteAccountResponse], error)
	GetSSOLoginURLInternal(context.Context, *connect.Request[v1.GetSSOLoginURLRequest], any) (*connect.Response[v1.GetSSOLoginURLResponse], error)
	ListSSOLoginsInternal(context.Context, *connect.Request[v1.ListSSOLoginsRequest], any) (*connect.Response[v1.ListSSOLoginsResponse], error)
	ListLoginProvidersInternal(context.Context, *connect.Request[v1.ListLoginProvidersRequest], any) (*connect.Response[v1.ListLoginProvidersResponse], error)
	ListJoinableOrganizationsInternal(context.Context, *connect.Request[v1.ListJoinableOrganizationsRequest], any) (*connect.Response[v1.ListJoinableOrganizationsResponse], error)
	CreateMagicLinkInternal(context.Context, *connect.Request[v1.CreateMagicLinkRequest], any) (*connect.Response[v1.CreateMagicLinkResponse], error)
	BlockAccountInternal(context.Context, *connect.Request[v1.BlockAccountRequest], any) (*connect.Response[v1.BlockAccountResponse], error)
	UnblockAccountInternal(context.Context, *connect.Request[v1.UnblockAccountRequest], any) (*connect.Response[v1.UnblockAccountResponse], error)
	GetChatIdentityTokenInternal(context.Context, *connect.Request[v1.GetChatIdentityTokenRequest], any) (*connect.Response[v1.GetChatIdentityTokenResponse], error)
}

// AccountServiceAdapter implements AccountServiceClient by wrapping an implementation and delegating to it.
type AccountServiceAdapter struct {
	AccountServiceInternal
}

// NewAccountServiceAdapter creates a new AccountServiceAdapter that wraps the given implementation.
func NewAccountServiceAdapter(impl AccountServiceInternal) *AccountServiceAdapter {
	return &AccountServiceAdapter{
		AccountServiceInternal: impl,
	}
}

// GetAccount implements AccountServiceClient.GetAccount by delegating to GetAccountInternal.
func (a *AccountServiceAdapter) GetAccount(ctx context.Context, req *connect.Request[v1.GetAccountRequest]) (*connect.Response[v1.GetAccountResponse], error) {
	return a.GetAccountInternal(ctx, req, nil)
}

// DeleteAccount implements AccountServiceClient.DeleteAccount by delegating to DeleteAccountInternal.
func (a *AccountServiceAdapter) DeleteAccount(ctx context.Context, req *connect.Request[v1.DeleteAccountRequest]) (*connect.Response[v1.DeleteAccountResponse], error) {
	return a.DeleteAccountInternal(ctx, req, nil)
}

// GetSSOLoginURL implements AccountServiceClient.GetSSOLoginURL by delegating to GetSSOLoginURLInternal.
func (a *AccountServiceAdapter) GetSSOLoginURL(ctx context.Context, req *connect.Request[v1.GetSSOLoginURLRequest]) (*connect.Response[v1.GetSSOLoginURLResponse], error) {
	return a.GetSSOLoginURLInternal(ctx, req, nil)
}

// ListSSOLogins implements AccountServiceClient.ListSSOLogins by delegating to ListSSOLoginsInternal.
func (a *AccountServiceAdapter) ListSSOLogins(ctx context.Context, req *connect.Request[v1.ListSSOLoginsRequest]) (*connect.Response[v1.ListSSOLoginsResponse], error) {
	return a.ListSSOLoginsInternal(ctx, req, nil)
}

// ListLoginProviders implements AccountServiceClient.ListLoginProviders by delegating to ListLoginProvidersInternal.
func (a *AccountServiceAdapter) ListLoginProviders(ctx context.Context, req *connect.Request[v1.ListLoginProvidersRequest]) (*connect.Response[v1.ListLoginProvidersResponse], error) {
	return a.ListLoginProvidersInternal(ctx, req, nil)
}

// ListJoinableOrganizations implements AccountServiceClient.ListJoinableOrganizations by delegating to ListJoinableOrganizationsInternal.
func (a *AccountServiceAdapter) ListJoinableOrganizations(ctx context.Context, req *connect.Request[v1.ListJoinableOrganizationsRequest]) (*connect.Response[v1.ListJoinableOrganizationsResponse], error) {
	return a.ListJoinableOrganizationsInternal(ctx, req, nil)
}

// CreateMagicLink implements AccountServiceClient.CreateMagicLink by delegating to CreateMagicLinkInternal.
func (a *AccountServiceAdapter) CreateMagicLink(ctx context.Context, req *connect.Request[v1.CreateMagicLinkRequest]) (*connect.Response[v1.CreateMagicLinkResponse], error) {
	return a.CreateMagicLinkInternal(ctx, req, nil)
}

// BlockAccount implements AccountServiceClient.BlockAccount by delegating to BlockAccountInternal.
func (a *AccountServiceAdapter) BlockAccount(ctx context.Context, req *connect.Request[v1.BlockAccountRequest]) (*connect.Response[v1.BlockAccountResponse], error) {
	return a.BlockAccountInternal(ctx, req, nil)
}

// UnblockAccount implements AccountServiceClient.UnblockAccount by delegating to UnblockAccountInternal.
func (a *AccountServiceAdapter) UnblockAccount(ctx context.Context, req *connect.Request[v1.UnblockAccountRequest]) (*connect.Response[v1.UnblockAccountResponse], error) {
	return a.UnblockAccountInternal(ctx, req, nil)
}

// GetChatIdentityToken implements AccountServiceClient.GetChatIdentityToken by delegating to GetChatIdentityTokenInternal.
func (a *AccountServiceAdapter) GetChatIdentityToken(ctx context.Context, req *connect.Request[v1.GetChatIdentityTokenRequest]) (*connect.Response[v1.GetChatIdentityTokenResponse], error) {
	return a.GetChatIdentityTokenInternal(ctx, req, nil)
}
