// Code generated by protoc-api-adapter. DO NOT EDIT.

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	v1 "github.com/gitpod-io/terraform-provider-ona/internal/api/go/v1"
)

// EnvironmentAutomationServiceInternal defines the internal implementation interface for EnvironmentAutomationService.
// Implement this interface to provide custom logic for each RPC.
type EnvironmentAutomationServiceInternal interface {
	CreateServiceInternal(context.Context, *connect.Request[v1.CreateServiceRequest], any) (*connect.Response[v1.CreateServiceResponse], error)
	GetServiceInternal(context.Context, *connect.Request[v1.GetServiceRequest], any) (*connect.Response[v1.GetServiceResponse], error)
	ListServicesInternal(context.Context, *connect.Request[v1.ListServicesRequest], any) (*connect.Response[v1.ListServicesResponse], error)
	UpdateServiceInternal(context.Context, *connect.Request[v1.UpdateServiceRequest], any) (*connect.Response[v1.UpdateServiceResponse], error)
	DeleteServiceInternal(context.Context, *connect.Request[v1.DeleteServiceRequest], any) (*connect.Response[v1.DeleteServiceResponse], error)
	StartServiceInternal(context.Context, *connect.Request[v1.StartServiceRequest], any) (*connect.Response[v1.StartServiceResponse], error)
	StopServiceInternal(context.Context, *connect.Request[v1.StopServiceRequest], any) (*connect.Response[v1.StopServiceResponse], error)
	UpsertAutomationsFileInternal(context.Context, *connect.Request[v1.UpsertAutomationsFileRequest], any) (*connect.Response[v1.UpsertAutomationsFileResponse], error)
	CreateTaskInternal(context.Context, *connect.Request[v1.CreateTaskRequest], any) (*connect.Response[v1.CreateTaskResponse], error)
	GetTaskInternal(context.Context, *connect.Request[v1.GetTaskRequest], any) (*connect.Response[v1.GetTaskResponse], error)
	ListTasksInternal(context.Context, *connect.Request[v1.ListTasksRequest], any) (*connect.Response[v1.ListTasksResponse], error)
	UpdateTaskInternal(context.Context, *connect.Request[v1.UpdateTaskRequest], any) (*connect.Response[v1.UpdateTaskResponse], error)
	DeleteTaskInternal(context.Context, *connect.Request[v1.DeleteTaskRequest], any) (*connect.Response[v1.DeleteTaskResponse], error)
	StartTaskInternal(context.Context, *connect.Request[v1.StartTaskRequest], any) (*connect.Response[v1.StartTaskResponse], error)
	ListTaskExecutionsInternal(context.Context, *connect.Request[v1.ListTaskExecutionsRequest], any) (*connect.Response[v1.ListTaskExecutionsResponse], error)
	GetTaskExecutionInternal(context.Context, *connect.Request[v1.GetTaskExecutionRequest], any) (*connect.Response[v1.GetTaskExecutionResponse], error)
	StopTaskExecutionInternal(context.Context, *connect.Request[v1.StopTaskExecutionRequest], any) (*connect.Response[v1.StopTaskExecutionResponse], error)
	UpdateTaskExecutionStatusInternal(context.Context, *connect.Request[v1.UpdateTaskExecutionStatusRequest], any) (*connect.Response[v1.UpdateTaskExecutionStatusResponse], error)
}

// EnvironmentAutomationServiceAdapter implements EnvironmentAutomationServiceClient by wrapping an implementation and delegating to it.
type EnvironmentAutomationServiceAdapter struct {
	EnvironmentAutomationServiceInternal
}

// NewEnvironmentAutomationServiceAdapter creates a new EnvironmentAutomationServiceAdapter that wraps the given implementation.
func NewEnvironmentAutomationServiceAdapter(impl EnvironmentAutomationServiceInternal) *EnvironmentAutomationServiceAdapter {
	return &EnvironmentAutomationServiceAdapter{
		EnvironmentAutomationServiceInternal: impl,
	}
}

// CreateService implements EnvironmentAutomationServiceClient.CreateService by delegating to CreateServiceInternal.
func (a *EnvironmentAutomationServiceAdapter) CreateService(ctx context.Context, req *connect.Request[v1.CreateServiceRequest]) (*connect.Response[v1.CreateServiceResponse], error) {
	return a.CreateServiceInternal(ctx, req, nil)
}

// GetService implements EnvironmentAutomationServiceClient.GetService by delegating to GetServiceInternal.
func (a *EnvironmentAutomationServiceAdapter) GetService(ctx context.Context, req *connect.Request[v1.GetServiceRequest]) (*connect.Response[v1.GetServiceResponse], error) {
	return a.GetServiceInternal(ctx, req, nil)
}

// ListServices implements EnvironmentAutomationServiceClient.ListServices by delegating to ListServicesInternal.
func (a *EnvironmentAutomationServiceAdapter) ListServices(ctx context.Context, req *connect.Request[v1.ListServicesRequest]) (*connect.Response[v1.ListServicesResponse], error) {
	return a.ListServicesInternal(ctx, req, nil)
}

// UpdateService implements EnvironmentAutomationServiceClient.UpdateService by delegating to UpdateServiceInternal.
func (a *EnvironmentAutomationServiceAdapter) UpdateService(ctx context.Context, req *connect.Request[v1.UpdateServiceRequest]) (*connect.Response[v1.UpdateServiceResponse], error) {
	return a.UpdateServiceInternal(ctx, req, nil)
}

// DeleteService implements EnvironmentAutomationServiceClient.DeleteService by delegating to DeleteServiceInternal.
func (a *EnvironmentAutomationServiceAdapter) DeleteService(ctx context.Context, req *connect.Request[v1.DeleteServiceRequest]) (*connect.Response[v1.DeleteServiceResponse], error) {
	return a.DeleteServiceInternal(ctx, req, nil)
}

// StartService implements EnvironmentAutomationServiceClient.StartService by delegating to StartServiceInternal.
func (a *EnvironmentAutomationServiceAdapter) StartService(ctx context.Context, req *connect.Request[v1.StartServiceRequest]) (*connect.Response[v1.StartServiceResponse], error) {
	return a.StartServiceInternal(ctx, req, nil)
}

// StopService implements EnvironmentAutomationServiceClient.StopService by delegating to StopServiceInternal.
func (a *EnvironmentAutomationServiceAdapter) StopService(ctx context.Context, req *connect.Request[v1.StopServiceRequest]) (*connect.Response[v1.StopServiceResponse], error) {
	return a.StopServiceInternal(ctx, req, nil)
}

// UpsertAutomationsFile implements EnvironmentAutomationServiceClient.UpsertAutomationsFile by delegating to UpsertAutomationsFileInternal.
func (a *EnvironmentAutomationServiceAdapter) UpsertAutomationsFile(ctx context.Context, req *connect.Request[v1.UpsertAutomationsFileRequest]) (*connect.Response[v1.UpsertAutomationsFileResponse], error) {
	return a.UpsertAutomationsFileInternal(ctx, req, nil)
}

// CreateTask implements EnvironmentAutomationServiceClient.CreateTask by delegating to CreateTaskInternal.
func (a *EnvironmentAutomationServiceAdapter) CreateTask(ctx context.Context, req *connect.Request[v1.CreateTaskRequest]) (*connect.Response[v1.CreateTaskResponse], error) {
	return a.CreateTaskInternal(ctx, req, nil)
}

// GetTask implements EnvironmentAutomationServiceClient.GetTask by delegating to GetTaskInternal.
func (a *EnvironmentAutomationServiceAdapter) GetTask(ctx context.Context, req *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error) {
	return a.GetTaskInternal(ctx, req, nil)
}

// ListTasks implements EnvironmentAutomationServiceClient.ListTasks by delegating to ListTasksInternal.
func (a *EnvironmentAutomationServiceAdapter) ListTasks(ctx context.Context, req *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error) {
	return a.ListTasksInternal(ctx, req, nil)
}

// UpdateTask implements EnvironmentAutomationServiceClient.UpdateTask by delegating to UpdateTaskInternal.
func (a *EnvironmentAutomationServiceAdapter) UpdateTask(ctx context.Context, req *connect.Request[v1.UpdateTaskRequest]) (*connect.Response[v1.UpdateTaskResponse], error) {
	return a.UpdateTaskInternal(ctx, req, nil)
}

// DeleteTask implements EnvironmentAutomationServiceClient.DeleteTask by delegating to DeleteTaskInternal.
func (a *EnvironmentAutomationServiceAdapter) DeleteTask(ctx context.Context, req *connect.Request[v1.DeleteTaskRequest]) (*connect.Response[v1.DeleteTaskResponse], error) {
	return a.DeleteTaskInternal(ctx, req, nil)
}

// StartTask implements EnvironmentAutomationServiceClient.StartTask by delegating to StartTaskInternal.
func (a *EnvironmentAutomationServiceAdapter) StartTask(ctx context.Context, req *connect.Request[v1.StartTaskRequest]) (*connect.Response[v1.StartTaskResponse], error) {
	return a.StartTaskInternal(ctx, req, nil)
}

// ListTaskExecutions implements EnvironmentAutomationServiceClient.ListTaskExecutions by delegating to ListTaskExecutionsInternal.
func (a *EnvironmentAutomationServiceAdapter) ListTaskExecutions(ctx context.Context, req *connect.Request[v1.ListTaskExecutionsRequest]) (*connect.Response[v1.ListTaskExecutionsResponse], error) {
	return a.ListTaskExecutionsInternal(ctx, req, nil)
}

// GetTaskExecution implements EnvironmentAutomationServiceClient.GetTaskExecution by delegating to GetTaskExecutionInternal.
func (a *EnvironmentAutomationServiceAdapter) GetTaskExecution(ctx context.Context, req *connect.Request[v1.GetTaskExecutionRequest]) (*connect.Response[v1.GetTaskExecutionResponse], error) {
	return a.GetTaskExecutionInternal(ctx, req, nil)
}

// StopTaskExecution implements EnvironmentAutomationServiceClient.StopTaskExecution by delegating to StopTaskExecutionInternal.
func (a *EnvironmentAutomationServiceAdapter) StopTaskExecution(ctx context.Context, req *connect.Request[v1.StopTaskExecutionRequest]) (*connect.Response[v1.StopTaskExecutionResponse], error) {
	return a.StopTaskExecutionInternal(ctx, req, nil)
}

// UpdateTaskExecutionStatus implements EnvironmentAutomationServiceClient.UpdateTaskExecutionStatus by delegating to UpdateTaskExecutionStatusInternal.
func (a *EnvironmentAutomationServiceAdapter) UpdateTaskExecutionStatus(ctx context.Context, req *connect.Request[v1.UpdateTaskExecutionStatusRequest]) (*connect.Response[v1.UpdateTaskExecutionStatusResponse], error) {
	return a.UpdateTaskExecutionStatusInternal(ctx, req, nil)
}
