// Code generated by protoc-api-adapter. DO NOT EDIT.

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	v1 "github.com/gitpod-io/terraform-provider-ona/internal/api/go/v1"
)

// OnaIntelligenceServiceInternal defines the internal implementation interface for OnaIntelligenceService.
// Implement this interface to provide custom logic for each RPC.
type OnaIntelligenceServiceInternal interface {
	CreateOrganizationLLMConfigurationInternal(context.Context, *connect.Request[v1.CreateOrganizationLLMConfigurationRequest], any) (*connect.Response[v1.CreateOrganizationLLMConfigurationResponse], error)
	UpdateOrganizationLLMConfigurationInternal(context.Context, *connect.Request[v1.UpdateOrganizationLLMConfigurationRequest], any) (*connect.Response[v1.UpdateOrganizationLLMConfigurationResponse], error)
	GetOrganizationLLMConfigurationInternal(context.Context, *connect.Request[v1.GetOrganizationLLMConfigurationRequest], any) (*connect.Response[v1.GetOrganizationLLMConfigurationResponse], error)
	ListOrganizationLLMConfigurationsInternal(context.Context, *connect.Request[v1.ListOrganizationLLMConfigurationsRequest], any) (*connect.Response[v1.ListOrganizationLLMConfigurationsResponse], error)
	DeleteOrganizationLLMConfigurationInternal(context.Context, *connect.Request[v1.DeleteOrganizationLLMConfigurationRequest], any) (*connect.Response[v1.DeleteOrganizationLLMConfigurationResponse], error)
}

// OnaIntelligenceServiceAdapter implements OnaIntelligenceServiceClient by wrapping an implementation and delegating to it.
type OnaIntelligenceServiceAdapter struct {
	OnaIntelligenceServiceInternal
}

// NewOnaIntelligenceServiceAdapter creates a new OnaIntelligenceServiceAdapter that wraps the given implementation.
func NewOnaIntelligenceServiceAdapter(impl OnaIntelligenceServiceInternal) *OnaIntelligenceServiceAdapter {
	return &OnaIntelligenceServiceAdapter{
		OnaIntelligenceServiceInternal: impl,
	}
}

// CreateOrganizationLLMConfiguration implements OnaIntelligenceServiceClient.CreateOrganizationLLMConfiguration by delegating to CreateOrganizationLLMConfigurationInternal.
func (a *OnaIntelligenceServiceAdapter) CreateOrganizationLLMConfiguration(ctx context.Context, req *connect.Request[v1.CreateOrganizationLLMConfigurationRequest]) (*connect.Response[v1.CreateOrganizationLLMConfigurationResponse], error) {
	return a.CreateOrganizationLLMConfigurationInternal(ctx, req, nil)
}

// UpdateOrganizationLLMConfiguration implements OnaIntelligenceServiceClient.UpdateOrganizationLLMConfiguration by delegating to UpdateOrganizationLLMConfigurationInternal.
func (a *OnaIntelligenceServiceAdapter) UpdateOrganizationLLMConfiguration(ctx context.Context, req *connect.Request[v1.UpdateOrganizationLLMConfigurationRequest]) (*connect.Response[v1.UpdateOrganizationLLMConfigurationResponse], error) {
	return a.UpdateOrganizationLLMConfigurationInternal(ctx, req, nil)
}

// GetOrganizationLLMConfiguration implements OnaIntelligenceServiceClient.GetOrganizationLLMConfiguration by delegating to GetOrganizationLLMConfigurationInternal.
func (a *OnaIntelligenceServiceAdapter) GetOrganizationLLMConfiguration(ctx context.Context, req *connect.Request[v1.GetOrganizationLLMConfigurationRequest]) (*connect.Response[v1.GetOrganizationLLMConfigurationResponse], error) {
	return a.GetOrganizationLLMConfigurationInternal(ctx, req, nil)
}

// ListOrganizationLLMConfigurations implements OnaIntelligenceServiceClient.ListOrganizationLLMConfigurations by delegating to ListOrganizationLLMConfigurationsInternal.
func (a *OnaIntelligenceServiceAdapter) ListOrganizationLLMConfigurations(ctx context.Context, req *connect.Request[v1.ListOrganizationLLMConfigurationsRequest]) (*connect.Response[v1.ListOrganizationLLMConfigurationsResponse], error) {
	return a.ListOrganizationLLMConfigurationsInternal(ctx, req, nil)
}

// DeleteOrganizationLLMConfiguration implements OnaIntelligenceServiceClient.DeleteOrganizationLLMConfiguration by delegating to DeleteOrganizationLLMConfigurationInternal.
func (a *OnaIntelligenceServiceAdapter) DeleteOrganizationLLMConfiguration(ctx context.Context, req *connect.Request[v1.DeleteOrganizationLLMConfigurationRequest]) (*connect.Response[v1.DeleteOrganizationLLMConfigurationResponse], error) {
	return a.DeleteOrganizationLLMConfigurationInternal(ctx, req, nil)
}
