// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: gitpod/v1/prebuild.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/gitpod-io/terraform-provider-ona/internal/api/go/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PrebuildServiceName is the fully-qualified name of the PrebuildService service.
	PrebuildServiceName = "gitpod.v1.PrebuildService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PrebuildServiceCreatePrebuildProcedure is the fully-qualified name of the PrebuildService's
	// CreatePrebuild RPC.
	PrebuildServiceCreatePrebuildProcedure = "/gitpod.v1.PrebuildService/CreatePrebuild"
	// PrebuildServiceListPrebuildsProcedure is the fully-qualified name of the PrebuildService's
	// ListPrebuilds RPC.
	PrebuildServiceListPrebuildsProcedure = "/gitpod.v1.PrebuildService/ListPrebuilds"
	// PrebuildServiceGetPrebuildProcedure is the fully-qualified name of the PrebuildService's
	// GetPrebuild RPC.
	PrebuildServiceGetPrebuildProcedure = "/gitpod.v1.PrebuildService/GetPrebuild"
	// PrebuildServiceCancelPrebuildProcedure is the fully-qualified name of the PrebuildService's
	// CancelPrebuild RPC.
	PrebuildServiceCancelPrebuildProcedure = "/gitpod.v1.PrebuildService/CancelPrebuild"
	// PrebuildServiceDeletePrebuildProcedure is the fully-qualified name of the PrebuildService's
	// DeletePrebuild RPC.
	PrebuildServiceDeletePrebuildProcedure = "/gitpod.v1.PrebuildService/DeletePrebuild"
	// PrebuildServiceCreatePrebuildLogsTokenProcedure is the fully-qualified name of the
	// PrebuildService's CreatePrebuildLogsToken RPC.
	PrebuildServiceCreatePrebuildLogsTokenProcedure = "/gitpod.v1.PrebuildService/CreatePrebuildLogsToken"
	// PrebuildServiceCreateWarmPoolProcedure is the fully-qualified name of the PrebuildService's
	// CreateWarmPool RPC.
	PrebuildServiceCreateWarmPoolProcedure = "/gitpod.v1.PrebuildService/CreateWarmPool"
	// PrebuildServiceGetWarmPoolProcedure is the fully-qualified name of the PrebuildService's
	// GetWarmPool RPC.
	PrebuildServiceGetWarmPoolProcedure = "/gitpod.v1.PrebuildService/GetWarmPool"
	// PrebuildServiceListWarmPoolsProcedure is the fully-qualified name of the PrebuildService's
	// ListWarmPools RPC.
	PrebuildServiceListWarmPoolsProcedure = "/gitpod.v1.PrebuildService/ListWarmPools"
	// PrebuildServiceUpdateWarmPoolProcedure is the fully-qualified name of the PrebuildService's
	// UpdateWarmPool RPC.
	PrebuildServiceUpdateWarmPoolProcedure = "/gitpod.v1.PrebuildService/UpdateWarmPool"
	// PrebuildServiceDeleteWarmPoolProcedure is the fully-qualified name of the PrebuildService's
	// DeleteWarmPool RPC.
	PrebuildServiceDeleteWarmPoolProcedure = "/gitpod.v1.PrebuildService/DeleteWarmPool"
)

// PrebuildServiceClient is a client for the gitpod.v1.PrebuildService service.
type PrebuildServiceClient interface {
	// Creates a prebuild for a project.
	//
	// Use this method to:
	// - Create on-demand prebuilds for faster environment startup
	// - Trigger prebuilds after repository changes
	// - Generate prebuilds for specific environment classes
	//
	// The prebuild process creates an environment, runs the devcontainer prebuild lifecycle,
	// and creates a snapshot for future environment provisioning.
	//
	// ### Examples
	//
	// - Create basic prebuild:
	//
	//	Creates a prebuild for a project using default settings.
	//
	//	```yaml
	//	projectId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	spec:
	//	  timeout: "3600s"  # 60 minutes default
	//	```
	//
	// - Create prebuild with custom environment class:
	//
	//	Creates a prebuild with a specific environment class and timeout.
	//
	//	```yaml
	//	projectId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	environmentClassId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	spec:
	//	  timeout: "3600s"  # 1 hour
	//	```
	CreatePrebuild(context.Context, *connect.Request[v1.CreatePrebuildRequest]) (*connect.Response[v1.CreatePrebuildResponse], error)
	ListPrebuilds(context.Context, *connect.Request[v1.ListPrebuildsRequest]) (*connect.Response[v1.ListPrebuildsResponse], error)
	// Gets details about a specific prebuild.
	//
	// Use this method to:
	// - Check prebuild status and progress
	// - Access prebuild logs for debugging
	//
	// ### Examples
	//
	// - Get prebuild details:
	//
	//	Retrieves comprehensive information about a prebuild.
	//
	//	```yaml
	//	prebuildId: "07e03a28-65a5-4d98-b532-8ea67b188048"
	//	```
	GetPrebuild(context.Context, *connect.Request[v1.GetPrebuildRequest]) (*connect.Response[v1.GetPrebuildResponse], error)
	// Cancels a running prebuild.
	//
	// Use this method to:
	// - Stop prebuilds that are no longer needed
	// - Free up resources for other operations
	//
	// ### Examples
	//
	// - Cancel prebuild:
	//
	//	Stops a running prebuild and cleans up resources.
	//
	//	```yaml
	//	prebuildId: "07e03a28-65a5-4d98-b532-8ea67b188048"
	//	```
	CancelPrebuild(context.Context, *connect.Request[v1.CancelPrebuildRequest]) (*connect.Response[v1.CancelPrebuildResponse], error)
	// Deletes a prebuild.
	//
	// Prebuilds are automatically deleted after some time. Use this method to
	// manually delete a prebuild before automatic cleanup, for example to remove
	// a prebuild that should no longer be used.
	//
	// Deletion is processed asynchronously. The prebuild will be marked for deletion
	// and removed from the system in the background.
	//
	// ### Examples
	//
	// - Delete prebuild:
	//
	//	Marks a prebuild for deletion and removes it from the system.
	//
	//	```yaml
	//	prebuildId: "07e03a28-65a5-4d98-b532-8ea67b188048"
	//	```
	DeletePrebuild(context.Context, *connect.Request[v1.DeletePrebuildRequest]) (*connect.Response[v1.DeletePrebuildResponse], error)
	// Creates a logs access token for a prebuild.
	//
	// Use this method to:
	// - Stream logs from a running prebuild
	// - Access archived logs from completed prebuilds
	//
	// Generated tokens are valid for one hour.
	//
	// ### Examples
	//
	// - Create prebuild logs token:
	//
	//	Generates a token for accessing prebuild logs.
	//
	//	```yaml
	//	prebuildId: "07e03a28-65a5-4d98-b532-8ea67b188048"
	//	```
	CreatePrebuildLogsToken(context.Context, *connect.Request[v1.CreatePrebuildLogsTokenRequest]) (*connect.Response[v1.CreatePrebuildLogsTokenResponse], error)
	// Creates a warm pool for a project and environment class.
	//
	// A warm pool maintains pre-created environment instances from a prebuild snapshot
	// so that new environments can start near-instantly.
	//
	// Only one warm pool is allowed per <project, environment_class> pair.
	// The environment class must have prebuilds enabled on the project.
	//
	// The pool's snapshot is managed automatically: when a new prebuild completes
	// for the same project and environment class, the pool's snapshot is updated
	// and the runner rotates instances.
	//
	// ### Examples
	//
	// - Create warm pool:
	//
	//	Creates a warm pool with 2 instances for a project and environment class.
	//
	//	```yaml
	//	projectId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	environmentClassId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	desiredSize: 2
	//	```
	CreateWarmPool(context.Context, *connect.Request[v1.CreateWarmPoolRequest]) (*connect.Response[v1.CreateWarmPoolResponse], error)
	// Gets details about a specific warm pool.
	//
	// Use this method to:
	// - Check warm pool status and phase
	// - View the current snapshot being warmed
	// - Monitor pool health
	//
	// ### Examples
	//
	// - Get warm pool:
	//
	//	```yaml
	//	warmPoolId: "a1b2c3d4-5678-9abc-def0-1234567890ab"
	//	```
	GetWarmPool(context.Context, *connect.Request[v1.GetWarmPoolRequest]) (*connect.Response[v1.GetWarmPoolResponse], error)
	// Lists warm pools with optional filtering.
	//
	// Use this method to:
	// - View all warm pools for a project
	// - Monitor warm pool status across environment classes
	//
	// ### Examples
	//
	// - List warm pools for a project:
	//
	//	```yaml
	//	filter:
	//	  projectIds: ["b0e12f6c-4c67-429d-a4a6-d9838b5da047"]
	//	```
	ListWarmPools(context.Context, *connect.Request[v1.ListWarmPoolsRequest]) (*connect.Response[v1.ListWarmPoolsResponse], error)
	// Updates a warm pool's configuration.
	//
	// Use this method to change the desired pool size.
	//
	// ### Examples
	//
	// - Update pool size:
	//
	//	```yaml
	//	warmPoolId: "a1b2c3d4-5678-9abc-def0-1234567890ab"
	//	desiredSize: 5
	//	```
	UpdateWarmPool(context.Context, *connect.Request[v1.UpdateWarmPoolRequest]) (*connect.Response[v1.UpdateWarmPoolResponse], error)
	// Deletes a warm pool.
	//
	// Deletion is processed asynchronously. The pool is marked for deletion
	// and the runner drains instances in the background.
	//
	// Warm pools are also automatically deleted when prebuilds are disabled
	// on the project or the environment class is removed from the prebuild
	// configuration.
	//
	// ### Examples
	//
	// - Delete warm pool:
	//
	//	```yaml
	//	warmPoolId: "a1b2c3d4-5678-9abc-def0-1234567890ab"
	//	```
	DeleteWarmPool(context.Context, *connect.Request[v1.DeleteWarmPoolRequest]) (*connect.Response[v1.DeleteWarmPoolResponse], error)
}

// NewPrebuildServiceClient constructs a client for the gitpod.v1.PrebuildService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPrebuildServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PrebuildServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	prebuildServiceMethods := v1.File_gitpod_v1_prebuild_proto.Services().ByName("PrebuildService").Methods()
	return &prebuildServiceClient{
		createPrebuild: connect.NewClient[v1.CreatePrebuildRequest, v1.CreatePrebuildResponse](
			httpClient,
			baseURL+PrebuildServiceCreatePrebuildProcedure,
			connect.WithSchema(prebuildServiceMethods.ByName("CreatePrebuild")),
			connect.WithClientOptions(opts...),
		),
		listPrebuilds: connect.NewClient[v1.ListPrebuildsRequest, v1.ListPrebuildsResponse](
			httpClient,
			baseURL+PrebuildServiceListPrebuildsProcedure,
			connect.WithSchema(prebuildServiceMethods.ByName("ListPrebuilds")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getPrebuild: connect.NewClient[v1.GetPrebuildRequest, v1.GetPrebuildResponse](
			httpClient,
			baseURL+PrebuildServiceGetPrebuildProcedure,
			connect.WithSchema(prebuildServiceMethods.ByName("GetPrebuild")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		cancelPrebuild: connect.NewClient[v1.CancelPrebuildRequest, v1.CancelPrebuildResponse](
			httpClient,
			baseURL+PrebuildServiceCancelPrebuildProcedure,
			connect.WithSchema(prebuildServiceMethods.ByName("CancelPrebuild")),
			connect.WithClientOptions(opts...),
		),
		deletePrebuild: connect.NewClient[v1.DeletePrebuildRequest, v1.DeletePrebuildResponse](
			httpClient,
			baseURL+PrebuildServiceDeletePrebuildProcedure,
			connect.WithSchema(prebuildServiceMethods.ByName("DeletePrebuild")),
			connect.WithClientOptions(opts...),
		),
		createPrebuildLogsToken: connect.NewClient[v1.CreatePrebuildLogsTokenRequest, v1.CreatePrebuildLogsTokenResponse](
			httpClient,
			baseURL+PrebuildServiceCreatePrebuildLogsTokenProcedure,
			connect.WithSchema(prebuildServiceMethods.ByName("CreatePrebuildLogsToken")),
			connect.WithClientOptions(opts...),
		),
		createWarmPool: connect.NewClient[v1.CreateWarmPoolRequest, v1.CreateWarmPoolResponse](
			httpClient,
			baseURL+PrebuildServiceCreateWarmPoolProcedure,
			connect.WithSchema(prebuildServiceMethods.ByName("CreateWarmPool")),
			connect.WithClientOptions(opts...),
		),
		getWarmPool: connect.NewClient[v1.GetWarmPoolRequest, v1.GetWarmPoolResponse](
			httpClient,
			baseURL+PrebuildServiceGetWarmPoolProcedure,
			connect.WithSchema(prebuildServiceMethods.ByName("GetWarmPool")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listWarmPools: connect.NewClient[v1.ListWarmPoolsRequest, v1.ListWarmPoolsResponse](
			httpClient,
			baseURL+PrebuildServiceListWarmPoolsProcedure,
			connect.WithSchema(prebuildServiceMethods.ByName("ListWarmPools")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updateWarmPool: connect.NewClient[v1.UpdateWarmPoolRequest, v1.UpdateWarmPoolResponse](
			httpClient,
			baseURL+PrebuildServiceUpdateWarmPoolProcedure,
			connect.WithSchema(prebuildServiceMethods.ByName("UpdateWarmPool")),
			connect.WithClientOptions(opts...),
		),
		deleteWarmPool: connect.NewClient[v1.DeleteWarmPoolRequest, v1.DeleteWarmPoolResponse](
			httpClient,
			baseURL+PrebuildServiceDeleteWarmPoolProcedure,
			connect.WithSchema(prebuildServiceMethods.ByName("DeleteWarmPool")),
			connect.WithClientOptions(opts...),
		),
	}
}

// prebuildServiceClient implements PrebuildServiceClient.
type prebuildServiceClient struct {
	createPrebuild          *connect.Client[v1.CreatePrebuildRequest, v1.CreatePrebuildResponse]
	listPrebuilds           *connect.Client[v1.ListPrebuildsRequest, v1.ListPrebuildsResponse]
	getPrebuild             *connect.Client[v1.GetPrebuildRequest, v1.GetPrebuildResponse]
	cancelPrebuild          *connect.Client[v1.CancelPrebuildRequest, v1.CancelPrebuildResponse]
	deletePrebuild          *connect.Client[v1.DeletePrebuildRequest, v1.DeletePrebuildResponse]
	createPrebuildLogsToken *connect.Client[v1.CreatePrebuildLogsTokenRequest, v1.CreatePrebuildLogsTokenResponse]
	createWarmPool          *connect.Client[v1.CreateWarmPoolRequest, v1.CreateWarmPoolResponse]
	getWarmPool             *connect.Client[v1.GetWarmPoolRequest, v1.GetWarmPoolResponse]
	listWarmPools           *connect.Client[v1.ListWarmPoolsRequest, v1.ListWarmPoolsResponse]
	updateWarmPool          *connect.Client[v1.UpdateWarmPoolRequest, v1.UpdateWarmPoolResponse]
	deleteWarmPool          *connect.Client[v1.DeleteWarmPoolRequest, v1.DeleteWarmPoolResponse]
}

// CreatePrebuild calls gitpod.v1.PrebuildService.CreatePrebuild.
func (c *prebuildServiceClient) CreatePrebuild(ctx context.Context, req *connect.Request[v1.CreatePrebuildRequest]) (*connect.Response[v1.CreatePrebuildResponse], error) {
	return c.createPrebuild.CallUnary(ctx, req)
}

// ListPrebuilds calls gitpod.v1.PrebuildService.ListPrebuilds.
func (c *prebuildServiceClient) ListPrebuilds(ctx context.Context, req *connect.Request[v1.ListPrebuildsRequest]) (*connect.Response[v1.ListPrebuildsResponse], error) {
	return c.listPrebuilds.CallUnary(ctx, req)
}

// GetPrebuild calls gitpod.v1.PrebuildService.GetPrebuild.
func (c *prebuildServiceClient) GetPrebuild(ctx context.Context, req *connect.Request[v1.GetPrebuildRequest]) (*connect.Response[v1.GetPrebuildResponse], error) {
	return c.getPrebuild.CallUnary(ctx, req)
}

// CancelPrebuild calls gitpod.v1.PrebuildService.CancelPrebuild.
func (c *prebuildServiceClient) CancelPrebuild(ctx context.Context, req *connect.Request[v1.CancelPrebuildRequest]) (*connect.Response[v1.CancelPrebuildResponse], error) {
	return c.cancelPrebuild.CallUnary(ctx, req)
}

// DeletePrebuild calls gitpod.v1.PrebuildService.DeletePrebuild.
func (c *prebuildServiceClient) DeletePrebuild(ctx context.Context, req *connect.Request[v1.DeletePrebuildRequest]) (*connect.Response[v1.DeletePrebuildResponse], error) {
	return c.deletePrebuild.CallUnary(ctx, req)
}

// CreatePrebuildLogsToken calls gitpod.v1.PrebuildService.CreatePrebuildLogsToken.
func (c *prebuildServiceClient) CreatePrebuildLogsToken(ctx context.Context, req *connect.Request[v1.CreatePrebuildLogsTokenRequest]) (*connect.Response[v1.CreatePrebuildLogsTokenResponse], error) {
	return c.createPrebuildLogsToken.CallUnary(ctx, req)
}

// CreateWarmPool calls gitpod.v1.PrebuildService.CreateWarmPool.
func (c *prebuildServiceClient) CreateWarmPool(ctx context.Context, req *connect.Request[v1.CreateWarmPoolRequest]) (*connect.Response[v1.CreateWarmPoolResponse], error) {
	return c.createWarmPool.CallUnary(ctx, req)
}

// GetWarmPool calls gitpod.v1.PrebuildService.GetWarmPool.
func (c *prebuildServiceClient) GetWarmPool(ctx context.Context, req *connect.Request[v1.GetWarmPoolRequest]) (*connect.Response[v1.GetWarmPoolResponse], error) {
	return c.getWarmPool.CallUnary(ctx, req)
}

// ListWarmPools calls gitpod.v1.PrebuildService.ListWarmPools.
func (c *prebuildServiceClient) ListWarmPools(ctx context.Context, req *connect.Request[v1.ListWarmPoolsRequest]) (*connect.Response[v1.ListWarmPoolsResponse], error) {
	return c.listWarmPools.CallUnary(ctx, req)
}

// UpdateWarmPool calls gitpod.v1.PrebuildService.UpdateWarmPool.
func (c *prebuildServiceClient) UpdateWarmPool(ctx context.Context, req *connect.Request[v1.UpdateWarmPoolRequest]) (*connect.Response[v1.UpdateWarmPoolResponse], error) {
	return c.updateWarmPool.CallUnary(ctx, req)
}

// DeleteWarmPool calls gitpod.v1.PrebuildService.DeleteWarmPool.
func (c *prebuildServiceClient) DeleteWarmPool(ctx context.Context, req *connect.Request[v1.DeleteWarmPoolRequest]) (*connect.Response[v1.DeleteWarmPoolResponse], error) {
	return c.deleteWarmPool.CallUnary(ctx, req)
}

// PrebuildServiceHandler is an implementation of the gitpod.v1.PrebuildService service.
type PrebuildServiceHandler interface {
	// Creates a prebuild for a project.
	//
	// Use this method to:
	// - Create on-demand prebuilds for faster environment startup
	// - Trigger prebuilds after repository changes
	// - Generate prebuilds for specific environment classes
	//
	// The prebuild process creates an environment, runs the devcontainer prebuild lifecycle,
	// and creates a snapshot for future environment provisioning.
	//
	// ### Examples
	//
	// - Create basic prebuild:
	//
	//	Creates a prebuild for a project using default settings.
	//
	//	```yaml
	//	projectId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	spec:
	//	  timeout: "3600s"  # 60 minutes default
	//	```
	//
	// - Create prebuild with custom environment class:
	//
	//	Creates a prebuild with a specific environment class and timeout.
	//
	//	```yaml
	//	projectId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	environmentClassId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	spec:
	//	  timeout: "3600s"  # 1 hour
	//	```
	CreatePrebuild(context.Context, *connect.Request[v1.CreatePrebuildRequest]) (*connect.Response[v1.CreatePrebuildResponse], error)
	ListPrebuilds(context.Context, *connect.Request[v1.ListPrebuildsRequest]) (*connect.Response[v1.ListPrebuildsResponse], error)
	// Gets details about a specific prebuild.
	//
	// Use this method to:
	// - Check prebuild status and progress
	// - Access prebuild logs for debugging
	//
	// ### Examples
	//
	// - Get prebuild details:
	//
	//	Retrieves comprehensive information about a prebuild.
	//
	//	```yaml
	//	prebuildId: "07e03a28-65a5-4d98-b532-8ea67b188048"
	//	```
	GetPrebuild(context.Context, *connect.Request[v1.GetPrebuildRequest]) (*connect.Response[v1.GetPrebuildResponse], error)
	// Cancels a running prebuild.
	//
	// Use this method to:
	// - Stop prebuilds that are no longer needed
	// - Free up resources for other operations
	//
	// ### Examples
	//
	// - Cancel prebuild:
	//
	//	Stops a running prebuild and cleans up resources.
	//
	//	```yaml
	//	prebuildId: "07e03a28-65a5-4d98-b532-8ea67b188048"
	//	```
	CancelPrebuild(context.Context, *connect.Request[v1.CancelPrebuildRequest]) (*connect.Response[v1.CancelPrebuildResponse], error)
	// Deletes a prebuild.
	//
	// Prebuilds are automatically deleted after some time. Use this method to
	// manually delete a prebuild before automatic cleanup, for example to remove
	// a prebuild that should no longer be used.
	//
	// Deletion is processed asynchronously. The prebuild will be marked for deletion
	// and removed from the system in the background.
	//
	// ### Examples
	//
	// - Delete prebuild:
	//
	//	Marks a prebuild for deletion and removes it from the system.
	//
	//	```yaml
	//	prebuildId: "07e03a28-65a5-4d98-b532-8ea67b188048"
	//	```
	DeletePrebuild(context.Context, *connect.Request[v1.DeletePrebuildRequest]) (*connect.Response[v1.DeletePrebuildResponse], error)
	// Creates a logs access token for a prebuild.
	//
	// Use this method to:
	// - Stream logs from a running prebuild
	// - Access archived logs from completed prebuilds
	//
	// Generated tokens are valid for one hour.
	//
	// ### Examples
	//
	// - Create prebuild logs token:
	//
	//	Generates a token for accessing prebuild logs.
	//
	//	```yaml
	//	prebuildId: "07e03a28-65a5-4d98-b532-8ea67b188048"
	//	```
	CreatePrebuildLogsToken(context.Context, *connect.Request[v1.CreatePrebuildLogsTokenRequest]) (*connect.Response[v1.CreatePrebuildLogsTokenResponse], error)
	// Creates a warm pool for a project and environment class.
	//
	// A warm pool maintains pre-created environment instances from a prebuild snapshot
	// so that new environments can start near-instantly.
	//
	// Only one warm pool is allowed per <project, environment_class> pair.
	// The environment class must have prebuilds enabled on the project.
	//
	// The pool's snapshot is managed automatically: when a new prebuild completes
	// for the same project and environment class, the pool's snapshot is updated
	// and the runner rotates instances.
	//
	// ### Examples
	//
	// - Create warm pool:
	//
	//	Creates a warm pool with 2 instances for a project and environment class.
	//
	//	```yaml
	//	projectId: "b0e12f6c-4c67-429d-a4a6-d9838b5da047"
	//	environmentClassId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	desiredSize: 2
	//	```
	CreateWarmPool(context.Context, *connect.Request[v1.CreateWarmPoolRequest]) (*connect.Response[v1.CreateWarmPoolResponse], error)
	// Gets details about a specific warm pool.
	//
	// Use this method to:
	// - Check warm pool status and phase
	// - View the current snapshot being warmed
	// - Monitor pool health
	//
	// ### Examples
	//
	// - Get warm pool:
	//
	//	```yaml
	//	warmPoolId: "a1b2c3d4-5678-9abc-def0-1234567890ab"
	//	```
	GetWarmPool(context.Context, *connect.Request[v1.GetWarmPoolRequest]) (*connect.Response[v1.GetWarmPoolResponse], error)
	// Lists warm pools with optional filtering.
	//
	// Use this method to:
	// - View all warm pools for a project
	// - Monitor warm pool status across environment classes
	//
	// ### Examples
	//
	// - List warm pools for a project:
	//
	//	```yaml
	//	filter:
	//	  projectIds: ["b0e12f6c-4c67-429d-a4a6-d9838b5da047"]
	//	```
	ListWarmPools(context.Context, *connect.Request[v1.ListWarmPoolsRequest]) (*connect.Response[v1.ListWarmPoolsResponse], error)
	// Updates a warm pool's configuration.
	//
	// Use this method to change the desired pool size.
	//
	// ### Examples
	//
	// - Update pool size:
	//
	//	```yaml
	//	warmPoolId: "a1b2c3d4-5678-9abc-def0-1234567890ab"
	//	desiredSize: 5
	//	```
	UpdateWarmPool(context.Context, *connect.Request[v1.UpdateWarmPoolRequest]) (*connect.Response[v1.UpdateWarmPoolResponse], error)
	// Deletes a warm pool.
	//
	// Deletion is processed asynchronously. The pool is marked for deletion
	// and the runner drains instances in the background.
	//
	// Warm pools are also automatically deleted when prebuilds are disabled
	// on the project or the environment class is removed from the prebuild
	// configuration.
	//
	// ### Examples
	//
	// - Delete warm pool:
	//
	//	```yaml
	//	warmPoolId: "a1b2c3d4-5678-9abc-def0-1234567890ab"
	//	```
	DeleteWarmPool(context.Context, *connect.Request[v1.DeleteWarmPoolRequest]) (*connect.Response[v1.DeleteWarmPoolResponse], error)
}

// NewPrebuildServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPrebuildServiceHandler(svc PrebuildServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	prebuildServiceMethods := v1.File_gitpod_v1_prebuild_proto.Services().ByName("PrebuildService").Methods()
	prebuildServiceCreatePrebuildHandler := connect.NewUnaryHandler(
		PrebuildServiceCreatePrebuildProcedure,
		svc.CreatePrebuild,
		connect.WithSchema(prebuildServiceMethods.ByName("CreatePrebuild")),
		connect.WithHandlerOptions(opts...),
	)
	prebuildServiceListPrebuildsHandler := connect.NewUnaryHandler(
		PrebuildServiceListPrebuildsProcedure,
		svc.ListPrebuilds,
		connect.WithSchema(prebuildServiceMethods.ByName("ListPrebuilds")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	prebuildServiceGetPrebuildHandler := connect.NewUnaryHandler(
		PrebuildServiceGetPrebuildProcedure,
		svc.GetPrebuild,
		connect.WithSchema(prebuildServiceMethods.ByName("GetPrebuild")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	prebuildServiceCancelPrebuildHandler := connect.NewUnaryHandler(
		PrebuildServiceCancelPrebuildProcedure,
		svc.CancelPrebuild,
		connect.WithSchema(prebuildServiceMethods.ByName("CancelPrebuild")),
		connect.WithHandlerOptions(opts...),
	)
	prebuildServiceDeletePrebuildHandler := connect.NewUnaryHandler(
		PrebuildServiceDeletePrebuildProcedure,
		svc.DeletePrebuild,
		connect.WithSchema(prebuildServiceMethods.ByName("DeletePrebuild")),
		connect.WithHandlerOptions(opts...),
	)
	prebuildServiceCreatePrebuildLogsTokenHandler := connect.NewUnaryHandler(
		PrebuildServiceCreatePrebuildLogsTokenProcedure,
		svc.CreatePrebuildLogsToken,
		connect.WithSchema(prebuildServiceMethods.ByName("CreatePrebuildLogsToken")),
		connect.WithHandlerOptions(opts...),
	)
	prebuildServiceCreateWarmPoolHandler := connect.NewUnaryHandler(
		PrebuildServiceCreateWarmPoolProcedure,
		svc.CreateWarmPool,
		connect.WithSchema(prebuildServiceMethods.ByName("CreateWarmPool")),
		connect.WithHandlerOptions(opts...),
	)
	prebuildServiceGetWarmPoolHandler := connect.NewUnaryHandler(
		PrebuildServiceGetWarmPoolProcedure,
		svc.GetWarmPool,
		connect.WithSchema(prebuildServiceMethods.ByName("GetWarmPool")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	prebuildServiceListWarmPoolsHandler := connect.NewUnaryHandler(
		PrebuildServiceListWarmPoolsProcedure,
		svc.ListWarmPools,
		connect.WithSchema(prebuildServiceMethods.ByName("ListWarmPools")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	prebuildServiceUpdateWarmPoolHandler := connect.NewUnaryHandler(
		PrebuildServiceUpdateWarmPoolProcedure,
		svc.UpdateWarmPool,
		connect.WithSchema(prebuildServiceMethods.ByName("UpdateWarmPool")),
		connect.WithHandlerOptions(opts...),
	)
	prebuildServiceDeleteWarmPoolHandler := connect.NewUnaryHandler(
		PrebuildServiceDeleteWarmPoolProcedure,
		svc.DeleteWarmPool,
		connect.WithSchema(prebuildServiceMethods.ByName("DeleteWarmPool")),
		connect.WithHandlerOptions(opts...),
	)
	return "/gitpod.v1.PrebuildService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PrebuildServiceCreatePrebuildProcedure:
			prebuildServiceCreatePrebuildHandler.ServeHTTP(w, r)
		case PrebuildServiceListPrebuildsProcedure:
			prebuildServiceListPrebuildsHandler.ServeHTTP(w, r)
		case PrebuildServiceGetPrebuildProcedure:
			prebuildServiceGetPrebuildHandler.ServeHTTP(w, r)
		case PrebuildServiceCancelPrebuildProcedure:
			prebuildServiceCancelPrebuildHandler.ServeHTTP(w, r)
		case PrebuildServiceDeletePrebuildProcedure:
			prebuildServiceDeletePrebuildHandler.ServeHTTP(w, r)
		case PrebuildServiceCreatePrebuildLogsTokenProcedure:
			prebuildServiceCreatePrebuildLogsTokenHandler.ServeHTTP(w, r)
		case PrebuildServiceCreateWarmPoolProcedure:
			prebuildServiceCreateWarmPoolHandler.ServeHTTP(w, r)
		case PrebuildServiceGetWarmPoolProcedure:
			prebuildServiceGetWarmPoolHandler.ServeHTTP(w, r)
		case PrebuildServiceListWarmPoolsProcedure:
			prebuildServiceListWarmPoolsHandler.ServeHTTP(w, r)
		case PrebuildServiceUpdateWarmPoolProcedure:
			prebuildServiceUpdateWarmPoolHandler.ServeHTTP(w, r)
		case PrebuildServiceDeleteWarmPoolProcedure:
			prebuildServiceDeleteWarmPoolHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPrebuildServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPrebuildServiceHandler struct{}

func (UnimplementedPrebuildServiceHandler) CreatePrebuild(context.Context, *connect.Request[v1.CreatePrebuildRequest]) (*connect.Response[v1.CreatePrebuildResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.PrebuildService.CreatePrebuild is not implemented"))
}

func (UnimplementedPrebuildServiceHandler) ListPrebuilds(context.Context, *connect.Request[v1.ListPrebuildsRequest]) (*connect.Response[v1.ListPrebuildsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.PrebuildService.ListPrebuilds is not implemented"))
}

func (UnimplementedPrebuildServiceHandler) GetPrebuild(context.Context, *connect.Request[v1.GetPrebuildRequest]) (*connect.Response[v1.GetPrebuildResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.PrebuildService.GetPrebuild is not implemented"))
}

func (UnimplementedPrebuildServiceHandler) CancelPrebuild(context.Context, *connect.Request[v1.CancelPrebuildRequest]) (*connect.Response[v1.CancelPrebuildResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.PrebuildService.CancelPrebuild is not implemented"))
}

func (UnimplementedPrebuildServiceHandler) DeletePrebuild(context.Context, *connect.Request[v1.DeletePrebuildRequest]) (*connect.Response[v1.DeletePrebuildResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.PrebuildService.DeletePrebuild is not implemented"))
}

func (UnimplementedPrebuildServiceHandler) CreatePrebuildLogsToken(context.Context, *connect.Request[v1.CreatePrebuildLogsTokenRequest]) (*connect.Response[v1.CreatePrebuildLogsTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.PrebuildService.CreatePrebuildLogsToken is not implemented"))
}

func (UnimplementedPrebuildServiceHandler) CreateWarmPool(context.Context, *connect.Request[v1.CreateWarmPoolRequest]) (*connect.Response[v1.CreateWarmPoolResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.PrebuildService.CreateWarmPool is not implemented"))
}

func (UnimplementedPrebuildServiceHandler) GetWarmPool(context.Context, *connect.Request[v1.GetWarmPoolRequest]) (*connect.Response[v1.GetWarmPoolResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.PrebuildService.GetWarmPool is not implemented"))
}

func (UnimplementedPrebuildServiceHandler) ListWarmPools(context.Context, *connect.Request[v1.ListWarmPoolsRequest]) (*connect.Response[v1.ListWarmPoolsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.PrebuildService.ListWarmPools is not implemented"))
}

func (UnimplementedPrebuildServiceHandler) UpdateWarmPool(context.Context, *connect.Request[v1.UpdateWarmPoolRequest]) (*connect.Response[v1.UpdateWarmPoolResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.PrebuildService.UpdateWarmPool is not implemented"))
}

func (UnimplementedPrebuildServiceHandler) DeleteWarmPool(context.Context, *connect.Request[v1.DeleteWarmPoolRequest]) (*connect.Response[v1.DeleteWarmPoolResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.PrebuildService.DeleteWarmPool is not implemented"))
}
