// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: gitpod/v1/runner_configuration.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/gitpod-io/terraform-provider-ona/internal/api/go/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RunnerConfigurationServiceName is the fully-qualified name of the RunnerConfigurationService
	// service.
	RunnerConfigurationServiceName = "gitpod.v1.RunnerConfigurationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RunnerConfigurationServiceCreateHostAuthenticationTokenProcedure is the fully-qualified name of
	// the RunnerConfigurationService's CreateHostAuthenticationToken RPC.
	RunnerConfigurationServiceCreateHostAuthenticationTokenProcedure = "/gitpod.v1.RunnerConfigurationService/CreateHostAuthenticationToken"
	// RunnerConfigurationServiceGetHostAuthenticationTokenProcedure is the fully-qualified name of the
	// RunnerConfigurationService's GetHostAuthenticationToken RPC.
	RunnerConfigurationServiceGetHostAuthenticationTokenProcedure = "/gitpod.v1.RunnerConfigurationService/GetHostAuthenticationToken"
	// RunnerConfigurationServiceListHostAuthenticationTokensProcedure is the fully-qualified name of
	// the RunnerConfigurationService's ListHostAuthenticationTokens RPC.
	RunnerConfigurationServiceListHostAuthenticationTokensProcedure = "/gitpod.v1.RunnerConfigurationService/ListHostAuthenticationTokens"
	// RunnerConfigurationServiceUpdateHostAuthenticationTokenProcedure is the fully-qualified name of
	// the RunnerConfigurationService's UpdateHostAuthenticationToken RPC.
	RunnerConfigurationServiceUpdateHostAuthenticationTokenProcedure = "/gitpod.v1.RunnerConfigurationService/UpdateHostAuthenticationToken"
	// RunnerConfigurationServiceUpdateHostAuthenticationTokenMetadataProcedure is the fully-qualified
	// name of the RunnerConfigurationService's UpdateHostAuthenticationTokenMetadata RPC.
	RunnerConfigurationServiceUpdateHostAuthenticationTokenMetadataProcedure = "/gitpod.v1.RunnerConfigurationService/UpdateHostAuthenticationTokenMetadata"
	// RunnerConfigurationServiceDeleteHostAuthenticationTokenProcedure is the fully-qualified name of
	// the RunnerConfigurationService's DeleteHostAuthenticationToken RPC.
	RunnerConfigurationServiceDeleteHostAuthenticationTokenProcedure = "/gitpod.v1.RunnerConfigurationService/DeleteHostAuthenticationToken"
	// RunnerConfigurationServiceGetRunnerConfigurationSchemaProcedure is the fully-qualified name of
	// the RunnerConfigurationService's GetRunnerConfigurationSchema RPC.
	RunnerConfigurationServiceGetRunnerConfigurationSchemaProcedure = "/gitpod.v1.RunnerConfigurationService/GetRunnerConfigurationSchema"
	// RunnerConfigurationServiceCreateSCMIntegrationProcedure is the fully-qualified name of the
	// RunnerConfigurationService's CreateSCMIntegration RPC.
	RunnerConfigurationServiceCreateSCMIntegrationProcedure = "/gitpod.v1.RunnerConfigurationService/CreateSCMIntegration"
	// RunnerConfigurationServiceGetSCMIntegrationProcedure is the fully-qualified name of the
	// RunnerConfigurationService's GetSCMIntegration RPC.
	RunnerConfigurationServiceGetSCMIntegrationProcedure = "/gitpod.v1.RunnerConfigurationService/GetSCMIntegration"
	// RunnerConfigurationServiceListSCMIntegrationsProcedure is the fully-qualified name of the
	// RunnerConfigurationService's ListSCMIntegrations RPC.
	RunnerConfigurationServiceListSCMIntegrationsProcedure = "/gitpod.v1.RunnerConfigurationService/ListSCMIntegrations"
	// RunnerConfigurationServiceUpdateSCMIntegrationProcedure is the fully-qualified name of the
	// RunnerConfigurationService's UpdateSCMIntegration RPC.
	RunnerConfigurationServiceUpdateSCMIntegrationProcedure = "/gitpod.v1.RunnerConfigurationService/UpdateSCMIntegration"
	// RunnerConfigurationServiceDeleteSCMIntegrationProcedure is the fully-qualified name of the
	// RunnerConfigurationService's DeleteSCMIntegration RPC.
	RunnerConfigurationServiceDeleteSCMIntegrationProcedure = "/gitpod.v1.RunnerConfigurationService/DeleteSCMIntegration"
	// RunnerConfigurationServiceCreateEnvironmentClassProcedure is the fully-qualified name of the
	// RunnerConfigurationService's CreateEnvironmentClass RPC.
	RunnerConfigurationServiceCreateEnvironmentClassProcedure = "/gitpod.v1.RunnerConfigurationService/CreateEnvironmentClass"
	// RunnerConfigurationServiceGetEnvironmentClassProcedure is the fully-qualified name of the
	// RunnerConfigurationService's GetEnvironmentClass RPC.
	RunnerConfigurationServiceGetEnvironmentClassProcedure = "/gitpod.v1.RunnerConfigurationService/GetEnvironmentClass"
	// RunnerConfigurationServiceListEnvironmentClassesProcedure is the fully-qualified name of the
	// RunnerConfigurationService's ListEnvironmentClasses RPC.
	RunnerConfigurationServiceListEnvironmentClassesProcedure = "/gitpod.v1.RunnerConfigurationService/ListEnvironmentClasses"
	// RunnerConfigurationServiceUpdateEnvironmentClassProcedure is the fully-qualified name of the
	// RunnerConfigurationService's UpdateEnvironmentClass RPC.
	RunnerConfigurationServiceUpdateEnvironmentClassProcedure = "/gitpod.v1.RunnerConfigurationService/UpdateEnvironmentClass"
	// RunnerConfigurationServiceValidateRunnerConfigurationProcedure is the fully-qualified name of the
	// RunnerConfigurationService's ValidateRunnerConfiguration RPC.
	RunnerConfigurationServiceValidateRunnerConfigurationProcedure = "/gitpod.v1.RunnerConfigurationService/ValidateRunnerConfiguration"
	// RunnerConfigurationServiceCreateLLMIntegrationProcedure is the fully-qualified name of the
	// RunnerConfigurationService's CreateLLMIntegration RPC.
	RunnerConfigurationServiceCreateLLMIntegrationProcedure = "/gitpod.v1.RunnerConfigurationService/CreateLLMIntegration"
	// RunnerConfigurationServiceGetLLMIntegrationProcedure is the fully-qualified name of the
	// RunnerConfigurationService's GetLLMIntegration RPC.
	RunnerConfigurationServiceGetLLMIntegrationProcedure = "/gitpod.v1.RunnerConfigurationService/GetLLMIntegration"
	// RunnerConfigurationServiceListLLMIntegrationsProcedure is the fully-qualified name of the
	// RunnerConfigurationService's ListLLMIntegrations RPC.
	RunnerConfigurationServiceListLLMIntegrationsProcedure = "/gitpod.v1.RunnerConfigurationService/ListLLMIntegrations"
	// RunnerConfigurationServiceUpdateLLMIntegrationProcedure is the fully-qualified name of the
	// RunnerConfigurationService's UpdateLLMIntegration RPC.
	RunnerConfigurationServiceUpdateLLMIntegrationProcedure = "/gitpod.v1.RunnerConfigurationService/UpdateLLMIntegration"
	// RunnerConfigurationServiceDeleteLLMIntegrationProcedure is the fully-qualified name of the
	// RunnerConfigurationService's DeleteLLMIntegration RPC.
	RunnerConfigurationServiceDeleteLLMIntegrationProcedure = "/gitpod.v1.RunnerConfigurationService/DeleteLLMIntegration"
)

// RunnerConfigurationServiceClient is a client for the gitpod.v1.RunnerConfigurationService
// service.
type RunnerConfigurationServiceClient interface {
	// Creates a new authentication token for accessing remote hosts.
	//
	// Use this method to:
	// - Set up SCM authentication
	// - Configure OAuth credentials
	// - Manage PAT tokens
	//
	// ### Examples
	//
	// - Create OAuth token:
	//
	//	Creates a new OAuth-based authentication token.
	//
	//	```yaml
	//	runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	userId: "f53d2330-3795-4c5d-a1f3-453121af9c60"
	//	host: "github.com"
	//	token: "gho_xxxxxxxxxxxx"
	//	source: HOST_AUTHENTICATION_TOKEN_SOURCE_OAUTH
	//	expiresAt: "2024-12-31T23:59:59Z"
	//	refreshToken: "ghr_xxxxxxxxxxxx"
	//	```
	CreateHostAuthenticationToken(context.Context, *connect.Request[v1.CreateHostAuthenticationTokenRequest]) (*connect.Response[v1.CreateHostAuthenticationTokenResponse], error)
	// Gets details about a specific host authentication token.
	//
	// Use this method to:
	// - View token information
	// - Check token expiration
	// - Verify token validity
	//
	// ### Examples
	//
	// - Get token details:
	//
	//	Retrieves information about a specific token.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	GetHostAuthenticationToken(context.Context, *connect.Request[v1.GetHostAuthenticationTokenRequest]) (*connect.Response[v1.GetHostAuthenticationTokenResponse], error)
	// Lists host authentication tokens with optional filtering.
	//
	// Use this method to:
	// - View all tokens
	// - Filter by runner or user
	// - Monitor token status
	//
	// ### Examples
	//
	// - List all tokens:
	//
	//	Shows all tokens with pagination.
	//
	//	```yaml
	//	pagination:
	//	  pageSize: 20
	//	```
	//
	// - Filter by runner:
	//
	//	Lists tokens for a specific runner.
	//
	//	```yaml
	//	filter:
	//	  runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	pagination:
	//	  pageSize: 20
	//	```
	ListHostAuthenticationTokens(context.Context, *connect.Request[v1.ListHostAuthenticationTokensRequest]) (*connect.Response[v1.ListHostAuthenticationTokensResponse], error)
	// Updates an existing host authentication token.
	//
	// Use this method to:
	// - Refresh token values
	// - Update expiration
	// - Modify token settings
	//
	// ### Examples
	//
	// - Update token:
	//
	//	Updates token value and expiration.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	token: "gho_xxxxxxxxxxxx"
	//	expiresAt: "2024-12-31T23:59:59Z"
	//	refreshToken: "ghr_xxxxxxxxxxxx"
	//	```
	UpdateHostAuthenticationToken(context.Context, *connect.Request[v1.UpdateHostAuthenticationTokenRequest]) (*connect.Response[v1.UpdateHostAuthenticationTokenResponse], error)
	// Updates metadata for an existing host authentication token.
	//
	// Use this method to:
	// - Persist provider-derived identity metadata
	// - Attach external user mappings used by webhook handling
	//
	// ### Examples
	//
	// - Update external user ID:
	//
	//	Persists the provider user ID associated with the token.
	//
	//	```yaml
	//	runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	externalUserId: "12345678"
	//	```
	UpdateHostAuthenticationTokenMetadata(context.Context, *connect.Request[v1.UpdateHostAuthenticationTokenMetadataRequest]) (*connect.Response[v1.UpdateHostAuthenticationTokenMetadataResponse], error)
	// Deletes a host authentication token.
	//
	// Use this method to:
	// - Remove unused tokens
	// - Revoke access
	// - Clean up expired tokens
	//
	// ### Examples
	//
	// - Delete token:
	//
	//	Permanently removes a token.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	DeleteHostAuthenticationToken(context.Context, *connect.Request[v1.DeleteHostAuthenticationTokenRequest]) (*connect.Response[v1.DeleteHostAuthenticationTokenResponse], error)
	// Gets the latest runner configuration schema.
	//
	// Use this method to:
	// - View available settings
	// - Check configuration options
	// - Validate configurations
	//
	// ### Examples
	//
	// - Get schema:
	//
	//	Retrieves configuration schema for a runner.
	//
	//	```yaml
	//	runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	GetRunnerConfigurationSchema(context.Context, *connect.Request[v1.GetRunnerConfigurationSchemaRequest]) (*connect.Response[v1.GetRunnerConfigurationSchemaResponse], error)
	// Creates a new SCM integration for a runner.
	//
	// Use this method to:
	// - Configure source control access
	// - Set up repository integrations
	// - Enable code synchronization
	//
	// ### Examples
	//
	// - Create GitHub integration:
	//
	//	Sets up GitHub SCM integration.
	//
	//	```yaml
	//	runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	scmId: "github"
	//	host: "github.com"
	//	oauthClientId: "client_id"
	//	oauthPlaintextClientSecret: "client_secret"
	//	```
	CreateSCMIntegration(context.Context, *connect.Request[v1.CreateSCMIntegrationRequest]) (*connect.Response[v1.CreateSCMIntegrationResponse], error)
	// Gets details about a specific SCM integration.
	//
	// Use this method to:
	// - View integration settings
	// - Check integration status
	// - Verify configuration
	//
	// ### Examples
	//
	// - Get integration details:
	//
	//	Retrieves information about a specific integration.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	GetSCMIntegration(context.Context, *connect.Request[v1.GetSCMIntegrationRequest]) (*connect.Response[v1.GetSCMIntegrationResponse], error)
	// Lists SCM integrations for a runner.
	//
	// Use this method to:
	// - View all integrations
	// - Monitor integration status
	// - Check available SCMs
	//
	// ### Examples
	//
	// - List integrations:
	//
	//	Shows all SCM integrations.
	//
	//	```yaml
	//	filter:
	//	  runnerIds: ["d2c94c27-3b76-4a42-b88c-95a85e392c68"]
	//	pagination:
	//	  pageSize: 20
	//	```
	ListSCMIntegrations(context.Context, *connect.Request[v1.ListSCMIntegrationsRequest]) (*connect.Response[v1.ListSCMIntegrationsResponse], error)
	// Updates an existing SCM integration.
	//
	// Use this method to:
	// - Modify integration settings
	// - Update credentials
	// - Change configuration
	//
	// ### Examples
	//
	// - Update integration:
	//
	//	Updates OAuth credentials.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	oauthClientId: "new_client_id"
	//	oauthPlaintextClientSecret: "new_client_secret"
	//	```
	UpdateSCMIntegration(context.Context, *connect.Request[v1.UpdateSCMIntegrationRequest]) (*connect.Response[v1.UpdateSCMIntegrationResponse], error)
	// Deletes an SCM integration.
	//
	// Use this method to:
	// - Remove unused integrations
	// - Clean up configurations
	// - Revoke SCM access
	//
	// ### Examples
	//
	// - Delete integration:
	//
	//	Removes an SCM integration.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	DeleteSCMIntegration(context.Context, *connect.Request[v1.DeleteSCMIntegrationRequest]) (*connect.Response[v1.DeleteSCMIntegrationResponse], error)
	// Creates a new environment class for a runner.
	//
	// Use this method to:
	// - Define compute resources
	// - Configure environment settings
	// - Set up runtime options
	//
	// ### Examples
	//
	// - Create environment class:
	//
	//	Creates a new environment configuration.
	//
	//	```yaml
	//	runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	displayName: "Large Instance"
	//	description: "8 CPU, 16GB RAM"
	//	configuration:
	//	  - key: "cpu"
	//	    value: "8"
	//	  - key: "memory"
	//	    value: "16384"
	//	```
	CreateEnvironmentClass(context.Context, *connect.Request[v1.CreateEnvironmentClassRequest]) (*connect.Response[v1.CreateEnvironmentClassResponse], error)
	// Gets details about a specific environment class.
	//
	// Use this method to:
	// - View class configuration
	// - Check resource settings
	// - Verify availability
	//
	// ### Examples
	//
	// - Get class details:
	//
	//	Retrieves information about a specific class.
	//
	//	```yaml
	//	environmentClassId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	GetEnvironmentClass(context.Context, *connect.Request[v1.GetEnvironmentClassRequest]) (*connect.Response[v1.GetEnvironmentClassResponse], error)
	// Lists environment classes with optional filtering.
	//
	// Use this method to:
	// - View available classes
	// - Filter by capability
	// - Check enabled status
	//
	// ### Examples
	//
	// - List all classes:
	//
	//	Shows all environment classes.
	//
	//	```yaml
	//	pagination:
	//	  pageSize: 20
	//	```
	//
	// - Filter enabled classes:
	//
	//	Lists only enabled environment classes.
	//
	//	```yaml
	//	filter:
	//	  enabled: true
	//	pagination:
	//	  pageSize: 20
	//	```
	//
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	ListEnvironmentClasses(context.Context, *connect.Request[v1.ListEnvironmentClassesRequest]) (*connect.Response[v1.ListEnvironmentClassesResponse], error)
	// Updates an environment class.
	//
	// Use this method to:
	// - Modify class settings
	// - Update resource limits
	// - Change availability
	//
	// ### Examples
	//
	// - Update class:
	//
	//	Changes class configuration.
	//
	//	```yaml
	//	environmentClassId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	displayName: "Updated Large Instance"
	//	description: "16 CPU, 32GB RAM"
	//	enabled: true
	//	```
	UpdateEnvironmentClass(context.Context, *connect.Request[v1.UpdateEnvironmentClassRequest]) (*connect.Response[v1.UpdateEnvironmentClassResponse], error)
	// Validates a runner configuration.
	//
	// Use this method to:
	// - Check configuration validity
	// - Verify integration settings
	// - Validate environment classes
	//
	// ### Examples
	//
	// - Validate SCM integration:
	//
	//	Checks if an SCM integration is valid.
	//
	//	```yaml
	//	runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	scmIntegration:
	//	  id: "integration-id"
	//	  scmId: "github"
	//	  host: "github.com"
	//	  oauthClientId: "client_id"
	//	  oauthPlaintextClientSecret: "client_secret"
	//	```
	ValidateRunnerConfiguration(context.Context, *connect.Request[v1.ValidateRunnerConfigurationRequest]) (*connect.Response[v1.ValidateRunnerConfigurationResponse], error)
	// Creates a new LLM integration for a runner.
	//
	// Use this method to:
	// - Configure LLM access
	// - Set up LLM integrations
	// - Enable LLM usage
	CreateLLMIntegration(context.Context, *connect.Request[v1.CreateLLMIntegrationRequest]) (*connect.Response[v1.CreateLLMIntegrationResponse], error)
	// Gets details about a specific LLM integration.
	//
	// Use this method to:
	// - View integration settings
	// - Check integration status
	// - Verify configuration
	//
	// ### Examples
	//
	// - Get integration details:
	//
	//	Retrieves information about a specific integration.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	GetLLMIntegration(context.Context, *connect.Request[v1.GetLLMIntegrationRequest]) (*connect.Response[v1.GetLLMIntegrationResponse], error)
	// Lists LLM integrations for a runner.
	//
	// Use this method to:
	// - View all integrations
	// - Monitor integration status
	// - Check available LLMs
	//
	// ### Examples
	//
	// - List integrations:
	//
	//	Shows all LLM integrations.
	//
	//	```yaml
	//	filter:
	//	  runnerIds: ["d2c94c27-3b76-4a42-b88c-95a85e392c68"]
	//	pagination:
	//	  pageSize: 20
	//	```
	ListLLMIntegrations(context.Context, *connect.Request[v1.ListLLMIntegrationsRequest]) (*connect.Response[v1.ListLLMIntegrationsResponse], error)
	// Updates an existing LLM integration.
	//
	// Use this method to:
	// - Modify integration settings
	// - Update credentials
	// - Change configuration
	//
	// ### Examples
	//
	// - Update integration:
	//
	//	Updates OAuth credentials.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	apiKey: "sk-..."
	//	```
	UpdateLLMIntegration(context.Context, *connect.Request[v1.UpdateLLMIntegrationRequest]) (*connect.Response[v1.UpdateLLMIntegrationResponse], error)
	// Deletes an LLM integration.
	//
	// Use this method to:
	// - Remove unused integrations
	// - Clean up configurations
	// - Revoke LLM access
	//
	// ### Examples
	//
	// - Delete integration:
	//
	//	Removes an LLM integration.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	DeleteLLMIntegration(context.Context, *connect.Request[v1.DeleteLLMIntegrationRequest]) (*connect.Response[v1.DeleteLLMIntegrationResponse], error)
}

// NewRunnerConfigurationServiceClient constructs a client for the
// gitpod.v1.RunnerConfigurationService service. By default, it uses the Connect protocol with the
// binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To use the
// gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRunnerConfigurationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RunnerConfigurationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	runnerConfigurationServiceMethods := v1.File_gitpod_v1_runner_configuration_proto.Services().ByName("RunnerConfigurationService").Methods()
	return &runnerConfigurationServiceClient{
		createHostAuthenticationToken: connect.NewClient[v1.CreateHostAuthenticationTokenRequest, v1.CreateHostAuthenticationTokenResponse](
			httpClient,
			baseURL+RunnerConfigurationServiceCreateHostAuthenticationTokenProcedure,
			connect.WithSchema(runnerConfigurationServiceMethods.ByName("CreateHostAuthenticationToken")),
			connect.WithClientOptions(opts...),
		),
		getHostAuthenticationToken: connect.NewClient[v1.GetHostAuthenticationTokenRequest, v1.GetHostAuthenticationTokenResponse](
			httpClient,
			baseURL+RunnerConfigurationServiceGetHostAuthenticationTokenProcedure,
			connect.WithSchema(runnerConfigurationServiceMethods.ByName("GetHostAuthenticationToken")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listHostAuthenticationTokens: connect.NewClient[v1.ListHostAuthenticationTokensRequest, v1.ListHostAuthenticationTokensResponse](
			httpClient,
			baseURL+RunnerConfigurationServiceListHostAuthenticationTokensProcedure,
			connect.WithSchema(runnerConfigurationServiceMethods.ByName("ListHostAuthenticationTokens")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updateHostAuthenticationToken: connect.NewClient[v1.UpdateHostAuthenticationTokenRequest, v1.UpdateHostAuthenticationTokenResponse](
			httpClient,
			baseURL+RunnerConfigurationServiceUpdateHostAuthenticationTokenProcedure,
			connect.WithSchema(runnerConfigurationServiceMethods.ByName("UpdateHostAuthenticationToken")),
			connect.WithClientOptions(opts...),
		),
		updateHostAuthenticationTokenMetadata: connect.NewClient[v1.UpdateHostAuthenticationTokenMetadataRequest, v1.UpdateHostAuthenticationTokenMetadataResponse](
			httpClient,
			baseURL+RunnerConfigurationServiceUpdateHostAuthenticationTokenMetadataProcedure,
			connect.WithSchema(runnerConfigurationServiceMethods.ByName("UpdateHostAuthenticationTokenMetadata")),
			connect.WithClientOptions(opts...),
		),
		deleteHostAuthenticationToken: connect.NewClient[v1.DeleteHostAuthenticationTokenRequest, v1.DeleteHostAuthenticationTokenResponse](
			httpClient,
			baseURL+RunnerConfigurationServiceDeleteHostAuthenticationTokenProcedure,
			connect.WithSchema(runnerConfigurationServiceMethods.ByName("DeleteHostAuthenticationToken")),
			connect.WithClientOptions(opts...),
		),
		getRunnerConfigurationSchema: connect.NewClient[v1.GetRunnerConfigurationSchemaRequest, v1.GetRunnerConfigurationSchemaResponse](
			httpClient,
			baseURL+RunnerConfigurationServiceGetRunnerConfigurationSchemaProcedure,
			connect.WithSchema(runnerConfigurationServiceMethods.ByName("GetRunnerConfigurationSchema")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		createSCMIntegration: connect.NewClient[v1.CreateSCMIntegrationRequest, v1.CreateSCMIntegrationResponse](
			httpClient,
			baseURL+RunnerConfigurationServiceCreateSCMIntegrationProcedure,
			connect.WithSchema(runnerConfigurationServiceMethods.ByName("CreateSCMIntegration")),
			connect.WithClientOptions(opts...),
		),
		getSCMIntegration: connect.NewClient[v1.GetSCMIntegrationRequest, v1.GetSCMIntegrationResponse](
			httpClient,
			baseURL+RunnerConfigurationServiceGetSCMIntegrationProcedure,
			connect.WithSchema(runnerConfigurationServiceMethods.ByName("GetSCMIntegration")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listSCMIntegrations: connect.NewClient[v1.ListSCMIntegrationsRequest, v1.ListSCMIntegrationsResponse](
			httpClient,
			baseURL+RunnerConfigurationServiceListSCMIntegrationsProcedure,
			connect.WithSchema(runnerConfigurationServiceMethods.ByName("ListSCMIntegrations")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updateSCMIntegration: connect.NewClient[v1.UpdateSCMIntegrationRequest, v1.UpdateSCMIntegrationResponse](
			httpClient,
			baseURL+RunnerConfigurationServiceUpdateSCMIntegrationProcedure,
			connect.WithSchema(runnerConfigurationServiceMethods.ByName("UpdateSCMIntegration")),
			connect.WithClientOptions(opts...),
		),
		deleteSCMIntegration: connect.NewClient[v1.DeleteSCMIntegrationRequest, v1.DeleteSCMIntegrationResponse](
			httpClient,
			baseURL+RunnerConfigurationServiceDeleteSCMIntegrationProcedure,
			connect.WithSchema(runnerConfigurationServiceMethods.ByName("DeleteSCMIntegration")),
			connect.WithClientOptions(opts...),
		),
		createEnvironmentClass: connect.NewClient[v1.CreateEnvironmentClassRequest, v1.CreateEnvironmentClassResponse](
			httpClient,
			baseURL+RunnerConfigurationServiceCreateEnvironmentClassProcedure,
			connect.WithSchema(runnerConfigurationServiceMethods.ByName("CreateEnvironmentClass")),
			connect.WithClientOptions(opts...),
		),
		getEnvironmentClass: connect.NewClient[v1.GetEnvironmentClassRequest, v1.GetEnvironmentClassResponse](
			httpClient,
			baseURL+RunnerConfigurationServiceGetEnvironmentClassProcedure,
			connect.WithSchema(runnerConfigurationServiceMethods.ByName("GetEnvironmentClass")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listEnvironmentClasses: connect.NewClient[v1.ListEnvironmentClassesRequest, v1.ListEnvironmentClassesResponse](
			httpClient,
			baseURL+RunnerConfigurationServiceListEnvironmentClassesProcedure,
			connect.WithSchema(runnerConfigurationServiceMethods.ByName("ListEnvironmentClasses")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updateEnvironmentClass: connect.NewClient[v1.UpdateEnvironmentClassRequest, v1.UpdateEnvironmentClassResponse](
			httpClient,
			baseURL+RunnerConfigurationServiceUpdateEnvironmentClassProcedure,
			connect.WithSchema(runnerConfigurationServiceMethods.ByName("UpdateEnvironmentClass")),
			connect.WithClientOptions(opts...),
		),
		validateRunnerConfiguration: connect.NewClient[v1.ValidateRunnerConfigurationRequest, v1.ValidateRunnerConfigurationResponse](
			httpClient,
			baseURL+RunnerConfigurationServiceValidateRunnerConfigurationProcedure,
			connect.WithSchema(runnerConfigurationServiceMethods.ByName("ValidateRunnerConfiguration")),
			connect.WithClientOptions(opts...),
		),
		createLLMIntegration: connect.NewClient[v1.CreateLLMIntegrationRequest, v1.CreateLLMIntegrationResponse](
			httpClient,
			baseURL+RunnerConfigurationServiceCreateLLMIntegrationProcedure,
			connect.WithSchema(runnerConfigurationServiceMethods.ByName("CreateLLMIntegration")),
			connect.WithClientOptions(opts...),
		),
		getLLMIntegration: connect.NewClient[v1.GetLLMIntegrationRequest, v1.GetLLMIntegrationResponse](
			httpClient,
			baseURL+RunnerConfigurationServiceGetLLMIntegrationProcedure,
			connect.WithSchema(runnerConfigurationServiceMethods.ByName("GetLLMIntegration")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listLLMIntegrations: connect.NewClient[v1.ListLLMIntegrationsRequest, v1.ListLLMIntegrationsResponse](
			httpClient,
			baseURL+RunnerConfigurationServiceListLLMIntegrationsProcedure,
			connect.WithSchema(runnerConfigurationServiceMethods.ByName("ListLLMIntegrations")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updateLLMIntegration: connect.NewClient[v1.UpdateLLMIntegrationRequest, v1.UpdateLLMIntegrationResponse](
			httpClient,
			baseURL+RunnerConfigurationServiceUpdateLLMIntegrationProcedure,
			connect.WithSchema(runnerConfigurationServiceMethods.ByName("UpdateLLMIntegration")),
			connect.WithClientOptions(opts...),
		),
		deleteLLMIntegration: connect.NewClient[v1.DeleteLLMIntegrationRequest, v1.DeleteLLMIntegrationResponse](
			httpClient,
			baseURL+RunnerConfigurationServiceDeleteLLMIntegrationProcedure,
			connect.WithSchema(runnerConfigurationServiceMethods.ByName("DeleteLLMIntegration")),
			connect.WithClientOptions(opts...),
		),
	}
}

// runnerConfigurationServiceClient implements RunnerConfigurationServiceClient.
type runnerConfigurationServiceClient struct {
	createHostAuthenticationToken         *connect.Client[v1.CreateHostAuthenticationTokenRequest, v1.CreateHostAuthenticationTokenResponse]
	getHostAuthenticationToken            *connect.Client[v1.GetHostAuthenticationTokenRequest, v1.GetHostAuthenticationTokenResponse]
	listHostAuthenticationTokens          *connect.Client[v1.ListHostAuthenticationTokensRequest, v1.ListHostAuthenticationTokensResponse]
	updateHostAuthenticationToken         *connect.Client[v1.UpdateHostAuthenticationTokenRequest, v1.UpdateHostAuthenticationTokenResponse]
	updateHostAuthenticationTokenMetadata *connect.Client[v1.UpdateHostAuthenticationTokenMetadataRequest, v1.UpdateHostAuthenticationTokenMetadataResponse]
	deleteHostAuthenticationToken         *connect.Client[v1.DeleteHostAuthenticationTokenRequest, v1.DeleteHostAuthenticationTokenResponse]
	getRunnerConfigurationSchema          *connect.Client[v1.GetRunnerConfigurationSchemaRequest, v1.GetRunnerConfigurationSchemaResponse]
	createSCMIntegration                  *connect.Client[v1.CreateSCMIntegrationRequest, v1.CreateSCMIntegrationResponse]
	getSCMIntegration                     *connect.Client[v1.GetSCMIntegrationRequest, v1.GetSCMIntegrationResponse]
	listSCMIntegrations                   *connect.Client[v1.ListSCMIntegrationsRequest, v1.ListSCMIntegrationsResponse]
	updateSCMIntegration                  *connect.Client[v1.UpdateSCMIntegrationRequest, v1.UpdateSCMIntegrationResponse]
	deleteSCMIntegration                  *connect.Client[v1.DeleteSCMIntegrationRequest, v1.DeleteSCMIntegrationResponse]
	createEnvironmentClass                *connect.Client[v1.CreateEnvironmentClassRequest, v1.CreateEnvironmentClassResponse]
	getEnvironmentClass                   *connect.Client[v1.GetEnvironmentClassRequest, v1.GetEnvironmentClassResponse]
	listEnvironmentClasses                *connect.Client[v1.ListEnvironmentClassesRequest, v1.ListEnvironmentClassesResponse]
	updateEnvironmentClass                *connect.Client[v1.UpdateEnvironmentClassRequest, v1.UpdateEnvironmentClassResponse]
	validateRunnerConfiguration           *connect.Client[v1.ValidateRunnerConfigurationRequest, v1.ValidateRunnerConfigurationResponse]
	createLLMIntegration                  *connect.Client[v1.CreateLLMIntegrationRequest, v1.CreateLLMIntegrationResponse]
	getLLMIntegration                     *connect.Client[v1.GetLLMIntegrationRequest, v1.GetLLMIntegrationResponse]
	listLLMIntegrations                   *connect.Client[v1.ListLLMIntegrationsRequest, v1.ListLLMIntegrationsResponse]
	updateLLMIntegration                  *connect.Client[v1.UpdateLLMIntegrationRequest, v1.UpdateLLMIntegrationResponse]
	deleteLLMIntegration                  *connect.Client[v1.DeleteLLMIntegrationRequest, v1.DeleteLLMIntegrationResponse]
}

// CreateHostAuthenticationToken calls
// gitpod.v1.RunnerConfigurationService.CreateHostAuthenticationToken.
func (c *runnerConfigurationServiceClient) CreateHostAuthenticationToken(ctx context.Context, req *connect.Request[v1.CreateHostAuthenticationTokenRequest]) (*connect.Response[v1.CreateHostAuthenticationTokenResponse], error) {
	return c.createHostAuthenticationToken.CallUnary(ctx, req)
}

// GetHostAuthenticationToken calls gitpod.v1.RunnerConfigurationService.GetHostAuthenticationToken.
func (c *runnerConfigurationServiceClient) GetHostAuthenticationToken(ctx context.Context, req *connect.Request[v1.GetHostAuthenticationTokenRequest]) (*connect.Response[v1.GetHostAuthenticationTokenResponse], error) {
	return c.getHostAuthenticationToken.CallUnary(ctx, req)
}

// ListHostAuthenticationTokens calls
// gitpod.v1.RunnerConfigurationService.ListHostAuthenticationTokens.
func (c *runnerConfigurationServiceClient) ListHostAuthenticationTokens(ctx context.Context, req *connect.Request[v1.ListHostAuthenticationTokensRequest]) (*connect.Response[v1.ListHostAuthenticationTokensResponse], error) {
	return c.listHostAuthenticationTokens.CallUnary(ctx, req)
}

// UpdateHostAuthenticationToken calls
// gitpod.v1.RunnerConfigurationService.UpdateHostAuthenticationToken.
func (c *runnerConfigurationServiceClient) UpdateHostAuthenticationToken(ctx context.Context, req *connect.Request[v1.UpdateHostAuthenticationTokenRequest]) (*connect.Response[v1.UpdateHostAuthenticationTokenResponse], error) {
	return c.updateHostAuthenticationToken.CallUnary(ctx, req)
}

// UpdateHostAuthenticationTokenMetadata calls
// gitpod.v1.RunnerConfigurationService.UpdateHostAuthenticationTokenMetadata.
func (c *runnerConfigurationServiceClient) UpdateHostAuthenticationTokenMetadata(ctx context.Context, req *connect.Request[v1.UpdateHostAuthenticationTokenMetadataRequest]) (*connect.Response[v1.UpdateHostAuthenticationTokenMetadataResponse], error) {
	return c.updateHostAuthenticationTokenMetadata.CallUnary(ctx, req)
}

// DeleteHostAuthenticationToken calls
// gitpod.v1.RunnerConfigurationService.DeleteHostAuthenticationToken.
func (c *runnerConfigurationServiceClient) DeleteHostAuthenticationToken(ctx context.Context, req *connect.Request[v1.DeleteHostAuthenticationTokenRequest]) (*connect.Response[v1.DeleteHostAuthenticationTokenResponse], error) {
	return c.deleteHostAuthenticationToken.CallUnary(ctx, req)
}

// GetRunnerConfigurationSchema calls
// gitpod.v1.RunnerConfigurationService.GetRunnerConfigurationSchema.
func (c *runnerConfigurationServiceClient) GetRunnerConfigurationSchema(ctx context.Context, req *connect.Request[v1.GetRunnerConfigurationSchemaRequest]) (*connect.Response[v1.GetRunnerConfigurationSchemaResponse], error) {
	return c.getRunnerConfigurationSchema.CallUnary(ctx, req)
}

// CreateSCMIntegration calls gitpod.v1.RunnerConfigurationService.CreateSCMIntegration.
func (c *runnerConfigurationServiceClient) CreateSCMIntegration(ctx context.Context, req *connect.Request[v1.CreateSCMIntegrationRequest]) (*connect.Response[v1.CreateSCMIntegrationResponse], error) {
	return c.createSCMIntegration.CallUnary(ctx, req)
}

// GetSCMIntegration calls gitpod.v1.RunnerConfigurationService.GetSCMIntegration.
func (c *runnerConfigurationServiceClient) GetSCMIntegration(ctx context.Context, req *connect.Request[v1.GetSCMIntegrationRequest]) (*connect.Response[v1.GetSCMIntegrationResponse], error) {
	return c.getSCMIntegration.CallUnary(ctx, req)
}

// ListSCMIntegrations calls gitpod.v1.RunnerConfigurationService.ListSCMIntegrations.
func (c *runnerConfigurationServiceClient) ListSCMIntegrations(ctx context.Context, req *connect.Request[v1.ListSCMIntegrationsRequest]) (*connect.Response[v1.ListSCMIntegrationsResponse], error) {
	return c.listSCMIntegrations.CallUnary(ctx, req)
}

// UpdateSCMIntegration calls gitpod.v1.RunnerConfigurationService.UpdateSCMIntegration.
func (c *runnerConfigurationServiceClient) UpdateSCMIntegration(ctx context.Context, req *connect.Request[v1.UpdateSCMIntegrationRequest]) (*connect.Response[v1.UpdateSCMIntegrationResponse], error) {
	return c.updateSCMIntegration.CallUnary(ctx, req)
}

// DeleteSCMIntegration calls gitpod.v1.RunnerConfigurationService.DeleteSCMIntegration.
func (c *runnerConfigurationServiceClient) DeleteSCMIntegration(ctx context.Context, req *connect.Request[v1.DeleteSCMIntegrationRequest]) (*connect.Response[v1.DeleteSCMIntegrationResponse], error) {
	return c.deleteSCMIntegration.CallUnary(ctx, req)
}

// CreateEnvironmentClass calls gitpod.v1.RunnerConfigurationService.CreateEnvironmentClass.
func (c *runnerConfigurationServiceClient) CreateEnvironmentClass(ctx context.Context, req *connect.Request[v1.CreateEnvironmentClassRequest]) (*connect.Response[v1.CreateEnvironmentClassResponse], error) {
	return c.createEnvironmentClass.CallUnary(ctx, req)
}

// GetEnvironmentClass calls gitpod.v1.RunnerConfigurationService.GetEnvironmentClass.
func (c *runnerConfigurationServiceClient) GetEnvironmentClass(ctx context.Context, req *connect.Request[v1.GetEnvironmentClassRequest]) (*connect.Response[v1.GetEnvironmentClassResponse], error) {
	return c.getEnvironmentClass.CallUnary(ctx, req)
}

// ListEnvironmentClasses calls gitpod.v1.RunnerConfigurationService.ListEnvironmentClasses.
func (c *runnerConfigurationServiceClient) ListEnvironmentClasses(ctx context.Context, req *connect.Request[v1.ListEnvironmentClassesRequest]) (*connect.Response[v1.ListEnvironmentClassesResponse], error) {
	return c.listEnvironmentClasses.CallUnary(ctx, req)
}

// UpdateEnvironmentClass calls gitpod.v1.RunnerConfigurationService.UpdateEnvironmentClass.
func (c *runnerConfigurationServiceClient) UpdateEnvironmentClass(ctx context.Context, req *connect.Request[v1.UpdateEnvironmentClassRequest]) (*connect.Response[v1.UpdateEnvironmentClassResponse], error) {
	return c.updateEnvironmentClass.CallUnary(ctx, req)
}

// ValidateRunnerConfiguration calls
// gitpod.v1.RunnerConfigurationService.ValidateRunnerConfiguration.
func (c *runnerConfigurationServiceClient) ValidateRunnerConfiguration(ctx context.Context, req *connect.Request[v1.ValidateRunnerConfigurationRequest]) (*connect.Response[v1.ValidateRunnerConfigurationResponse], error) {
	return c.validateRunnerConfiguration.CallUnary(ctx, req)
}

// CreateLLMIntegration calls gitpod.v1.RunnerConfigurationService.CreateLLMIntegration.
func (c *runnerConfigurationServiceClient) CreateLLMIntegration(ctx context.Context, req *connect.Request[v1.CreateLLMIntegrationRequest]) (*connect.Response[v1.CreateLLMIntegrationResponse], error) {
	return c.createLLMIntegration.CallUnary(ctx, req)
}

// GetLLMIntegration calls gitpod.v1.RunnerConfigurationService.GetLLMIntegration.
func (c *runnerConfigurationServiceClient) GetLLMIntegration(ctx context.Context, req *connect.Request[v1.GetLLMIntegrationRequest]) (*connect.Response[v1.GetLLMIntegrationResponse], error) {
	return c.getLLMIntegration.CallUnary(ctx, req)
}

// ListLLMIntegrations calls gitpod.v1.RunnerConfigurationService.ListLLMIntegrations.
func (c *runnerConfigurationServiceClient) ListLLMIntegrations(ctx context.Context, req *connect.Request[v1.ListLLMIntegrationsRequest]) (*connect.Response[v1.ListLLMIntegrationsResponse], error) {
	return c.listLLMIntegrations.CallUnary(ctx, req)
}

// UpdateLLMIntegration calls gitpod.v1.RunnerConfigurationService.UpdateLLMIntegration.
func (c *runnerConfigurationServiceClient) UpdateLLMIntegration(ctx context.Context, req *connect.Request[v1.UpdateLLMIntegrationRequest]) (*connect.Response[v1.UpdateLLMIntegrationResponse], error) {
	return c.updateLLMIntegration.CallUnary(ctx, req)
}

// DeleteLLMIntegration calls gitpod.v1.RunnerConfigurationService.DeleteLLMIntegration.
func (c *runnerConfigurationServiceClient) DeleteLLMIntegration(ctx context.Context, req *connect.Request[v1.DeleteLLMIntegrationRequest]) (*connect.Response[v1.DeleteLLMIntegrationResponse], error) {
	return c.deleteLLMIntegration.CallUnary(ctx, req)
}

// RunnerConfigurationServiceHandler is an implementation of the
// gitpod.v1.RunnerConfigurationService service.
type RunnerConfigurationServiceHandler interface {
	// Creates a new authentication token for accessing remote hosts.
	//
	// Use this method to:
	// - Set up SCM authentication
	// - Configure OAuth credentials
	// - Manage PAT tokens
	//
	// ### Examples
	//
	// - Create OAuth token:
	//
	//	Creates a new OAuth-based authentication token.
	//
	//	```yaml
	//	runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	userId: "f53d2330-3795-4c5d-a1f3-453121af9c60"
	//	host: "github.com"
	//	token: "gho_xxxxxxxxxxxx"
	//	source: HOST_AUTHENTICATION_TOKEN_SOURCE_OAUTH
	//	expiresAt: "2024-12-31T23:59:59Z"
	//	refreshToken: "ghr_xxxxxxxxxxxx"
	//	```
	CreateHostAuthenticationToken(context.Context, *connect.Request[v1.CreateHostAuthenticationTokenRequest]) (*connect.Response[v1.CreateHostAuthenticationTokenResponse], error)
	// Gets details about a specific host authentication token.
	//
	// Use this method to:
	// - View token information
	// - Check token expiration
	// - Verify token validity
	//
	// ### Examples
	//
	// - Get token details:
	//
	//	Retrieves information about a specific token.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	GetHostAuthenticationToken(context.Context, *connect.Request[v1.GetHostAuthenticationTokenRequest]) (*connect.Response[v1.GetHostAuthenticationTokenResponse], error)
	// Lists host authentication tokens with optional filtering.
	//
	// Use this method to:
	// - View all tokens
	// - Filter by runner or user
	// - Monitor token status
	//
	// ### Examples
	//
	// - List all tokens:
	//
	//	Shows all tokens with pagination.
	//
	//	```yaml
	//	pagination:
	//	  pageSize: 20
	//	```
	//
	// - Filter by runner:
	//
	//	Lists tokens for a specific runner.
	//
	//	```yaml
	//	filter:
	//	  runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	pagination:
	//	  pageSize: 20
	//	```
	ListHostAuthenticationTokens(context.Context, *connect.Request[v1.ListHostAuthenticationTokensRequest]) (*connect.Response[v1.ListHostAuthenticationTokensResponse], error)
	// Updates an existing host authentication token.
	//
	// Use this method to:
	// - Refresh token values
	// - Update expiration
	// - Modify token settings
	//
	// ### Examples
	//
	// - Update token:
	//
	//	Updates token value and expiration.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	token: "gho_xxxxxxxxxxxx"
	//	expiresAt: "2024-12-31T23:59:59Z"
	//	refreshToken: "ghr_xxxxxxxxxxxx"
	//	```
	UpdateHostAuthenticationToken(context.Context, *connect.Request[v1.UpdateHostAuthenticationTokenRequest]) (*connect.Response[v1.UpdateHostAuthenticationTokenResponse], error)
	// Updates metadata for an existing host authentication token.
	//
	// Use this method to:
	// - Persist provider-derived identity metadata
	// - Attach external user mappings used by webhook handling
	//
	// ### Examples
	//
	// - Update external user ID:
	//
	//	Persists the provider user ID associated with the token.
	//
	//	```yaml
	//	runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	externalUserId: "12345678"
	//	```
	UpdateHostAuthenticationTokenMetadata(context.Context, *connect.Request[v1.UpdateHostAuthenticationTokenMetadataRequest]) (*connect.Response[v1.UpdateHostAuthenticationTokenMetadataResponse], error)
	// Deletes a host authentication token.
	//
	// Use this method to:
	// - Remove unused tokens
	// - Revoke access
	// - Clean up expired tokens
	//
	// ### Examples
	//
	// - Delete token:
	//
	//	Permanently removes a token.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	DeleteHostAuthenticationToken(context.Context, *connect.Request[v1.DeleteHostAuthenticationTokenRequest]) (*connect.Response[v1.DeleteHostAuthenticationTokenResponse], error)
	// Gets the latest runner configuration schema.
	//
	// Use this method to:
	// - View available settings
	// - Check configuration options
	// - Validate configurations
	//
	// ### Examples
	//
	// - Get schema:
	//
	//	Retrieves configuration schema for a runner.
	//
	//	```yaml
	//	runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	GetRunnerConfigurationSchema(context.Context, *connect.Request[v1.GetRunnerConfigurationSchemaRequest]) (*connect.Response[v1.GetRunnerConfigurationSchemaResponse], error)
	// Creates a new SCM integration for a runner.
	//
	// Use this method to:
	// - Configure source control access
	// - Set up repository integrations
	// - Enable code synchronization
	//
	// ### Examples
	//
	// - Create GitHub integration:
	//
	//	Sets up GitHub SCM integration.
	//
	//	```yaml
	//	runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	scmId: "github"
	//	host: "github.com"
	//	oauthClientId: "client_id"
	//	oauthPlaintextClientSecret: "client_secret"
	//	```
	CreateSCMIntegration(context.Context, *connect.Request[v1.CreateSCMIntegrationRequest]) (*connect.Response[v1.CreateSCMIntegrationResponse], error)
	// Gets details about a specific SCM integration.
	//
	// Use this method to:
	// - View integration settings
	// - Check integration status
	// - Verify configuration
	//
	// ### Examples
	//
	// - Get integration details:
	//
	//	Retrieves information about a specific integration.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	GetSCMIntegration(context.Context, *connect.Request[v1.GetSCMIntegrationRequest]) (*connect.Response[v1.GetSCMIntegrationResponse], error)
	// Lists SCM integrations for a runner.
	//
	// Use this method to:
	// - View all integrations
	// - Monitor integration status
	// - Check available SCMs
	//
	// ### Examples
	//
	// - List integrations:
	//
	//	Shows all SCM integrations.
	//
	//	```yaml
	//	filter:
	//	  runnerIds: ["d2c94c27-3b76-4a42-b88c-95a85e392c68"]
	//	pagination:
	//	  pageSize: 20
	//	```
	ListSCMIntegrations(context.Context, *connect.Request[v1.ListSCMIntegrationsRequest]) (*connect.Response[v1.ListSCMIntegrationsResponse], error)
	// Updates an existing SCM integration.
	//
	// Use this method to:
	// - Modify integration settings
	// - Update credentials
	// - Change configuration
	//
	// ### Examples
	//
	// - Update integration:
	//
	//	Updates OAuth credentials.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	oauthClientId: "new_client_id"
	//	oauthPlaintextClientSecret: "new_client_secret"
	//	```
	UpdateSCMIntegration(context.Context, *connect.Request[v1.UpdateSCMIntegrationRequest]) (*connect.Response[v1.UpdateSCMIntegrationResponse], error)
	// Deletes an SCM integration.
	//
	// Use this method to:
	// - Remove unused integrations
	// - Clean up configurations
	// - Revoke SCM access
	//
	// ### Examples
	//
	// - Delete integration:
	//
	//	Removes an SCM integration.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	DeleteSCMIntegration(context.Context, *connect.Request[v1.DeleteSCMIntegrationRequest]) (*connect.Response[v1.DeleteSCMIntegrationResponse], error)
	// Creates a new environment class for a runner.
	//
	// Use this method to:
	// - Define compute resources
	// - Configure environment settings
	// - Set up runtime options
	//
	// ### Examples
	//
	// - Create environment class:
	//
	//	Creates a new environment configuration.
	//
	//	```yaml
	//	runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	displayName: "Large Instance"
	//	description: "8 CPU, 16GB RAM"
	//	configuration:
	//	  - key: "cpu"
	//	    value: "8"
	//	  - key: "memory"
	//	    value: "16384"
	//	```
	CreateEnvironmentClass(context.Context, *connect.Request[v1.CreateEnvironmentClassRequest]) (*connect.Response[v1.CreateEnvironmentClassResponse], error)
	// Gets details about a specific environment class.
	//
	// Use this method to:
	// - View class configuration
	// - Check resource settings
	// - Verify availability
	//
	// ### Examples
	//
	// - Get class details:
	//
	//	Retrieves information about a specific class.
	//
	//	```yaml
	//	environmentClassId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	GetEnvironmentClass(context.Context, *connect.Request[v1.GetEnvironmentClassRequest]) (*connect.Response[v1.GetEnvironmentClassResponse], error)
	// Lists environment classes with optional filtering.
	//
	// Use this method to:
	// - View available classes
	// - Filter by capability
	// - Check enabled status
	//
	// ### Examples
	//
	// - List all classes:
	//
	//	Shows all environment classes.
	//
	//	```yaml
	//	pagination:
	//	  pageSize: 20
	//	```
	//
	// - Filter enabled classes:
	//
	//	Lists only enabled environment classes.
	//
	//	```yaml
	//	filter:
	//	  enabled: true
	//	pagination:
	//	  pageSize: 20
	//	```
	//
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	ListEnvironmentClasses(context.Context, *connect.Request[v1.ListEnvironmentClassesRequest]) (*connect.Response[v1.ListEnvironmentClassesResponse], error)
	// Updates an environment class.
	//
	// Use this method to:
	// - Modify class settings
	// - Update resource limits
	// - Change availability
	//
	// ### Examples
	//
	// - Update class:
	//
	//	Changes class configuration.
	//
	//	```yaml
	//	environmentClassId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	displayName: "Updated Large Instance"
	//	description: "16 CPU, 32GB RAM"
	//	enabled: true
	//	```
	UpdateEnvironmentClass(context.Context, *connect.Request[v1.UpdateEnvironmentClassRequest]) (*connect.Response[v1.UpdateEnvironmentClassResponse], error)
	// Validates a runner configuration.
	//
	// Use this method to:
	// - Check configuration validity
	// - Verify integration settings
	// - Validate environment classes
	//
	// ### Examples
	//
	// - Validate SCM integration:
	//
	//	Checks if an SCM integration is valid.
	//
	//	```yaml
	//	runnerId: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	scmIntegration:
	//	  id: "integration-id"
	//	  scmId: "github"
	//	  host: "github.com"
	//	  oauthClientId: "client_id"
	//	  oauthPlaintextClientSecret: "client_secret"
	//	```
	ValidateRunnerConfiguration(context.Context, *connect.Request[v1.ValidateRunnerConfigurationRequest]) (*connect.Response[v1.ValidateRunnerConfigurationResponse], error)
	// Creates a new LLM integration for a runner.
	//
	// Use this method to:
	// - Configure LLM access
	// - Set up LLM integrations
	// - Enable LLM usage
	CreateLLMIntegration(context.Context, *connect.Request[v1.CreateLLMIntegrationRequest]) (*connect.Response[v1.CreateLLMIntegrationResponse], error)
	// Gets details about a specific LLM integration.
	//
	// Use this method to:
	// - View integration settings
	// - Check integration status
	// - Verify configuration
	//
	// ### Examples
	//
	// - Get integration details:
	//
	//	Retrieves information about a specific integration.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	GetLLMIntegration(context.Context, *connect.Request[v1.GetLLMIntegrationRequest]) (*connect.Response[v1.GetLLMIntegrationResponse], error)
	// Lists LLM integrations for a runner.
	//
	// Use this method to:
	// - View all integrations
	// - Monitor integration status
	// - Check available LLMs
	//
	// ### Examples
	//
	// - List integrations:
	//
	//	Shows all LLM integrations.
	//
	//	```yaml
	//	filter:
	//	  runnerIds: ["d2c94c27-3b76-4a42-b88c-95a85e392c68"]
	//	pagination:
	//	  pageSize: 20
	//	```
	ListLLMIntegrations(context.Context, *connect.Request[v1.ListLLMIntegrationsRequest]) (*connect.Response[v1.ListLLMIntegrationsResponse], error)
	// Updates an existing LLM integration.
	//
	// Use this method to:
	// - Modify integration settings
	// - Update credentials
	// - Change configuration
	//
	// ### Examples
	//
	// - Update integration:
	//
	//	Updates OAuth credentials.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	apiKey: "sk-..."
	//	```
	UpdateLLMIntegration(context.Context, *connect.Request[v1.UpdateLLMIntegrationRequest]) (*connect.Response[v1.UpdateLLMIntegrationResponse], error)
	// Deletes an LLM integration.
	//
	// Use this method to:
	// - Remove unused integrations
	// - Clean up configurations
	// - Revoke LLM access
	//
	// ### Examples
	//
	// - Delete integration:
	//
	//	Removes an LLM integration.
	//
	//	```yaml
	//	id: "d2c94c27-3b76-4a42-b88c-95a85e392c68"
	//	```
	DeleteLLMIntegration(context.Context, *connect.Request[v1.DeleteLLMIntegrationRequest]) (*connect.Response[v1.DeleteLLMIntegrationResponse], error)
}

// NewRunnerConfigurationServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRunnerConfigurationServiceHandler(svc RunnerConfigurationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	runnerConfigurationServiceMethods := v1.File_gitpod_v1_runner_configuration_proto.Services().ByName("RunnerConfigurationService").Methods()
	runnerConfigurationServiceCreateHostAuthenticationTokenHandler := connect.NewUnaryHandler(
		RunnerConfigurationServiceCreateHostAuthenticationTokenProcedure,
		svc.CreateHostAuthenticationToken,
		connect.WithSchema(runnerConfigurationServiceMethods.ByName("CreateHostAuthenticationToken")),
		connect.WithHandlerOptions(opts...),
	)
	runnerConfigurationServiceGetHostAuthenticationTokenHandler := connect.NewUnaryHandler(
		RunnerConfigurationServiceGetHostAuthenticationTokenProcedure,
		svc.GetHostAuthenticationToken,
		connect.WithSchema(runnerConfigurationServiceMethods.ByName("GetHostAuthenticationToken")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	runnerConfigurationServiceListHostAuthenticationTokensHandler := connect.NewUnaryHandler(
		RunnerConfigurationServiceListHostAuthenticationTokensProcedure,
		svc.ListHostAuthenticationTokens,
		connect.WithSchema(runnerConfigurationServiceMethods.ByName("ListHostAuthenticationTokens")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	runnerConfigurationServiceUpdateHostAuthenticationTokenHandler := connect.NewUnaryHandler(
		RunnerConfigurationServiceUpdateHostAuthenticationTokenProcedure,
		svc.UpdateHostAuthenticationToken,
		connect.WithSchema(runnerConfigurationServiceMethods.ByName("UpdateHostAuthenticationToken")),
		connect.WithHandlerOptions(opts...),
	)
	runnerConfigurationServiceUpdateHostAuthenticationTokenMetadataHandler := connect.NewUnaryHandler(
		RunnerConfigurationServiceUpdateHostAuthenticationTokenMetadataProcedure,
		svc.UpdateHostAuthenticationTokenMetadata,
		connect.WithSchema(runnerConfigurationServiceMethods.ByName("UpdateHostAuthenticationTokenMetadata")),
		connect.WithHandlerOptions(opts...),
	)
	runnerConfigurationServiceDeleteHostAuthenticationTokenHandler := connect.NewUnaryHandler(
		RunnerConfigurationServiceDeleteHostAuthenticationTokenProcedure,
		svc.DeleteHostAuthenticationToken,
		connect.WithSchema(runnerConfigurationServiceMethods.ByName("DeleteHostAuthenticationToken")),
		connect.WithHandlerOptions(opts...),
	)
	runnerConfigurationServiceGetRunnerConfigurationSchemaHandler := connect.NewUnaryHandler(
		RunnerConfigurationServiceGetRunnerConfigurationSchemaProcedure,
		svc.GetRunnerConfigurationSchema,
		connect.WithSchema(runnerConfigurationServiceMethods.ByName("GetRunnerConfigurationSchema")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	runnerConfigurationServiceCreateSCMIntegrationHandler := connect.NewUnaryHandler(
		RunnerConfigurationServiceCreateSCMIntegrationProcedure,
		svc.CreateSCMIntegration,
		connect.WithSchema(runnerConfigurationServiceMethods.ByName("CreateSCMIntegration")),
		connect.WithHandlerOptions(opts...),
	)
	runnerConfigurationServiceGetSCMIntegrationHandler := connect.NewUnaryHandler(
		RunnerConfigurationServiceGetSCMIntegrationProcedure,
		svc.GetSCMIntegration,
		connect.WithSchema(runnerConfigurationServiceMethods.ByName("GetSCMIntegration")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	runnerConfigurationServiceListSCMIntegrationsHandler := connect.NewUnaryHandler(
		RunnerConfigurationServiceListSCMIntegrationsProcedure,
		svc.ListSCMIntegrations,
		connect.WithSchema(runnerConfigurationServiceMethods.ByName("ListSCMIntegrations")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	runnerConfigurationServiceUpdateSCMIntegrationHandler := connect.NewUnaryHandler(
		RunnerConfigurationServiceUpdateSCMIntegrationProcedure,
		svc.UpdateSCMIntegration,
		connect.WithSchema(runnerConfigurationServiceMethods.ByName("UpdateSCMIntegration")),
		connect.WithHandlerOptions(opts...),
	)
	runnerConfigurationServiceDeleteSCMIntegrationHandler := connect.NewUnaryHandler(
		RunnerConfigurationServiceDeleteSCMIntegrationProcedure,
		svc.DeleteSCMIntegration,
		connect.WithSchema(runnerConfigurationServiceMethods.ByName("DeleteSCMIntegration")),
		connect.WithHandlerOptions(opts...),
	)
	runnerConfigurationServiceCreateEnvironmentClassHandler := connect.NewUnaryHandler(
		RunnerConfigurationServiceCreateEnvironmentClassProcedure,
		svc.CreateEnvironmentClass,
		connect.WithSchema(runnerConfigurationServiceMethods.ByName("CreateEnvironmentClass")),
		connect.WithHandlerOptions(opts...),
	)
	runnerConfigurationServiceGetEnvironmentClassHandler := connect.NewUnaryHandler(
		RunnerConfigurationServiceGetEnvironmentClassProcedure,
		svc.GetEnvironmentClass,
		connect.WithSchema(runnerConfigurationServiceMethods.ByName("GetEnvironmentClass")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	runnerConfigurationServiceListEnvironmentClassesHandler := connect.NewUnaryHandler(
		RunnerConfigurationServiceListEnvironmentClassesProcedure,
		svc.ListEnvironmentClasses,
		connect.WithSchema(runnerConfigurationServiceMethods.ByName("ListEnvironmentClasses")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	runnerConfigurationServiceUpdateEnvironmentClassHandler := connect.NewUnaryHandler(
		RunnerConfigurationServiceUpdateEnvironmentClassProcedure,
		svc.UpdateEnvironmentClass,
		connect.WithSchema(runnerConfigurationServiceMethods.ByName("UpdateEnvironmentClass")),
		connect.WithHandlerOptions(opts...),
	)
	runnerConfigurationServiceValidateRunnerConfigurationHandler := connect.NewUnaryHandler(
		RunnerConfigurationServiceValidateRunnerConfigurationProcedure,
		svc.ValidateRunnerConfiguration,
		connect.WithSchema(runnerConfigurationServiceMethods.ByName("ValidateRunnerConfiguration")),
		connect.WithHandlerOptions(opts...),
	)
	runnerConfigurationServiceCreateLLMIntegrationHandler := connect.NewUnaryHandler(
		RunnerConfigurationServiceCreateLLMIntegrationProcedure,
		svc.CreateLLMIntegration,
		connect.WithSchema(runnerConfigurationServiceMethods.ByName("CreateLLMIntegration")),
		connect.WithHandlerOptions(opts...),
	)
	runnerConfigurationServiceGetLLMIntegrationHandler := connect.NewUnaryHandler(
		RunnerConfigurationServiceGetLLMIntegrationProcedure,
		svc.GetLLMIntegration,
		connect.WithSchema(runnerConfigurationServiceMethods.ByName("GetLLMIntegration")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	runnerConfigurationServiceListLLMIntegrationsHandler := connect.NewUnaryHandler(
		RunnerConfigurationServiceListLLMIntegrationsProcedure,
		svc.ListLLMIntegrations,
		connect.WithSchema(runnerConfigurationServiceMethods.ByName("ListLLMIntegrations")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	runnerConfigurationServiceUpdateLLMIntegrationHandler := connect.NewUnaryHandler(
		RunnerConfigurationServiceUpdateLLMIntegrationProcedure,
		svc.UpdateLLMIntegration,
		connect.WithSchema(runnerConfigurationServiceMethods.ByName("UpdateLLMIntegration")),
		connect.WithHandlerOptions(opts...),
	)
	runnerConfigurationServiceDeleteLLMIntegrationHandler := connect.NewUnaryHandler(
		RunnerConfigurationServiceDeleteLLMIntegrationProcedure,
		svc.DeleteLLMIntegration,
		connect.WithSchema(runnerConfigurationServiceMethods.ByName("DeleteLLMIntegration")),
		connect.WithHandlerOptions(opts...),
	)
	return "/gitpod.v1.RunnerConfigurationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RunnerConfigurationServiceCreateHostAuthenticationTokenProcedure:
			runnerConfigurationServiceCreateHostAuthenticationTokenHandler.ServeHTTP(w, r)
		case RunnerConfigurationServiceGetHostAuthenticationTokenProcedure:
			runnerConfigurationServiceGetHostAuthenticationTokenHandler.ServeHTTP(w, r)
		case RunnerConfigurationServiceListHostAuthenticationTokensProcedure:
			runnerConfigurationServiceListHostAuthenticationTokensHandler.ServeHTTP(w, r)
		case RunnerConfigurationServiceUpdateHostAuthenticationTokenProcedure:
			runnerConfigurationServiceUpdateHostAuthenticationTokenHandler.ServeHTTP(w, r)
		case RunnerConfigurationServiceUpdateHostAuthenticationTokenMetadataProcedure:
			runnerConfigurationServiceUpdateHostAuthenticationTokenMetadataHandler.ServeHTTP(w, r)
		case RunnerConfigurationServiceDeleteHostAuthenticationTokenProcedure:
			runnerConfigurationServiceDeleteHostAuthenticationTokenHandler.ServeHTTP(w, r)
		case RunnerConfigurationServiceGetRunnerConfigurationSchemaProcedure:
			runnerConfigurationServiceGetRunnerConfigurationSchemaHandler.ServeHTTP(w, r)
		case RunnerConfigurationServiceCreateSCMIntegrationProcedure:
			runnerConfigurationServiceCreateSCMIntegrationHandler.ServeHTTP(w, r)
		case RunnerConfigurationServiceGetSCMIntegrationProcedure:
			runnerConfigurationServiceGetSCMIntegrationHandler.ServeHTTP(w, r)
		case RunnerConfigurationServiceListSCMIntegrationsProcedure:
			runnerConfigurationServiceListSCMIntegrationsHandler.ServeHTTP(w, r)
		case RunnerConfigurationServiceUpdateSCMIntegrationProcedure:
			runnerConfigurationServiceUpdateSCMIntegrationHandler.ServeHTTP(w, r)
		case RunnerConfigurationServiceDeleteSCMIntegrationProcedure:
			runnerConfigurationServiceDeleteSCMIntegrationHandler.ServeHTTP(w, r)
		case RunnerConfigurationServiceCreateEnvironmentClassProcedure:
			runnerConfigurationServiceCreateEnvironmentClassHandler.ServeHTTP(w, r)
		case RunnerConfigurationServiceGetEnvironmentClassProcedure:
			runnerConfigurationServiceGetEnvironmentClassHandler.ServeHTTP(w, r)
		case RunnerConfigurationServiceListEnvironmentClassesProcedure:
			runnerConfigurationServiceListEnvironmentClassesHandler.ServeHTTP(w, r)
		case RunnerConfigurationServiceUpdateEnvironmentClassProcedure:
			runnerConfigurationServiceUpdateEnvironmentClassHandler.ServeHTTP(w, r)
		case RunnerConfigurationServiceValidateRunnerConfigurationProcedure:
			runnerConfigurationServiceValidateRunnerConfigurationHandler.ServeHTTP(w, r)
		case RunnerConfigurationServiceCreateLLMIntegrationProcedure:
			runnerConfigurationServiceCreateLLMIntegrationHandler.ServeHTTP(w, r)
		case RunnerConfigurationServiceGetLLMIntegrationProcedure:
			runnerConfigurationServiceGetLLMIntegrationHandler.ServeHTTP(w, r)
		case RunnerConfigurationServiceListLLMIntegrationsProcedure:
			runnerConfigurationServiceListLLMIntegrationsHandler.ServeHTTP(w, r)
		case RunnerConfigurationServiceUpdateLLMIntegrationProcedure:
			runnerConfigurationServiceUpdateLLMIntegrationHandler.ServeHTTP(w, r)
		case RunnerConfigurationServiceDeleteLLMIntegrationProcedure:
			runnerConfigurationServiceDeleteLLMIntegrationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRunnerConfigurationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRunnerConfigurationServiceHandler struct{}

func (UnimplementedRunnerConfigurationServiceHandler) CreateHostAuthenticationToken(context.Context, *connect.Request[v1.CreateHostAuthenticationTokenRequest]) (*connect.Response[v1.CreateHostAuthenticationTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.RunnerConfigurationService.CreateHostAuthenticationToken is not implemented"))
}

func (UnimplementedRunnerConfigurationServiceHandler) GetHostAuthenticationToken(context.Context, *connect.Request[v1.GetHostAuthenticationTokenRequest]) (*connect.Response[v1.GetHostAuthenticationTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.RunnerConfigurationService.GetHostAuthenticationToken is not implemented"))
}

func (UnimplementedRunnerConfigurationServiceHandler) ListHostAuthenticationTokens(context.Context, *connect.Request[v1.ListHostAuthenticationTokensRequest]) (*connect.Response[v1.ListHostAuthenticationTokensResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.RunnerConfigurationService.ListHostAuthenticationTokens is not implemented"))
}

func (UnimplementedRunnerConfigurationServiceHandler) UpdateHostAuthenticationToken(context.Context, *connect.Request[v1.UpdateHostAuthenticationTokenRequest]) (*connect.Response[v1.UpdateHostAuthenticationTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.RunnerConfigurationService.UpdateHostAuthenticationToken is not implemented"))
}

func (UnimplementedRunnerConfigurationServiceHandler) UpdateHostAuthenticationTokenMetadata(context.Context, *connect.Request[v1.UpdateHostAuthenticationTokenMetadataRequest]) (*connect.Response[v1.UpdateHostAuthenticationTokenMetadataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.RunnerConfigurationService.UpdateHostAuthenticationTokenMetadata is not implemented"))
}

func (UnimplementedRunnerConfigurationServiceHandler) DeleteHostAuthenticationToken(context.Context, *connect.Request[v1.DeleteHostAuthenticationTokenRequest]) (*connect.Response[v1.DeleteHostAuthenticationTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.RunnerConfigurationService.DeleteHostAuthenticationToken is not implemented"))
}

func (UnimplementedRunnerConfigurationServiceHandler) GetRunnerConfigurationSchema(context.Context, *connect.Request[v1.GetRunnerConfigurationSchemaRequest]) (*connect.Response[v1.GetRunnerConfigurationSchemaResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.RunnerConfigurationService.GetRunnerConfigurationSchema is not implemented"))
}

func (UnimplementedRunnerConfigurationServiceHandler) CreateSCMIntegration(context.Context, *connect.Request[v1.CreateSCMIntegrationRequest]) (*connect.Response[v1.CreateSCMIntegrationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.RunnerConfigurationService.CreateSCMIntegration is not implemented"))
}

func (UnimplementedRunnerConfigurationServiceHandler) GetSCMIntegration(context.Context, *connect.Request[v1.GetSCMIntegrationRequest]) (*connect.Response[v1.GetSCMIntegrationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.RunnerConfigurationService.GetSCMIntegration is not implemented"))
}

func (UnimplementedRunnerConfigurationServiceHandler) ListSCMIntegrations(context.Context, *connect.Request[v1.ListSCMIntegrationsRequest]) (*connect.Response[v1.ListSCMIntegrationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.RunnerConfigurationService.ListSCMIntegrations is not implemented"))
}

func (UnimplementedRunnerConfigurationServiceHandler) UpdateSCMIntegration(context.Context, *connect.Request[v1.UpdateSCMIntegrationRequest]) (*connect.Response[v1.UpdateSCMIntegrationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.RunnerConfigurationService.UpdateSCMIntegration is not implemented"))
}

func (UnimplementedRunnerConfigurationServiceHandler) DeleteSCMIntegration(context.Context, *connect.Request[v1.DeleteSCMIntegrationRequest]) (*connect.Response[v1.DeleteSCMIntegrationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.RunnerConfigurationService.DeleteSCMIntegration is not implemented"))
}

func (UnimplementedRunnerConfigurationServiceHandler) CreateEnvironmentClass(context.Context, *connect.Request[v1.CreateEnvironmentClassRequest]) (*connect.Response[v1.CreateEnvironmentClassResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.RunnerConfigurationService.CreateEnvironmentClass is not implemented"))
}

func (UnimplementedRunnerConfigurationServiceHandler) GetEnvironmentClass(context.Context, *connect.Request[v1.GetEnvironmentClassRequest]) (*connect.Response[v1.GetEnvironmentClassResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.RunnerConfigurationService.GetEnvironmentClass is not implemented"))
}

func (UnimplementedRunnerConfigurationServiceHandler) ListEnvironmentClasses(context.Context, *connect.Request[v1.ListEnvironmentClassesRequest]) (*connect.Response[v1.ListEnvironmentClassesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.RunnerConfigurationService.ListEnvironmentClasses is not implemented"))
}

func (UnimplementedRunnerConfigurationServiceHandler) UpdateEnvironmentClass(context.Context, *connect.Request[v1.UpdateEnvironmentClassRequest]) (*connect.Response[v1.UpdateEnvironmentClassResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.RunnerConfigurationService.UpdateEnvironmentClass is not implemented"))
}

func (UnimplementedRunnerConfigurationServiceHandler) ValidateRunnerConfiguration(context.Context, *connect.Request[v1.ValidateRunnerConfigurationRequest]) (*connect.Response[v1.ValidateRunnerConfigurationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.RunnerConfigurationService.ValidateRunnerConfiguration is not implemented"))
}

func (UnimplementedRunnerConfigurationServiceHandler) CreateLLMIntegration(context.Context, *connect.Request[v1.CreateLLMIntegrationRequest]) (*connect.Response[v1.CreateLLMIntegrationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.RunnerConfigurationService.CreateLLMIntegration is not implemented"))
}

func (UnimplementedRunnerConfigurationServiceHandler) GetLLMIntegration(context.Context, *connect.Request[v1.GetLLMIntegrationRequest]) (*connect.Response[v1.GetLLMIntegrationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.RunnerConfigurationService.GetLLMIntegration is not implemented"))
}

func (UnimplementedRunnerConfigurationServiceHandler) ListLLMIntegrations(context.Context, *connect.Request[v1.ListLLMIntegrationsRequest]) (*connect.Response[v1.ListLLMIntegrationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.RunnerConfigurationService.ListLLMIntegrations is not implemented"))
}

func (UnimplementedRunnerConfigurationServiceHandler) UpdateLLMIntegration(context.Context, *connect.Request[v1.UpdateLLMIntegrationRequest]) (*connect.Response[v1.UpdateLLMIntegrationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.RunnerConfigurationService.UpdateLLMIntegration is not implemented"))
}

func (UnimplementedRunnerConfigurationServiceHandler) DeleteLLMIntegration(context.Context, *connect.Request[v1.DeleteLLMIntegrationRequest]) (*connect.Response[v1.DeleteLLMIntegrationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitpod.v1.RunnerConfigurationService.DeleteLLMIntegration is not implemented"))
}
