// Code generated by MockGen. DO NOT EDIT.
// Source: ../../v1/v1connect/group.connect.go
//
// Generated by this command:
//
//	mockgen -source=../../v1/v1connect/group.connect.go -destination=group.connect_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	connect "connectrpc.com/connect"
	v1 "github.com/gitpod-io/terraform-provider-ona/internal/api/go/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockGroupServiceClient is a mock of GroupServiceClient interface.
type MockGroupServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockGroupServiceClientMockRecorder
	isgomock struct{}
}

// MockGroupServiceClientMockRecorder is the mock recorder for MockGroupServiceClient.
type MockGroupServiceClientMockRecorder struct {
	mock *MockGroupServiceClient
}

// NewMockGroupServiceClient creates a new mock instance.
func NewMockGroupServiceClient(ctrl *gomock.Controller) *MockGroupServiceClient {
	mock := &MockGroupServiceClient{ctrl: ctrl}
	mock.recorder = &MockGroupServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupServiceClient) EXPECT() *MockGroupServiceClientMockRecorder {
	return m.recorder
}

// CreateGroup mocks base method.
func (m *MockGroupServiceClient) CreateGroup(arg0 context.Context, arg1 *connect.Request[v1.CreateGroupRequest]) (*connect.Response[v1.CreateGroupResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroup", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.CreateGroupResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockGroupServiceClientMockRecorder) CreateGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroup", reflect.TypeOf((*MockGroupServiceClient)(nil).CreateGroup), arg0, arg1)
}

// CreateMembership mocks base method.
func (m *MockGroupServiceClient) CreateMembership(arg0 context.Context, arg1 *connect.Request[v1.CreateMembershipRequest]) (*connect.Response[v1.CreateMembershipResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMembership", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.CreateMembershipResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMembership indicates an expected call of CreateMembership.
func (mr *MockGroupServiceClientMockRecorder) CreateMembership(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMembership", reflect.TypeOf((*MockGroupServiceClient)(nil).CreateMembership), arg0, arg1)
}

// CreateRoleAssignment mocks base method.
func (m *MockGroupServiceClient) CreateRoleAssignment(arg0 context.Context, arg1 *connect.Request[v1.CreateRoleAssignmentRequest]) (*connect.Response[v1.CreateRoleAssignmentResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoleAssignment", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.CreateRoleAssignmentResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoleAssignment indicates an expected call of CreateRoleAssignment.
func (mr *MockGroupServiceClientMockRecorder) CreateRoleAssignment(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoleAssignment", reflect.TypeOf((*MockGroupServiceClient)(nil).CreateRoleAssignment), arg0, arg1)
}

// DeleteGroup mocks base method.
func (m *MockGroupServiceClient) DeleteGroup(arg0 context.Context, arg1 *connect.Request[v1.DeleteGroupRequest]) (*connect.Response[v1.DeleteGroupResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroup", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.DeleteGroupResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteGroup indicates an expected call of DeleteGroup.
func (mr *MockGroupServiceClientMockRecorder) DeleteGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroup", reflect.TypeOf((*MockGroupServiceClient)(nil).DeleteGroup), arg0, arg1)
}

// DeleteMembership mocks base method.
func (m *MockGroupServiceClient) DeleteMembership(arg0 context.Context, arg1 *connect.Request[v1.DeleteMembershipRequest]) (*connect.Response[v1.DeleteMembershipResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMembership", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.DeleteMembershipResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMembership indicates an expected call of DeleteMembership.
func (mr *MockGroupServiceClientMockRecorder) DeleteMembership(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMembership", reflect.TypeOf((*MockGroupServiceClient)(nil).DeleteMembership), arg0, arg1)
}

// DeleteRoleAssignment mocks base method.
func (m *MockGroupServiceClient) DeleteRoleAssignment(arg0 context.Context, arg1 *connect.Request[v1.DeleteRoleAssignmentRequest]) (*connect.Response[v1.DeleteRoleAssignmentResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoleAssignment", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.DeleteRoleAssignmentResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRoleAssignment indicates an expected call of DeleteRoleAssignment.
func (mr *MockGroupServiceClientMockRecorder) DeleteRoleAssignment(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoleAssignment", reflect.TypeOf((*MockGroupServiceClient)(nil).DeleteRoleAssignment), arg0, arg1)
}

// GetGroup mocks base method.
func (m *MockGroupServiceClient) GetGroup(arg0 context.Context, arg1 *connect.Request[v1.GetGroupRequest]) (*connect.Response[v1.GetGroupResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroup", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetGroupResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroup indicates an expected call of GetGroup.
func (mr *MockGroupServiceClientMockRecorder) GetGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroup", reflect.TypeOf((*MockGroupServiceClient)(nil).GetGroup), arg0, arg1)
}

// GetMembership mocks base method.
func (m *MockGroupServiceClient) GetMembership(arg0 context.Context, arg1 *connect.Request[v1.GetMembershipRequest]) (*connect.Response[v1.GetMembershipResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembership", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetMembershipResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembership indicates an expected call of GetMembership.
func (mr *MockGroupServiceClientMockRecorder) GetMembership(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembership", reflect.TypeOf((*MockGroupServiceClient)(nil).GetMembership), arg0, arg1)
}

// ListGroups mocks base method.
func (m *MockGroupServiceClient) ListGroups(arg0 context.Context, arg1 *connect.Request[v1.ListGroupsRequest]) (*connect.Response[v1.ListGroupsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroups", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListGroupsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroups indicates an expected call of ListGroups.
func (mr *MockGroupServiceClientMockRecorder) ListGroups(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroups", reflect.TypeOf((*MockGroupServiceClient)(nil).ListGroups), arg0, arg1)
}

// ListMemberships mocks base method.
func (m *MockGroupServiceClient) ListMemberships(arg0 context.Context, arg1 *connect.Request[v1.ListMembershipsRequest]) (*connect.Response[v1.ListMembershipsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMemberships", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListMembershipsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMemberships indicates an expected call of ListMemberships.
func (mr *MockGroupServiceClientMockRecorder) ListMemberships(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMemberships", reflect.TypeOf((*MockGroupServiceClient)(nil).ListMemberships), arg0, arg1)
}

// ListRoleAssignments mocks base method.
func (m *MockGroupServiceClient) ListRoleAssignments(arg0 context.Context, arg1 *connect.Request[v1.ListRoleAssignmentsRequest]) (*connect.Response[v1.ListRoleAssignmentsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoleAssignments", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListRoleAssignmentsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoleAssignments indicates an expected call of ListRoleAssignments.
func (mr *MockGroupServiceClientMockRecorder) ListRoleAssignments(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoleAssignments", reflect.TypeOf((*MockGroupServiceClient)(nil).ListRoleAssignments), arg0, arg1)
}

// ShareResourceWithPrincipal mocks base method.
func (m *MockGroupServiceClient) ShareResourceWithPrincipal(arg0 context.Context, arg1 *connect.Request[v1.ShareResourceWithPrincipalRequest]) (*connect.Response[v1.ShareResourceWithPrincipalResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShareResourceWithPrincipal", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ShareResourceWithPrincipalResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShareResourceWithPrincipal indicates an expected call of ShareResourceWithPrincipal.
func (mr *MockGroupServiceClientMockRecorder) ShareResourceWithPrincipal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShareResourceWithPrincipal", reflect.TypeOf((*MockGroupServiceClient)(nil).ShareResourceWithPrincipal), arg0, arg1)
}

// UnshareResourceWithPrincipal mocks base method.
func (m *MockGroupServiceClient) UnshareResourceWithPrincipal(arg0 context.Context, arg1 *connect.Request[v1.UnshareResourceWithPrincipalRequest]) (*connect.Response[v1.UnshareResourceWithPrincipalResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnshareResourceWithPrincipal", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.UnshareResourceWithPrincipalResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnshareResourceWithPrincipal indicates an expected call of UnshareResourceWithPrincipal.
func (mr *MockGroupServiceClientMockRecorder) UnshareResourceWithPrincipal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnshareResourceWithPrincipal", reflect.TypeOf((*MockGroupServiceClient)(nil).UnshareResourceWithPrincipal), arg0, arg1)
}

// UpdateGroup mocks base method.
func (m *MockGroupServiceClient) UpdateGroup(arg0 context.Context, arg1 *connect.Request[v1.UpdateGroupRequest]) (*connect.Response[v1.UpdateGroupResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroup", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.UpdateGroupResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGroup indicates an expected call of UpdateGroup.
func (mr *MockGroupServiceClientMockRecorder) UpdateGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroup", reflect.TypeOf((*MockGroupServiceClient)(nil).UpdateGroup), arg0, arg1)
}

// MockGroupServiceHandler is a mock of GroupServiceHandler interface.
type MockGroupServiceHandler struct {
	ctrl     *gomock.Controller
	recorder *MockGroupServiceHandlerMockRecorder
	isgomock struct{}
}

// MockGroupServiceHandlerMockRecorder is the mock recorder for MockGroupServiceHandler.
type MockGroupServiceHandlerMockRecorder struct {
	mock *MockGroupServiceHandler
}

// NewMockGroupServiceHandler creates a new mock instance.
func NewMockGroupServiceHandler(ctrl *gomock.Controller) *MockGroupServiceHandler {
	mock := &MockGroupServiceHandler{ctrl: ctrl}
	mock.recorder = &MockGroupServiceHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupServiceHandler) EXPECT() *MockGroupServiceHandlerMockRecorder {
	return m.recorder
}

// CreateGroup mocks base method.
func (m *MockGroupServiceHandler) CreateGroup(arg0 context.Context, arg1 *connect.Request[v1.CreateGroupRequest]) (*connect.Response[v1.CreateGroupResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroup", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.CreateGroupResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockGroupServiceHandlerMockRecorder) CreateGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroup", reflect.TypeOf((*MockGroupServiceHandler)(nil).CreateGroup), arg0, arg1)
}

// CreateMembership mocks base method.
func (m *MockGroupServiceHandler) CreateMembership(arg0 context.Context, arg1 *connect.Request[v1.CreateMembershipRequest]) (*connect.Response[v1.CreateMembershipResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMembership", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.CreateMembershipResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMembership indicates an expected call of CreateMembership.
func (mr *MockGroupServiceHandlerMockRecorder) CreateMembership(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMembership", reflect.TypeOf((*MockGroupServiceHandler)(nil).CreateMembership), arg0, arg1)
}

// CreateRoleAssignment mocks base method.
func (m *MockGroupServiceHandler) CreateRoleAssignment(arg0 context.Context, arg1 *connect.Request[v1.CreateRoleAssignmentRequest]) (*connect.Response[v1.CreateRoleAssignmentResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoleAssignment", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.CreateRoleAssignmentResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoleAssignment indicates an expected call of CreateRoleAssignment.
func (mr *MockGroupServiceHandlerMockRecorder) CreateRoleAssignment(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoleAssignment", reflect.TypeOf((*MockGroupServiceHandler)(nil).CreateRoleAssignment), arg0, arg1)
}

// DeleteGroup mocks base method.
func (m *MockGroupServiceHandler) DeleteGroup(arg0 context.Context, arg1 *connect.Request[v1.DeleteGroupRequest]) (*connect.Response[v1.DeleteGroupResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroup", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.DeleteGroupResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteGroup indicates an expected call of DeleteGroup.
func (mr *MockGroupServiceHandlerMockRecorder) DeleteGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroup", reflect.TypeOf((*MockGroupServiceHandler)(nil).DeleteGroup), arg0, arg1)
}

// DeleteMembership mocks base method.
func (m *MockGroupServiceHandler) DeleteMembership(arg0 context.Context, arg1 *connect.Request[v1.DeleteMembershipRequest]) (*connect.Response[v1.DeleteMembershipResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMembership", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.DeleteMembershipResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMembership indicates an expected call of DeleteMembership.
func (mr *MockGroupServiceHandlerMockRecorder) DeleteMembership(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMembership", reflect.TypeOf((*MockGroupServiceHandler)(nil).DeleteMembership), arg0, arg1)
}

// DeleteRoleAssignment mocks base method.
func (m *MockGroupServiceHandler) DeleteRoleAssignment(arg0 context.Context, arg1 *connect.Request[v1.DeleteRoleAssignmentRequest]) (*connect.Response[v1.DeleteRoleAssignmentResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoleAssignment", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.DeleteRoleAssignmentResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRoleAssignment indicates an expected call of DeleteRoleAssignment.
func (mr *MockGroupServiceHandlerMockRecorder) DeleteRoleAssignment(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoleAssignment", reflect.TypeOf((*MockGroupServiceHandler)(nil).DeleteRoleAssignment), arg0, arg1)
}

// GetGroup mocks base method.
func (m *MockGroupServiceHandler) GetGroup(arg0 context.Context, arg1 *connect.Request[v1.GetGroupRequest]) (*connect.Response[v1.GetGroupResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroup", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetGroupResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroup indicates an expected call of GetGroup.
func (mr *MockGroupServiceHandlerMockRecorder) GetGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroup", reflect.TypeOf((*MockGroupServiceHandler)(nil).GetGroup), arg0, arg1)
}

// GetMembership mocks base method.
func (m *MockGroupServiceHandler) GetMembership(arg0 context.Context, arg1 *connect.Request[v1.GetMembershipRequest]) (*connect.Response[v1.GetMembershipResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembership", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetMembershipResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembership indicates an expected call of GetMembership.
func (mr *MockGroupServiceHandlerMockRecorder) GetMembership(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembership", reflect.TypeOf((*MockGroupServiceHandler)(nil).GetMembership), arg0, arg1)
}

// ListGroups mocks base method.
func (m *MockGroupServiceHandler) ListGroups(arg0 context.Context, arg1 *connect.Request[v1.ListGroupsRequest]) (*connect.Response[v1.ListGroupsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroups", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListGroupsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroups indicates an expected call of ListGroups.
func (mr *MockGroupServiceHandlerMockRecorder) ListGroups(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroups", reflect.TypeOf((*MockGroupServiceHandler)(nil).ListGroups), arg0, arg1)
}

// ListMemberships mocks base method.
func (m *MockGroupServiceHandler) ListMemberships(arg0 context.Context, arg1 *connect.Request[v1.ListMembershipsRequest]) (*connect.Response[v1.ListMembershipsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMemberships", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListMembershipsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMemberships indicates an expected call of ListMemberships.
func (mr *MockGroupServiceHandlerMockRecorder) ListMemberships(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMemberships", reflect.TypeOf((*MockGroupServiceHandler)(nil).ListMemberships), arg0, arg1)
}

// ListRoleAssignments mocks base method.
func (m *MockGroupServiceHandler) ListRoleAssignments(arg0 context.Context, arg1 *connect.Request[v1.ListRoleAssignmentsRequest]) (*connect.Response[v1.ListRoleAssignmentsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoleAssignments", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListRoleAssignmentsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoleAssignments indicates an expected call of ListRoleAssignments.
func (mr *MockGroupServiceHandlerMockRecorder) ListRoleAssignments(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoleAssignments", reflect.TypeOf((*MockGroupServiceHandler)(nil).ListRoleAssignments), arg0, arg1)
}

// ShareResourceWithPrincipal mocks base method.
func (m *MockGroupServiceHandler) ShareResourceWithPrincipal(arg0 context.Context, arg1 *connect.Request[v1.ShareResourceWithPrincipalRequest]) (*connect.Response[v1.ShareResourceWithPrincipalResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShareResourceWithPrincipal", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ShareResourceWithPrincipalResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShareResourceWithPrincipal indicates an expected call of ShareResourceWithPrincipal.
func (mr *MockGroupServiceHandlerMockRecorder) ShareResourceWithPrincipal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShareResourceWithPrincipal", reflect.TypeOf((*MockGroupServiceHandler)(nil).ShareResourceWithPrincipal), arg0, arg1)
}

// UnshareResourceWithPrincipal mocks base method.
func (m *MockGroupServiceHandler) UnshareResourceWithPrincipal(arg0 context.Context, arg1 *connect.Request[v1.UnshareResourceWithPrincipalRequest]) (*connect.Response[v1.UnshareResourceWithPrincipalResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnshareResourceWithPrincipal", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.UnshareResourceWithPrincipalResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnshareResourceWithPrincipal indicates an expected call of UnshareResourceWithPrincipal.
func (mr *MockGroupServiceHandlerMockRecorder) UnshareResourceWithPrincipal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnshareResourceWithPrincipal", reflect.TypeOf((*MockGroupServiceHandler)(nil).UnshareResourceWithPrincipal), arg0, arg1)
}

// UpdateGroup mocks base method.
func (m *MockGroupServiceHandler) UpdateGroup(arg0 context.Context, arg1 *connect.Request[v1.UpdateGroupRequest]) (*connect.Response[v1.UpdateGroupResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroup", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.UpdateGroupResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGroup indicates an expected call of UpdateGroup.
func (mr *MockGroupServiceHandlerMockRecorder) UpdateGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroup", reflect.TypeOf((*MockGroupServiceHandler)(nil).UpdateGroup), arg0, arg1)
}
