// Code generated by MockGen. DO NOT EDIT.
// Source: ../../v1/v1connect/webhook.connect.go
//
// Generated by this command:
//
//	mockgen -source=../../v1/v1connect/webhook.connect.go -destination=webhook.connect_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	connect "connectrpc.com/connect"
	v1 "github.com/gitpod-io/terraform-provider-ona/internal/api/go/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhookServiceClient is a mock of WebhookServiceClient interface.
type MockWebhookServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookServiceClientMockRecorder
	isgomock struct{}
}

// MockWebhookServiceClientMockRecorder is the mock recorder for MockWebhookServiceClient.
type MockWebhookServiceClientMockRecorder struct {
	mock *MockWebhookServiceClient
}

// NewMockWebhookServiceClient creates a new mock instance.
func NewMockWebhookServiceClient(ctrl *gomock.Controller) *MockWebhookServiceClient {
	mock := &MockWebhookServiceClient{ctrl: ctrl}
	mock.recorder = &MockWebhookServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookServiceClient) EXPECT() *MockWebhookServiceClientMockRecorder {
	return m.recorder
}

// CreateWebhook mocks base method.
func (m *MockWebhookServiceClient) CreateWebhook(arg0 context.Context, arg1 *connect.Request[v1.CreateWebhookRequest]) (*connect.Response[v1.CreateWebhookResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWebhook", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.CreateWebhookResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWebhook indicates an expected call of CreateWebhook.
func (mr *MockWebhookServiceClientMockRecorder) CreateWebhook(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWebhook", reflect.TypeOf((*MockWebhookServiceClient)(nil).CreateWebhook), arg0, arg1)
}

// DeleteWebhook mocks base method.
func (m *MockWebhookServiceClient) DeleteWebhook(arg0 context.Context, arg1 *connect.Request[v1.DeleteWebhookRequest]) (*connect.Response[v1.DeleteWebhookResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWebhook", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.DeleteWebhookResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteWebhook indicates an expected call of DeleteWebhook.
func (mr *MockWebhookServiceClientMockRecorder) DeleteWebhook(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWebhook", reflect.TypeOf((*MockWebhookServiceClient)(nil).DeleteWebhook), arg0, arg1)
}

// GetWebhook mocks base method.
func (m *MockWebhookServiceClient) GetWebhook(arg0 context.Context, arg1 *connect.Request[v1.GetWebhookRequest]) (*connect.Response[v1.GetWebhookResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhook", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetWebhookResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhook indicates an expected call of GetWebhook.
func (mr *MockWebhookServiceClientMockRecorder) GetWebhook(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhook", reflect.TypeOf((*MockWebhookServiceClient)(nil).GetWebhook), arg0, arg1)
}

// GetWebhookSecret mocks base method.
func (m *MockWebhookServiceClient) GetWebhookSecret(arg0 context.Context, arg1 *connect.Request[v1.GetWebhookSecretRequest]) (*connect.Response[v1.GetWebhookSecretResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhookSecret", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetWebhookSecretResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhookSecret indicates an expected call of GetWebhookSecret.
func (mr *MockWebhookServiceClientMockRecorder) GetWebhookSecret(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhookSecret", reflect.TypeOf((*MockWebhookServiceClient)(nil).GetWebhookSecret), arg0, arg1)
}

// ListWebhookWorkflows mocks base method.
func (m *MockWebhookServiceClient) ListWebhookWorkflows(arg0 context.Context, arg1 *connect.Request[v1.ListWebhookWorkflowsRequest]) (*connect.Response[v1.ListWebhookWorkflowsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWebhookWorkflows", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListWebhookWorkflowsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWebhookWorkflows indicates an expected call of ListWebhookWorkflows.
func (mr *MockWebhookServiceClientMockRecorder) ListWebhookWorkflows(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWebhookWorkflows", reflect.TypeOf((*MockWebhookServiceClient)(nil).ListWebhookWorkflows), arg0, arg1)
}

// ListWebhooks mocks base method.
func (m *MockWebhookServiceClient) ListWebhooks(arg0 context.Context, arg1 *connect.Request[v1.ListWebhooksRequest]) (*connect.Response[v1.ListWebhooksResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWebhooks", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListWebhooksResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWebhooks indicates an expected call of ListWebhooks.
func (mr *MockWebhookServiceClientMockRecorder) ListWebhooks(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWebhooks", reflect.TypeOf((*MockWebhookServiceClient)(nil).ListWebhooks), arg0, arg1)
}

// RotateWebhookSecret mocks base method.
func (m *MockWebhookServiceClient) RotateWebhookSecret(arg0 context.Context, arg1 *connect.Request[v1.RotateWebhookSecretRequest]) (*connect.Response[v1.RotateWebhookSecretResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateWebhookSecret", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.RotateWebhookSecretResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RotateWebhookSecret indicates an expected call of RotateWebhookSecret.
func (mr *MockWebhookServiceClientMockRecorder) RotateWebhookSecret(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateWebhookSecret", reflect.TypeOf((*MockWebhookServiceClient)(nil).RotateWebhookSecret), arg0, arg1)
}

// UpdateWebhook mocks base method.
func (m *MockWebhookServiceClient) UpdateWebhook(arg0 context.Context, arg1 *connect.Request[v1.UpdateWebhookRequest]) (*connect.Response[v1.UpdateWebhookResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWebhook", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.UpdateWebhookResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWebhook indicates an expected call of UpdateWebhook.
func (mr *MockWebhookServiceClientMockRecorder) UpdateWebhook(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWebhook", reflect.TypeOf((*MockWebhookServiceClient)(nil).UpdateWebhook), arg0, arg1)
}

// MockWebhookServiceHandler is a mock of WebhookServiceHandler interface.
type MockWebhookServiceHandler struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookServiceHandlerMockRecorder
	isgomock struct{}
}

// MockWebhookServiceHandlerMockRecorder is the mock recorder for MockWebhookServiceHandler.
type MockWebhookServiceHandlerMockRecorder struct {
	mock *MockWebhookServiceHandler
}

// NewMockWebhookServiceHandler creates a new mock instance.
func NewMockWebhookServiceHandler(ctrl *gomock.Controller) *MockWebhookServiceHandler {
	mock := &MockWebhookServiceHandler{ctrl: ctrl}
	mock.recorder = &MockWebhookServiceHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookServiceHandler) EXPECT() *MockWebhookServiceHandlerMockRecorder {
	return m.recorder
}

// CreateWebhook mocks base method.
func (m *MockWebhookServiceHandler) CreateWebhook(arg0 context.Context, arg1 *connect.Request[v1.CreateWebhookRequest]) (*connect.Response[v1.CreateWebhookResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWebhook", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.CreateWebhookResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWebhook indicates an expected call of CreateWebhook.
func (mr *MockWebhookServiceHandlerMockRecorder) CreateWebhook(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWebhook", reflect.TypeOf((*MockWebhookServiceHandler)(nil).CreateWebhook), arg0, arg1)
}

// DeleteWebhook mocks base method.
func (m *MockWebhookServiceHandler) DeleteWebhook(arg0 context.Context, arg1 *connect.Request[v1.DeleteWebhookRequest]) (*connect.Response[v1.DeleteWebhookResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWebhook", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.DeleteWebhookResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteWebhook indicates an expected call of DeleteWebhook.
func (mr *MockWebhookServiceHandlerMockRecorder) DeleteWebhook(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWebhook", reflect.TypeOf((*MockWebhookServiceHandler)(nil).DeleteWebhook), arg0, arg1)
}

// GetWebhook mocks base method.
func (m *MockWebhookServiceHandler) GetWebhook(arg0 context.Context, arg1 *connect.Request[v1.GetWebhookRequest]) (*connect.Response[v1.GetWebhookResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhook", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetWebhookResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhook indicates an expected call of GetWebhook.
func (mr *MockWebhookServiceHandlerMockRecorder) GetWebhook(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhook", reflect.TypeOf((*MockWebhookServiceHandler)(nil).GetWebhook), arg0, arg1)
}

// GetWebhookSecret mocks base method.
func (m *MockWebhookServiceHandler) GetWebhookSecret(arg0 context.Context, arg1 *connect.Request[v1.GetWebhookSecretRequest]) (*connect.Response[v1.GetWebhookSecretResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhookSecret", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetWebhookSecretResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhookSecret indicates an expected call of GetWebhookSecret.
func (mr *MockWebhookServiceHandlerMockRecorder) GetWebhookSecret(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhookSecret", reflect.TypeOf((*MockWebhookServiceHandler)(nil).GetWebhookSecret), arg0, arg1)
}

// ListWebhookWorkflows mocks base method.
func (m *MockWebhookServiceHandler) ListWebhookWorkflows(arg0 context.Context, arg1 *connect.Request[v1.ListWebhookWorkflowsRequest]) (*connect.Response[v1.ListWebhookWorkflowsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWebhookWorkflows", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListWebhookWorkflowsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWebhookWorkflows indicates an expected call of ListWebhookWorkflows.
func (mr *MockWebhookServiceHandlerMockRecorder) ListWebhookWorkflows(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWebhookWorkflows", reflect.TypeOf((*MockWebhookServiceHandler)(nil).ListWebhookWorkflows), arg0, arg1)
}

// ListWebhooks mocks base method.
func (m *MockWebhookServiceHandler) ListWebhooks(arg0 context.Context, arg1 *connect.Request[v1.ListWebhooksRequest]) (*connect.Response[v1.ListWebhooksResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWebhooks", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListWebhooksResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWebhooks indicates an expected call of ListWebhooks.
func (mr *MockWebhookServiceHandlerMockRecorder) ListWebhooks(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWebhooks", reflect.TypeOf((*MockWebhookServiceHandler)(nil).ListWebhooks), arg0, arg1)
}

// RotateWebhookSecret mocks base method.
func (m *MockWebhookServiceHandler) RotateWebhookSecret(arg0 context.Context, arg1 *connect.Request[v1.RotateWebhookSecretRequest]) (*connect.Response[v1.RotateWebhookSecretResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateWebhookSecret", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.RotateWebhookSecretResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RotateWebhookSecret indicates an expected call of RotateWebhookSecret.
func (mr *MockWebhookServiceHandlerMockRecorder) RotateWebhookSecret(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateWebhookSecret", reflect.TypeOf((*MockWebhookServiceHandler)(nil).RotateWebhookSecret), arg0, arg1)
}

// UpdateWebhook mocks base method.
func (m *MockWebhookServiceHandler) UpdateWebhook(arg0 context.Context, arg1 *connect.Request[v1.UpdateWebhookRequest]) (*connect.Response[v1.UpdateWebhookResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWebhook", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.UpdateWebhookResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWebhook indicates an expected call of UpdateWebhook.
func (mr *MockWebhookServiceHandlerMockRecorder) UpdateWebhook(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWebhook", reflect.TypeOf((*MockWebhookServiceHandler)(nil).UpdateWebhook), arg0, arg1)
}
